import { ImageType, CTA as CTAType } from "@yext/pages-components";

// TODO: Update any types as necessary since these are not autogenerated so might be off

export type HeroSectionType = {
  image?: ImageType;
  primaryCta?: CTAType;
  secondaryCta?: CTAType;
};

export type PromoSectionType = {
  image?: ImageType;
  title?: string;
  description?: RTF2 | string;
  cta?: CTAType;
};

export type ProductSectionType = Array<ProductStruct>;

export type ProductStruct = {
  image?: ImageType;
  heading?: string;
  description?: RTF2;
  category?: string;
  cta?: CTAType;
};

export type EventSectionType = Array<EventStruct>;

export type EventStruct = {
  image?: ImageType;
  title?: string;
  dateTime?: dateTime;
  description?: RTF2;
  cta?: CTAType;
};

export type FAQSectionType = Array<FAQStruct>;

export type FAQStruct = {
  question: string;
  answer: RTF2;
};

export type TestimonialSectionType = Array<TestimonialStruct>;

export type TestimonialStruct = {
  description?: RTF2;
  contributorName?: string;
  contributionDateTime?: string;
};

export type InsightSectionType = Array<InsightStruct>;

export type InsightStruct = {
  image?: ImageType;
  name?: string;
  category?: string;
  publishTime?: dateTime;
  description?: RTF2;
  cta?: CTAType;
};

export type TeamSectionType = Array<PersonStruct>;

export type PersonStruct = {
  headshot?: ImageType;
  name?: string;
  title?: string;
  phoneNumber?: string;
  email?: string;
  cta?: CTAType;
};

type dateTime = {
  start?: string; // ISO 8601
  end?: string; //  ISO 8601
};

type RTF2 = {
  html?: string;
};
