import path from "node:path";
import fs from "fs-extra";
import { buildEditorTemplateSource } from "../registry/registryTemplateGenerator.ts";
import { getLocalEditorManifest } from "./data.ts";
import {
  buildLocalEditorDataTemplatePath,
  buildLocalEditorDataTemplateSource,
  DEFAULT_LOCAL_EDITOR_STREAM_CONFIG_PATH,
  isGeneratedLocalEditorTemplate,
  LEGACY_LOCAL_EDITOR_DATA_TEMPLATE_PATH,
  LOCAL_EDITOR_DATA_TEMPLATE_PREFIX,
  toAbsoluteLocalEditorPath,
} from "./generatedFiles.ts";
import { writeFileIfChanged } from "./utils.ts";

type CreateLocalEditorArtifactsManagerOptions = {
  localEditorTemplateSource: string;
  localEditorDataTemplateSource: string;
  trackGeneratedFile: (filePath: string) => void;
};

/**
 * Creates the generation and cleanup lifecycle for local-editor shell and
 * data-template artifacts.
 */
export const createLocalEditorArtifactsManager = ({
  localEditorTemplateSource,
  localEditorDataTemplateSource,
  trackGeneratedFile,
}: CreateLocalEditorArtifactsManagerOptions) => {
  const syncLocalEditorTemplate = ({
    rootDir = process.cwd(),
    registryTemplateNames,
  }: {
    rootDir?: string;
    registryTemplateNames: string[];
  }) => {
    const templatePath = path.join(
      rootDir,
      "src",
      "templates",
      "local-editor.tsx"
    );
    let nextTemplateSource = localEditorTemplateSource;
    nextTemplateSource = buildEditorTemplateSource({
      rootDir,
      templatePath,
      templateSource: nextTemplateSource,
      templateNames: registryTemplateNames,
    });

    fs.mkdirSync(path.dirname(templatePath), { recursive: true });

    if (
      fs.existsSync(templatePath) &&
      !isGeneratedLocalEditorTemplate(templatePath)
    ) {
      throw new Error(
        `Refusing to overwrite hand-authored local editor template at ${templatePath}`
      );
    }

    writeFileIfChanged(templatePath, nextTemplateSource);
    trackGeneratedFile(templatePath);
  };

  const cleanupLocalEditorTemplate = (rootDir = process.cwd()) => {
    const templatePath = path.join(
      rootDir,
      "src",
      "templates",
      "local-editor.tsx"
    );
    if (isGeneratedLocalEditorTemplate(templatePath)) {
      fs.rmSync(templatePath, { force: true });
    }
  };

  const syncLocalEditorDataTemplates = async ({
    rootDir = process.cwd(),
  }: {
    rootDir?: string;
  } = {}) => {
    const manifest = await getLocalEditorManifest(rootDir);
    const activeTemplatePaths = new Set<string>();

    for (const templateId of manifest.templates) {
      const templatePath = path.join(
        rootDir,
        buildLocalEditorDataTemplatePath(templateId)
      );
      const streamConfigImportPath = path
        .relative(
          path.dirname(templatePath),
          toAbsoluteLocalEditorPath(
            rootDir,
            DEFAULT_LOCAL_EDITOR_STREAM_CONFIG_PATH
          )
        )
        .split(path.sep)
        .join("/");
      const nextTemplateSource = buildLocalEditorDataTemplateSource(
        localEditorDataTemplateSource,
        streamConfigImportPath.startsWith(".")
          ? streamConfigImportPath
          : `./${streamConfigImportPath}`,
        templateId
      );

      fs.mkdirSync(path.dirname(templatePath), { recursive: true });

      if (
        fs.existsSync(templatePath) &&
        !isGeneratedLocalEditorTemplate(templatePath)
      ) {
        throw new Error(
          `Refusing to overwrite hand-authored local editor data template at ${templatePath}`
        );
      }

      writeFileIfChanged(templatePath, nextTemplateSource);
      activeTemplatePaths.add(templatePath);
    }

    cleanupLocalEditorDataTemplates({
      rootDir,
      activeTemplatePaths,
    });
  };

  const cleanupLocalEditorDataTemplates = ({
    rootDir = process.cwd(),
    activeTemplatePaths,
  }: {
    rootDir?: string;
    activeTemplatePaths?: Set<string>;
  } = {}) => {
    // Only remove files we know were generated by the local-editor flow to
    // avoid clobbering hand-authored templates in consumer repos.
    const templatesDirectory = path.join(rootDir, "src", "templates");
    if (!fs.existsSync(templatesDirectory)) {
      return;
    }

    for (const entry of fs.readdirSync(templatesDirectory, {
      withFileTypes: true,
    })) {
      if (!entry.isFile()) {
        continue;
      }

      if (
        !entry.name.startsWith(LOCAL_EDITOR_DATA_TEMPLATE_PREFIX) ||
        path.extname(entry.name) !== ".tsx"
      ) {
        continue;
      }

      const templatePath = path.join(templatesDirectory, entry.name);
      if (
        activeTemplatePaths?.has(templatePath) ||
        !isGeneratedLocalEditorTemplate(templatePath)
      ) {
        continue;
      }

      fs.rmSync(templatePath, { force: true });
    }

    const legacyTemplatePath = path.join(
      rootDir,
      LEGACY_LOCAL_EDITOR_DATA_TEMPLATE_PATH
    );
    if (
      (!activeTemplatePaths || !activeTemplatePaths.has(legacyTemplatePath)) &&
      isGeneratedLocalEditorTemplate(legacyTemplatePath)
    ) {
      fs.rmSync(legacyTemplatePath, { force: true });
    }
  };

  const cleanupGeneratedLocalEditorArtifacts = (rootDir = process.cwd()) => {
    cleanupLocalEditorTemplate(rootDir);
    cleanupLocalEditorDataTemplates({ rootDir });
  };

  const cleanupServeArtifacts = (
    cleanupFiles: () => void,
    rootDir = process.cwd()
  ) => {
    cleanupGeneratedLocalEditorArtifacts(rootDir);
    cleanupFiles();
  };

  return {
    cleanupGeneratedLocalEditorArtifacts,
    cleanupServeArtifacts,
    syncLocalEditorDataTemplates,
    syncLocalEditorTemplate,
  };
};
