import os from "node:os";
import path from "node:path";
import fs from "fs-extra";
import { afterEach, describe, expect, it } from "vitest";
import type { SectionLibraryLayout } from "../../sectionLibrary.ts";
import { createLocalEditorArtifactsManager } from "./artifacts.ts";

const rootDirs: string[] = [];

afterEach(() => {
  while (rootDirs.length > 0) {
    fs.removeSync(rootDirs.pop()!);
  }
});

describe("createLocalEditorArtifactsManager", () => {
  it("creates a real-layout config registry and data templates for Entity layouts", () => {
    const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), "local-editor-"));
    rootDirs.push(rootDir);
    const artifacts = createLocalEditorArtifactsManager({
      localEditorTemplateSource: [
        "__LOCAL_EDITOR_STYLESHEET_HREFS__",
        "/* LOCAL_EDITOR_CONFIG_IMPORTS */",
        "/* LOCAL_EDITOR_COMPONENT_REGISTRY */",
      ].join("\n"),
      localEditorDataTemplateSource: [
        '"__LOCAL_EDITOR_STREAM_CONFIG_IMPORT__"',
        '"__LOCAL_EDITOR_TEMPLATE_ID__"',
        '"__LOCAL_EDITOR_PAGE_SET_TYPE__"',
        '"__LOCAL_EDITOR_DATA_TEMPLATE_NAME__"',
      ].join("\n"),
    });
    const layouts: SectionLibraryLayout[] = [
      {
        metadata: {
          id: "location-layout",
          displayName: "Location",
          pageSetType: "ENTITY",
          previewImageUrl: "",
        },
        defaultLayout: {},
      },
      {
        metadata: {
          id: "directory-layout",
          displayName: "Directory",
          pageSetType: "DIRECTORY",
        },
        defaultLayout: {},
      },
    ];

    artifacts.syncLocalEditorTemplate(layouts, rootDir);
    artifacts.syncLocalEditorDataTemplates(layouts, rootDir);

    expect(
      fs.readFileSync(
        path.join(rootDir, "src", "templates", "local-editor.tsx"),
        "utf8"
      )
    ).toContain("libraryConfig-location-layout");
    expect(
      fs.readFileSync(
        path.join(rootDir, "src", "templates", "local-editor.tsx"),
        "utf8"
      )
    ).toContain('"directory-layout": LayoutConfig1');
    expect(
      fs.existsSync(
        path.join(
          rootDir,
          "src",
          "templates",
          "local-editor-data-location-layout.tsx"
        )
      )
    ).toBe(true);
    expect(
      fs.existsSync(
        path.join(
          rootDir,
          "src",
          "templates",
          "local-editor-data-directory-layout.tsx"
        )
      )
    ).toBe(false);
  });

  it("does not overwrite a hand-authored local editor template", () => {
    const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), "local-editor-"));
    rootDirs.push(rootDir);
    fs.outputFileSync(
      path.join(rootDir, "src", "templates", "local-editor.tsx"),
      "export default null;"
    );
    const artifacts = createLocalEditorArtifactsManager({
      localEditorTemplateSource: "generated",
      localEditorDataTemplateSource: "generated",
    });

    expect(() => artifacts.syncLocalEditorTemplate([], rootDir)).toThrow(
      "Refusing to overwrite hand-authored local editor template"
    );
  });

  it("removes stale Directory and Locator data templates", () => {
    const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), "local-editor-"));
    rootDirs.push(rootDir);
    const artifacts = createLocalEditorArtifactsManager({
      localEditorTemplateSource:
        "/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */",
      localEditorDataTemplateSource:
        "/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */",
    });
    const staleTemplatePath = path.join(
      rootDir,
      "src",
      "templates",
      "local-editor-data-directory.tsx"
    );
    fs.outputFileSync(
      staleTemplatePath,
      "/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */"
    );

    artifacts.syncLocalEditorDataTemplates(
      [
        {
          metadata: {
            id: "directory",
            displayName: "Directory",
            pageSetType: "DIRECTORY",
          },
          defaultLayout: {},
        },
      ],
      rootDir
    );

    expect(fs.existsSync(staleTemplatePath)).toBe(false);
  });

  it("removes generated local editor templates", () => {
    const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), "local-editor-"));
    rootDirs.push(rootDir);
    const artifacts = createLocalEditorArtifactsManager({
      localEditorTemplateSource:
        "/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */",
      localEditorDataTemplateSource:
        "/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */",
    });

    artifacts.syncLocalEditorTemplate([], rootDir);
    artifacts.syncLocalEditorDataTemplates(
      [
        {
          metadata: {
            id: "location-layout",
            displayName: "Location",
            pageSetType: "ENTITY",
            previewImageUrl: "",
          },
          defaultLayout: {},
        },
      ],
      rootDir
    );
    artifacts.cleanupGeneratedLocalEditorArtifacts(rootDir);

    expect(
      fs.existsSync(path.join(rootDir, "src", "templates", "local-editor.tsx"))
    ).toBe(false);
    expect(
      fs.existsSync(
        path.join(
          rootDir,
          "src",
          "templates",
          "local-editor-data-location-layout.tsx"
        )
      )
    ).toBe(false);
  });
});
