import path from "node:path";
import fs from "fs-extra";
import { buildLocalEditorScaffoldSource } from "../localEditorScaffold.ts";

export const DEFAULT_LOCAL_EDITOR_ROUTE = "/local-editor";
export const DEFAULT_LOCAL_EDITOR_STREAM_CONFIG_PATH = "stream.config.ts";
export const LOCAL_EDITOR_API_BASE_PATH = "/__yext_visual_editor/local-editor";
export const LOCAL_EDITOR_DATA_TEMPLATE_PREFIX = "local-editor-data-";
export const LEGACY_LOCAL_EDITOR_DATA_TEMPLATE_PATH =
  "src/templates/local-editor-data.tsx";
export const GENERATED_LOCAL_EDITOR_TEMPLATE_PREFIX =
  "/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */";

/**
 * Builds the generated data-template name used for one local-editor template.
 */
export const buildLocalEditorDataTemplateName = (
  templateId: string
): string => {
  const normalizedTemplateSegment = templateId
    .trim()
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  return `${LOCAL_EDITOR_DATA_TEMPLATE_PREFIX}${normalizedTemplateSegment || "template"}`;
};

/**
 * Returns the generated `src/templates/*.tsx` path for one local-editor data
 * template.
 */
export const buildLocalEditorDataTemplatePath = (
  templateId: string
): string => {
  return path.join(
    "src",
    "templates",
    `${buildLocalEditorDataTemplateName(templateId)}.tsx`
  );
};

/**
 * Resolves a local-editor file path against the consumer root when needed.
 */
export const toAbsoluteLocalEditorPath = (
  rootDir: string,
  filePath: string
): string => {
  return path.isAbsolute(filePath) ? filePath : path.join(rootDir, filePath);
};

/**
 * Injects template-specific placeholders into generated local-editor data
 * template source.
 */
export const buildLocalEditorDataTemplateSource = (
  templateSource: string,
  streamConfigImportPath: string,
  templateId: string
): string => {
  return templateSource
    .replaceAll(
      '"__LOCAL_EDITOR_STREAM_CONFIG_IMPORT__"',
      JSON.stringify(streamConfigImportPath)
    )
    .replaceAll('"__LOCAL_EDITOR_TEMPLATE_ID__"', JSON.stringify(templateId))
    .replaceAll(
      '"__LOCAL_EDITOR_DATA_TEMPLATE_NAME__"',
      JSON.stringify(buildLocalEditorDataTemplateName(templateId))
    );
};

/**
 * Returns whether a template file was generated by the local-editor flow.
 */
export const isGeneratedLocalEditorTemplate = (
  templatePath: string
): boolean => {
  if (!fs.existsSync(templatePath)) {
    return false;
  }

  const fileContents = fs.readFileSync(templatePath, "utf8");
  return fileContents.startsWith(GENERATED_LOCAL_EDITOR_TEMPLATE_PREFIX);
};

/**
 * Ensures the root `stream.config.ts` file exists by scaffolding it on demand.
 */
export const ensureLocalEditorStreamConfig = async (
  rootDir: string
): Promise<void> => {
  const absoluteStreamConfigPath = toAbsoluteLocalEditorPath(
    rootDir,
    DEFAULT_LOCAL_EDITOR_STREAM_CONFIG_PATH
  );
  if (fs.existsSync(absoluteStreamConfigPath)) {
    return;
  }

  fs.ensureDirSync(path.dirname(absoluteStreamConfigPath));
  fs.writeFileSync(
    absoluteStreamConfigPath,
    buildLocalEditorScaffoldSource(rootDir)
  );
};
