import path from "node:path";
import fs from "fs-extra";
import type { PageSetType } from "../../sectionLibrary.ts";

export const DEFAULT_LOCAL_EDITOR_ROUTE = "/local-editor";
export const DEFAULT_LOCAL_EDITOR_STREAM_CONFIG_PATH = "stream.config.ts";
export const LOCAL_EDITOR_API_BASE_PATH = "/__yext_visual_editor/local-editor";
export const LOCAL_EDITOR_DATA_TEMPLATE_PREFIX = "local-editor-data-";
export const LEGACY_LOCAL_EDITOR_DATA_TEMPLATE_PATH =
  "src/templates/local-editor-data.tsx";
export const GENERATED_LOCAL_EDITOR_TEMPLATE_PREFIX =
  "/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */";

/**
 * Builds the generated data-template name used for one local-editor template.
 */
export const buildLocalEditorDataTemplateName = (layoutId: string): string => {
  const normalizedLayoutSegment = layoutId
    .trim()
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  return `${LOCAL_EDITOR_DATA_TEMPLATE_PREFIX}${normalizedLayoutSegment || "layout"}`;
};

/**
 * Returns the generated `src/templates/*.tsx` path for one local-editor data
 * template.
 */
export const buildLocalEditorDataTemplatePath = (layoutId: string): string => {
  return path.join(
    "src",
    "templates",
    `${buildLocalEditorDataTemplateName(layoutId)}.tsx`
  );
};

/**
 * Resolves a local-editor file path against the consumer root when needed.
 */
export const toAbsoluteLocalEditorPath = (
  rootDir: string,
  filePath: string
): string => {
  return path.isAbsolute(filePath) ? filePath : path.join(rootDir, filePath);
};

/**
 * Creates the default Local Editor stream configuration when a starter does
 * not provide one. The starter owns the generated file after this write.
 */
export const ensureLocalEditorStreamConfig = (rootDir: string): void => {
  const streamConfigPath = toAbsoluteLocalEditorPath(
    rootDir,
    DEFAULT_LOCAL_EDITOR_STREAM_CONFIG_PATH
  );
  if (fs.existsSync(streamConfigPath)) {
    return;
  }

  fs.writeFileSync(
    streamConfigPath,
    `import type { LocalEditorConfig } from "@yext/visual-editor/plugin";

const config = {
  defaults: {
    locale: "en",
  },
  pageSetTypes: {
    ENTITY: {
      stream: {
        $id: "local-editor-entity-stream",
        filter: { entityTypes: ["location"] },
        fields: [
          "id",
          "name",
          "slug",
          "address",
          "description",
          "emails",
          "hours",
          "mainPhone",
          "services",
          "yextDisplayCoordinate",
        ],
        localization: { locales: ["en"] },
      },
    },
  },
} satisfies LocalEditorConfig;

export default config;
`
  );
};

/**
 * Injects template-specific placeholders into generated local-editor data
 * template source.
 */
export const buildLocalEditorDataTemplateSource = (
  templateSource: string,
  streamConfigImportPath: string,
  layoutId: string,
  pageSetType: PageSetType
): string => {
  return templateSource
    .replaceAll(
      '"__LOCAL_EDITOR_STREAM_CONFIG_IMPORT__"',
      JSON.stringify(streamConfigImportPath)
    )
    .replaceAll('"__LOCAL_EDITOR_TEMPLATE_ID__"', JSON.stringify(layoutId))
    .replaceAll('"__LOCAL_EDITOR_PAGE_SET_TYPE__"', JSON.stringify(pageSetType))
    .replaceAll(
      '"__LOCAL_EDITOR_DATA_TEMPLATE_NAME__"',
      JSON.stringify(buildLocalEditorDataTemplateName(layoutId))
    );
};

/**
 * Returns whether a template file was generated by the local-editor flow.
 */
export const isGeneratedLocalEditorTemplate = (
  templatePath: string
): boolean => {
  if (!fs.existsSync(templatePath)) {
    return false;
  }

  const fileContents = fs.readFileSync(templatePath, "utf8");
  return fileContents.startsWith(GENERATED_LOCAL_EDITOR_TEMPLATE_PREFIX);
};
