import path from "node:path";
import fs from "fs-extra";
import { buildLocalEditorScaffoldSource } from "../localEditorScaffold.ts";
import type {
  LocalEditorPagesStream,
  LocalEditorStreamDefinition,
} from "./types.ts";

export const DEFAULT_LOCAL_EDITOR_ROUTE = "/local-editor";
export const DEFAULT_LOCAL_EDITOR_STREAM_CONFIG_PATH = "stream.config.ts";
export const LOCAL_EDITOR_API_BASE_PATH = "/__yext_visual_editor/local-editor";
export const LOCAL_EDITOR_DATA_TEMPLATE_PREFIX = "local-editor-data-";
export const LEGACY_LOCAL_EDITOR_DATA_TEMPLATE_PATH =
  "src/templates/local-editor-data.tsx";
export const GENERATED_LOCAL_EDITOR_TEMPLATE_PREFIX =
  "/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */";

export const normalizeLocalEditorRoute = (route?: string): string => {
  if (!route) {
    return DEFAULT_LOCAL_EDITOR_ROUTE;
  }

  const trimmedRoute = route.trim();
  if (!trimmedRoute) {
    return DEFAULT_LOCAL_EDITOR_ROUTE;
  }

  const normalizedRoute = `/${trimmedRoute.replace(/^\/+/, "").replace(/\/+$/, "")}`;
  return normalizedRoute === "/" ? DEFAULT_LOCAL_EDITOR_ROUTE : normalizedRoute;
};

export const toTemplatePathSegment = (route: string): string => {
  return normalizeLocalEditorRoute(route).replace(/^\/+/, "");
};

export const buildLocalEditorDataTemplateName = (
  templateId: string
): string => {
  const normalizedTemplateSegment = templateId
    .trim()
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  return `${LOCAL_EDITOR_DATA_TEMPLATE_PREFIX}${normalizedTemplateSegment || "template"}`;
};

export const buildLocalEditorDataTemplatePath = (
  templateId: string
): string => {
  return path.join(
    "src",
    "templates",
    `${buildLocalEditorDataTemplateName(templateId)}.tsx`
  );
};

export const toAbsoluteLocalEditorPath = (
  rootDir: string,
  filePath: string
): string => {
  return path.isAbsolute(filePath) ? filePath : path.join(rootDir, filePath);
};

export const buildLocalEditorTemplateSource = (
  templateSource: string,
  route: string
): string => {
  return templateSource.replaceAll(
    '"__LOCAL_EDITOR_ROUTE__"',
    JSON.stringify(toTemplatePathSegment(route))
  );
};

export const buildLocalEditorDataTemplateSource = (
  templateSource: string,
  streamConfigImportPath: string,
  templateId: string
): string => {
  return templateSource
    .replaceAll(
      '"__LOCAL_EDITOR_STREAM_CONFIG_IMPORT__"',
      JSON.stringify(streamConfigImportPath)
    )
    .replaceAll('"__LOCAL_EDITOR_TEMPLATE_ID__"', JSON.stringify(templateId))
    .replaceAll(
      '"__LOCAL_EDITOR_DATA_TEMPLATE_NAME__"',
      JSON.stringify(buildLocalEditorDataTemplateName(templateId))
    );
};

export const normalizeLocalEditorPagesStream = (
  stream?: LocalEditorStreamDefinition
): LocalEditorPagesStream | undefined => {
  if (!stream) {
    return undefined;
  }

  const normalizedFields = (stream.fields ?? [])
    .map((field) => {
      return typeof field === "string" ? field : field.name;
    })
    .filter((fieldName): fieldName is string => {
      return !!fieldName && fieldName !== "locale";
    })
    .filter((fieldName, index, values) => {
      return values.indexOf(fieldName) === index;
    });

  return {
    ...stream,
    fields: normalizedFields,
  };
};

export const isGeneratedLocalEditorTemplate = (
  templatePath: string
): boolean => {
  if (!fs.existsSync(templatePath)) {
    return false;
  }

  const fileContents = fs.readFileSync(templatePath, "utf8");
  return fileContents.startsWith(GENERATED_LOCAL_EDITOR_TEMPLATE_PREFIX);
};

export const ensureLocalEditorStreamConfig = async (
  rootDir: string,
  streamConfigPath: string
): Promise<void> => {
  const absoluteStreamConfigPath = toAbsoluteLocalEditorPath(
    rootDir,
    streamConfigPath
  );
  if (fs.existsSync(absoluteStreamConfigPath)) {
    return;
  }

  if (streamConfigPath !== DEFAULT_LOCAL_EDITOR_STREAM_CONFIG_PATH) {
    return;
  }

  fs.ensureDirSync(path.dirname(absoluteStreamConfigPath));
  fs.writeFileSync(
    absoluteStreamConfigPath,
    buildLocalEditorScaffoldSource(rootDir)
  );
};
