import * as React from "react";
import {
  FaPhone,
  FaEnvelope,
  FaMapMarkerAlt,
  FaCalendar,
  FaStar,
  FaHeart,
  FaShare,
  FaDownload,
  FaPlay,
  FaPause,
  FaStepForward,
  FaStepBackward,
  FaBars,
  FaSearch,
  FaTimes,
  FaCheck,
  FaPlus,
  FaMinus,
  FaArrowRight,
  FaArrowLeft,
  FaArrowUp,
  FaArrowDown,
} from "react-icons/fa";
import { PresetImageType } from "../types/types";

// Preset image icons mapping using react-icons
export const presetImageIcons: Record<PresetImageType, React.ReactNode> = {
  phone: <FaPhone size={16} />,
  email: <FaEnvelope size={16} />,
  location: <FaMapMarkerAlt size={16} />,
  calendar: <FaCalendar size={16} />,
  star: <FaStar size={16} />,
  heart: <FaHeart size={16} />,
  share: <FaShare size={16} />,
  download: <FaDownload size={16} />,
  play: <FaPlay size={16} />,
  pause: <FaPause size={16} />,
  next: <FaStepForward size={16} />,
  previous: <FaStepBackward size={16} />,
  menu: <FaBars size={16} />,
  search: <FaSearch size={16} />,
  close: <FaTimes size={16} />,
  check: <FaCheck size={16} />,
  plus: <FaPlus size={16} />,
  minus: <FaMinus size={16} />,
  "arrow-right": <FaArrowRight size={16} />,
  "arrow-left": <FaArrowLeft size={16} />,
  "arrow-up": <FaArrowUp size={16} />,
  "arrow-down": <FaArrowDown size={16} />,
};
