import { PUCK_PREVIEW_IFRAME_ID, THEME_STYLE_TAG_ID } from "./applyTheme.ts";
import { StyleSelectOption } from "./themeResolver.ts";

export type FontRegistry = Record<string, FontSpecification>;
type FontSpecification = {
  minWeight: number; // minimum weight the font supports
  maxWeight: number; // maximum weight the font supports
  italics: boolean; // whether the font supports italics
  fallback: "sans-serif" | "serif" | "monospace" | "cursive";
};

// List of variable Google Fonts https://fonts.google.com/?categoryFilters=Technology:%2FTechnology%2FVariable
// prettier-ignore
export const defaultFonts: FontRegistry = {
  "42dot Sans": { italics: false, minWeight: 300, maxWeight: 800, fallback: "sans-serif" },
  ABeeZee: { italics: true, minWeight: 400, maxWeight: 400, fallback: "sans-serif" },
  "AR One Sans": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Abhaya Libre": { italics: false, minWeight: 400, maxWeight: 800, fallback: "serif" },
  "Advent Pro": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Afacad: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Afacad Flux": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Agdasima: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Akatab: { italics: false, minWeight: 400, maxWeight: 900, fallback: "sans-serif" },
  Akshar: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Albert Sans": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Alef: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Alegreya: { italics: true, minWeight: 400, maxWeight: 900, fallback: "serif" },
  "Alegreya SC": { italics: true, minWeight: 400, maxWeight: 900, fallback: "serif" },
  "Alegreya Sans": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Alegreya Sans SC": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Aleo: { italics: true, minWeight: 100, maxWeight: 900, fallback: "serif" },
  Alexandria: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Alkatra: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Allan: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Almarai: { italics: false, minWeight: 300, maxWeight: 800, fallback: "sans-serif" },
  Almendra: { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Alumni Sans": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Alumni Sans Collegiate One": { italics: true, minWeight: 400, maxWeight: 400, fallback: "sans-serif" },
  "Alumni Sans Inline One": { italics: true, minWeight: 400, maxWeight: 400, fallback: "sans-serif" },
  "Alumni Sans Pinstripe": { italics: true, minWeight: 400, maxWeight: 400, fallback: "sans-serif" },
  Amaranth: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Amatic SC": { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  Amiko: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Amiri: { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Amita: { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  Anaheim: { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Ancizar Sans": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Ancizar Serif": { italics: true, minWeight: 300, maxWeight: 900, fallback: "serif" },
  "Andada Pro": { italics: true, minWeight: 400, maxWeight: 800, fallback: "serif" },
  Andika: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Anek Bangla": { italics: false, minWeight: 100, maxWeight: 800, fallback: "sans-serif" },
  "Anek Devanagari": { italics: false, minWeight: 100, maxWeight: 800, fallback: "sans-serif" },
  "Anek Gujarati": { italics: false, minWeight: 100, maxWeight: 800, fallback: "sans-serif" },
  "Anek Gurmukhi": { italics: false, minWeight: 100, maxWeight: 800, fallback: "sans-serif" },
  "Anek Kannada": { italics: false, minWeight: 100, maxWeight: 800, fallback: "sans-serif" },
  "Anek Latin": { italics: false, minWeight: 100, maxWeight: 800, fallback: "sans-serif" },
  "Anek Malayalam": { italics: false, minWeight: 100, maxWeight: 800, fallback: "sans-serif" },
  "Anek Odia": { italics: false, minWeight: 100, maxWeight: 800, fallback: "sans-serif" },
  "Anek Tamil": { italics: false, minWeight: 100, maxWeight: 800, fallback: "sans-serif" },
  "Anek Telugu": { italics: false, minWeight: 100, maxWeight: 800, fallback: "sans-serif" },
  "Annapurna SIL": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Anonymous Pro": { italics: true, minWeight: 400, maxWeight: 700, fallback: "monospace" },
  Antonio: { italics: false, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  Anuphan: { italics: false, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  Anybody: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Arapey: { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  Archivo: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Archivo Narrow": { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Aref Ruqaa": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Aref Ruqaa Ink": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Arima: { italics: false, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  Arimo: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Arsenal: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Arsenal SC": { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Arvo: { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Arya: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Asap: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Asap Condensed": { italics: true, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  Assistant: { italics: false, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  Astloch: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Asul: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Athiti: { italics: false, minWeight: 200, maxWeight: 700, fallback: "sans-serif" },
  "Atkinson Hyperlegible": { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Atkinson Hyperlegible Mono": { italics: true, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  "Atkinson Hyperlegible Next": { italics: true, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  Atma: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Averia Libre": { italics: true, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Averia Sans Libre": { italics: true, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Averia Serif Libre": { italics: true, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Azeret Mono": { italics: true, minWeight: 100, maxWeight: 900, fallback: "monospace" },
  B612: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "B612 Mono": { italics: true, minWeight: 400, maxWeight: 700, fallback: "monospace" },
  "BIZ UDGothic": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "BIZ UDMincho": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "BIZ UDPGothic": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "BIZ UDPMincho": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Bai Jamjuree": { italics: true, minWeight: 200, maxWeight: 700, fallback: "sans-serif" },
  "Baloo 2": { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Baloo Bhai 2": { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Baloo Bhaijaan 2": { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Baloo Bhaina 2": { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Baloo Chettan 2": { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Baloo Da 2": { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Baloo Paaji 2": { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Baloo Tamma 2": { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Baloo Tammudu 2": { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Baloo Thambi 2": { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Balsamiq Sans": { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Barlow: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Barlow Condensed": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Barlow Semi Condensed": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Baskervville: { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  Battambang: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Be Vietnam Pro": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Beiruti: { italics: false, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  Belanosima: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Bellota: { italics: true, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Bellota Text": { italics: true, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  BenchNine: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Besley: { italics: true, minWeight: 400, maxWeight: 900, fallback: "serif" },
  Bevan: { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "Big Shoulders": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Big Shoulders Inline": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Big Shoulders Stencil": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  BioRhyme: { italics: false, minWeight: 200, maxWeight: 800, fallback: "serif" },
  "BioRhyme Expanded": { italics: false, minWeight: 200, maxWeight: 800, fallback: "serif" },
  "Birthstone Bounce": { italics: false, minWeight: 400, maxWeight: 500, fallback: "cursive" },
  Biryani: { italics: false, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  Bitter: { italics: true, minWeight: 100, maxWeight: 900, fallback: "serif" },
  Blinker: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Bodoni Moda": { italics: true, minWeight: 400, maxWeight: 900, fallback: "serif" },
  "Bodoni Moda SC": { italics: true, minWeight: 400, maxWeight: 900, fallback: "serif" },
  "Bona Nova": { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Bona Nova SC": { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Brawler: { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Bricolage Grotesque": { italics: false, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  "Brygada 1918": { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Buda: { italics: false, minWeight: 300, maxWeight: 300, fallback: "sans-serif" },
  Buenard: { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Cabin: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Cabin Condensed": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Cabin Sketch": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Cairo: { italics: false, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  "Cairo Play": { italics: false, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  Caladea: { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Cambay: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Cantarell: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Cardo: { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Carlito: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Cascadia Code": { italics: true, minWeight: 200, maxWeight: 700, fallback: "sans-serif" },
  "Cascadia Mono": { italics: true, minWeight: 200, maxWeight: 700, fallback: "sans-serif" },
  Castoro: { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  Catamaran: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Caudex: { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Caveat: { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  "Chakra Petch": { italics: true, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Changa: { italics: false, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  "Changa One": { italics: true, minWeight: 400, maxWeight: 400, fallback: "sans-serif" },
  "Charis SIL": { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Charm: { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  Charmonman: { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  Chathura: { italics: false, minWeight: 100, maxWeight: 800, fallback: "sans-serif" },
  "Chau Philomene One": { italics: true, minWeight: 400, maxWeight: 400, fallback: "sans-serif" },
  "Cherry Swash": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Chivo: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Chivo Mono": { italics: true, minWeight: 100, maxWeight: 900, fallback: "monospace" },
  Cinzel: { italics: false, minWeight: 400, maxWeight: 900, fallback: "serif" },
  "Cinzel Decorative": { italics: false, minWeight: 400, maxWeight: 900, fallback: "sans-serif" },
  Coda: { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  Codystar: { italics: false, minWeight: 300, maxWeight: 400, fallback: "sans-serif" },
  Comfortaa: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Comic Neue": { italics: true, minWeight: 300, maxWeight: 700, fallback: "cursive" },
  "Comic Relief": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Comme: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Commissioner: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Corben: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Corinthia: { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  Cormorant: { italics: true, minWeight: 300, maxWeight: 700, fallback: "serif" },
  "Cormorant Garamond": { italics: true, minWeight: 300, maxWeight: 700, fallback: "serif" },
  "Cormorant Infant": { italics: true, minWeight: 300, maxWeight: 700, fallback: "serif" },
  "Cormorant SC": { italics: false, minWeight: 300, maxWeight: 700, fallback: "serif" },
  "Cormorant Unicase": { italics: false, minWeight: 300, maxWeight: 700, fallback: "serif" },
  "Cormorant Upright": { italics: false, minWeight: 300, maxWeight: 700, fallback: "serif" },
  "Courier Prime": { italics: true, minWeight: 400, maxWeight: 700, fallback: "monospace" },
  Cousine: { italics: true, minWeight: 400, maxWeight: 700, fallback: "monospace" },
  Coustard: { italics: false, minWeight: 400, maxWeight: 900, fallback: "serif" },
  "Crete Round": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "Crimson Pro": { italics: true, minWeight: 200, maxWeight: 900, fallback: "serif" },
  "Crimson Text": { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Cuprum: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "DM Mono": { italics: true, minWeight: 300, maxWeight: 500, fallback: "monospace" },
  "DM Sans": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "DM Serif Display": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "DM Serif Text": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "Dai Banna SIL": { italics: true, minWeight: 300, maxWeight: 700, fallback: "serif" },
  "Dancing Script": { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  "Darker Grotesque": { italics: false, minWeight: 300, maxWeight: 900, fallback: "sans-serif" },
  "David Libre": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Delius Unicase": { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  Domine: { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Dongle: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Dosis: { italics: false, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  Doto: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  DynaPuff: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "EB Garamond": { italics: true, minWeight: 400, maxWeight: 800, fallback: "serif" },
  Economica: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Eczar: { italics: false, minWeight: 400, maxWeight: 800, fallback: "serif" },
  "Edu AU VIC WA NT Arrows": { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  "Edu AU VIC WA NT Dots": { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  "Edu AU VIC WA NT Guides": { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  "Edu AU VIC WA NT Hand": { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  "Edu AU VIC WA NT Pre": { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  "Edu NSW ACT Foundation": { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  "Edu QLD Beginner": { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  "Edu SA Beginner": { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  "Edu TAS Beginner": { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  "Edu VIC WA NT Beginner": { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  "El Messiri": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Elsie: { italics: false, minWeight: 400, maxWeight: 900, fallback: "sans-serif" },
  "Elsie Swash Caps": { italics: false, minWeight: 400, maxWeight: 900, fallback: "sans-serif" },
  "Encode Sans": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Encode Sans Condensed": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Encode Sans Expanded": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Encode Sans SC": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Encode Sans Semi Condensed": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Encode Sans Semi Expanded": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Enriqueta: { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Epilogue: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Exo: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Exo 2": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Expletus Sans": { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Fahkwang: { italics: true, minWeight: 200, maxWeight: 700, fallback: "sans-serif" },
  "Familjen Grotesk": { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Fanwood Text": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  Farro: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Faustina: { italics: true, minWeight: 300, maxWeight: 800, fallback: "serif" },
  Figtree: { italics: true, minWeight: 300, maxWeight: 900, fallback: "sans-serif" },
  Finlandica: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Fira Code": { italics: false, minWeight: 300, maxWeight: 700, fallback: "monospace" },
  "Fira Mono": { italics: false, minWeight: 400, maxWeight: 700, fallback: "monospace" },
  "Fira Sans": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Fira Sans Condensed": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Fira Sans Extra Condensed": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Flamenco: { italics: false, minWeight: 300, maxWeight: 400, fallback: "sans-serif" },
  Foldit: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Fondamento: { italics: true, minWeight: 400, maxWeight: 400, fallback: "cursive" },
  "Fragment Mono": { italics: true, minWeight: 400, maxWeight: 400, fallback: "monospace" },
  "Frank Ruhl Libre": { italics: false, minWeight: 300, maxWeight: 900, fallback: "serif" },
  Fraunces: { italics: true, minWeight: 100, maxWeight: 900, fallback: "serif" },
  Fredoka: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Fruktur: { italics: true, minWeight: 400, maxWeight: 400, fallback: "sans-serif" },
  "Funnel Display": { italics: false, minWeight: 300, maxWeight: 800, fallback: "sans-serif" },
  "Funnel Sans": { italics: true, minWeight: 300, maxWeight: 800, fallback: "sans-serif" },
  Fustat: { italics: false, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  "Fuzzy Bubbles": { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  "GFS Neohellenic": { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Gabarito: { italics: false, minWeight: 400, maxWeight: 900, fallback: "sans-serif" },
  Gaegu: { italics: false, minWeight: 300, maxWeight: 700, fallback: "cursive" },
  Gantari: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Gayathri: { italics: false, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  Geist: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Geist Mono": { italics: false, minWeight: 100, maxWeight: 900, fallback: "monospace" },
  Gelasio: { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Gemunu Libre": { italics: false, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  Genos: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Gentium Book Plus": { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Gentium Plus": { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Geo: { italics: true, minWeight: 400, maxWeight: 400, fallback: "sans-serif" },
  Geologica: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Georama: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Glegoo: { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Glory: { italics: true, minWeight: 100, maxWeight: 800, fallback: "sans-serif" },
  Gluten: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Goldman: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Golos Text": { italics: false, minWeight: 400, maxWeight: 900, fallback: "sans-serif" },
  Gorditas: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Gothic A1": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Gowun Batang": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Grandstander: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Grenze: { italics: true, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Grenze Gotisch": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Gudea: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Gupter: { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Gwendolyn: { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  Hahmlet: { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  Halant: { italics: false, minWeight: 300, maxWeight: 700, fallback: "serif" },
  Handjet: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Hanken Grotesk": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Hanuman: { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  Harmattan: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Heebo: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Hepta Slab": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  Hind: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Hind Guntur": { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Hind Madurai": { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Hind Mysuru": { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Hind Siliguri": { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Hind Vadodara": { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Host Grotesk": { italics: true, minWeight: 300, maxWeight: 800, fallback: "sans-serif" },
  "Hubot Sans": { italics: true, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  "IBM Plex Mono": { italics: true, minWeight: 100, maxWeight: 700, fallback: "monospace" },
  "IBM Plex Sans": { italics: true, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  "IBM Plex Sans Arabic": { italics: false, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  "IBM Plex Sans Condensed": { italics: true, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  "IBM Plex Sans Devanagari": { italics: false, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  "IBM Plex Sans Hebrew": { italics: false, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  "IBM Plex Sans JP": { italics: false, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  "IBM Plex Sans KR": { italics: false, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  "IBM Plex Sans Thai": { italics: false, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  "IBM Plex Sans Thai Looped": { italics: false, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  "IBM Plex Serif": { italics: true, minWeight: 100, maxWeight: 700, fallback: "serif" },
  "IM Fell DW Pica": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "IM Fell Double Pica": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "IM Fell English": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "IM Fell French Canon": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "IM Fell Great Primer": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "Ibarra Real Nova": { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Imbue: { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Inclusive Sans": { italics: true, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Inconsolata: { italics: false, minWeight: 200, maxWeight: 900, fallback: "monospace" },
  Inika: { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Inknut Antiqua": { italics: false, minWeight: 300, maxWeight: 900, fallback: "serif" },
  "Inria Sans": { italics: true, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Inria Serif": { italics: true, minWeight: 300, maxWeight: 700, fallback: "serif" },
  "Instrument Sans": { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Instrument Serif": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  Inter: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Inter Tight": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Istok Web": { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Jaldi: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "JetBrains Mono": { italics: true, minWeight: 100, maxWeight: 800, fallback: "monospace" },
  "Josefin Sans": { italics: true, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  "Josefin Slab": { italics: true, minWeight: 100, maxWeight: 700, fallback: "serif" },
  Jost: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Judson: { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Jura: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  K2D: { italics: true, minWeight: 100, maxWeight: 800, fallback: "sans-serif" },
  Kadwa: { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Kaisei Decol": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Kaisei HarunoUmi": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Kaisei Opti": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Kaisei Tokumin": { italics: false, minWeight: 400, maxWeight: 800, fallback: "serif" },
  Kalam: { italics: false, minWeight: 300, maxWeight: 700, fallback: "cursive" },
  Kalnia: { italics: false, minWeight: 100, maxWeight: 700, fallback: "serif" },
  "Kalnia Glaze": { italics: false, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  Kameron: { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Kanchenjunga: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Kanit: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Kantumruy Pro": { italics: true, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  Karantina: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Karla: { italics: true, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  Karma: { italics: false, minWeight: 300, maxWeight: 700, fallback: "serif" },
  "Kay Pho Du": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Khand: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Khula: { italics: false, minWeight: 300, maxWeight: 800, fallback: "sans-serif" },
  "Kiwi Maru": { italics: false, minWeight: 300, maxWeight: 500, fallback: "serif" },
  "Klee One": { italics: false, minWeight: 400, maxWeight: 600, fallback: "cursive" },
  KoHo: { italics: true, minWeight: 200, maxWeight: 700, fallback: "sans-serif" },
  Kodchasan: { italics: true, minWeight: 200, maxWeight: 700, fallback: "sans-serif" },
  "Kode Mono": { italics: false, minWeight: 400, maxWeight: 700, fallback: "monospace" },
  "Koh Santepheap": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  Kreon: { italics: false, minWeight: 300, maxWeight: 700, fallback: "serif" },
  Krub: { italics: true, minWeight: 200, maxWeight: 700, fallback: "sans-serif" },
  Kufam: { italics: true, minWeight: 400, maxWeight: 900, fallback: "sans-serif" },
  "Kulim Park": { italics: true, minWeight: 200, maxWeight: 700, fallback: "sans-serif" },
  "Kumbh Sans": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "LXGW WenKai Mono TC": { italics: false, minWeight: 300, maxWeight: 700, fallback: "monospace" },
  "LXGW WenKai TC": { italics: false, minWeight: 300, maxWeight: 700, fallback: "cursive" },
  Labrada: { italics: true, minWeight: 100, maxWeight: 900, fallback: "serif" },
  Laila: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Lateef: { italics: false, minWeight: 200, maxWeight: 800, fallback: "serif" },
  Lato: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "League Spartan": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Lekton: { italics: true, minWeight: 400, maxWeight: 700, fallback: "monospace" },
  Lemonada: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Lexend: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Lexend Deca": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Lexend Exa": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Lexend Giga": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Lexend Mega": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Lexend Peta": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Lexend Tera": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Lexend Zetta": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Libre Baskerville": { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Libre Bodoni": { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Libre Caslon Text": { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Libre Franklin": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Life Savers": { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Linden Hill": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  Linefont: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Lisu Bosa": { italics: true, minWeight: 200, maxWeight: 900, fallback: "serif" },
  Literata: { italics: true, minWeight: 200, maxWeight: 900, fallback: "serif" },
  Livvic: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Lobster Two": { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Londrina Solid": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Lora: { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Lunasima: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Lusitana: { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "M PLUS 1": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "M PLUS 1 Code": { italics: false, minWeight: 100, maxWeight: 700, fallback: "monospace" },
  "M PLUS 1p": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "M PLUS 2": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "M PLUS Code Latin": { italics: false, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  "M PLUS Rounded 1c": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Mada: { italics: false, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  Magra: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Maitree: { italics: false, minWeight: 200, maxWeight: 700, fallback: "serif" },
  Mali: { italics: true, minWeight: 200, maxWeight: 700, fallback: "cursive" },
  Manjari: { italics: false, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  Manrope: { italics: false, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  Manuale: { italics: true, minWeight: 300, maxWeight: 800, fallback: "serif" },
  Marhey: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Markazi Text": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Martel: { italics: false, minWeight: 200, maxWeight: 900, fallback: "serif" },
  "Martel Sans": { italics: false, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  "Martian Mono": { italics: false, minWeight: 100, maxWeight: 800, fallback: "monospace" },
  Marvel: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Mate: { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "Material Symbols": { italics: false, minWeight: 100, maxWeight: 700, fallback: "monospace" },
  "Maven Pro": { italics: false, minWeight: 400, maxWeight: 900, fallback: "sans-serif" },
  Merienda: { italics: false, minWeight: 300, maxWeight: 900, fallback: "cursive" },
  Merriweather: { italics: true, minWeight: 300, maxWeight: 900, fallback: "serif" },
  "Merriweather Sans": { italics: true, minWeight: 300, maxWeight: 800, fallback: "sans-serif" },
  Mina: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Miriam Libre": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Mirza: { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Mitr: { italics: false, minWeight: 200, maxWeight: 700, fallback: "sans-serif" },
  Moderustic: { italics: false, minWeight: 300, maxWeight: 800, fallback: "sans-serif" },
  Mohave: { italics: true, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Molle: { italics: true, minWeight: 400, maxWeight: 400, fallback: "cursive" },
  "Mona Sans": { italics: true, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  Monda: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Montagu Slab": { italics: false, minWeight: 100, maxWeight: 700, fallback: "serif" },
  Montserrat: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Montserrat Alternates": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Montserrat Underline": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Mountains of Christmas": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Mukta: { italics: false, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  "Mukta Mahee": { italics: false, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  "Mukta Malar": { italics: false, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  "Mukta Vaani": { italics: false, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  Mulish: { italics: true, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  Murecho: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  MuseoModerno: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Namdhinggo: { italics: false, minWeight: 400, maxWeight: 800, fallback: "serif" },
  "Nanum Gothic": { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Nanum Gothic Coding": { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  "Nanum Myeongjo": { italics: false, minWeight: 400, maxWeight: 800, fallback: "serif" },
  Narnoor: { italics: false, minWeight: 400, maxWeight: 800, fallback: "serif" },
  "National Park": { italics: false, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  Neuton: { italics: true, minWeight: 200, maxWeight: 800, fallback: "serif" },
  "News Cycle": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Newsreader: { italics: true, minWeight: 200, maxWeight: 800, fallback: "serif" },
  Niramit: { italics: true, minWeight: 200, maxWeight: 700, fallback: "sans-serif" },
  Nobile: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Nokora: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noticia Text": { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Noto Kufi Arabic": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Naskh Arabic": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Noto Nastaliq Urdu": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Noto Rashi Hebrew": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Sans": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Adlam": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Adlam Unjoined": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Arabic": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Armenian": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Balinese": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Bamum": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Bassa Vah": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Bengali": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Canadian Aboriginal": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Cham": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Cherokee": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Devanagari": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Display": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Duployan": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Ethiopic": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Georgian": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Gujarati": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Gunjala Gondi": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Gurmukhi": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans HK": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Hanifi Rohingya": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Hebrew": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans JP": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Javanese": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans KR": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Kannada": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Kawi": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Kayah Li": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Khmer": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Lao": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Lao Looped": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Lisu": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Malayalam": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Medefaidrin": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Meetei Mayek": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Mono": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans NKo Unjoined": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Nag Mundari": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans New Tai Lue": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Ol Chiki": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Oriya": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans SC": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Sinhala": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Sora Sompeng": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Sundanese": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Symbols": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Syriac": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Syriac Eastern": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans TC": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Tai Tham": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Tamil": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Tangsa": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Sans Telugu": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Thaana": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Thai": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Thai Looped": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Noto Sans Vithkuqi": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Noto Serif": { italics: true, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif Armenian": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif Bengali": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif Devanagari": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif Display": { italics: true, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif Ethiopic": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif Georgian": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif Gujarati": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif Gurmukhi": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif HK": { italics: false, minWeight: 200, maxWeight: 900, fallback: "serif" },
  "Noto Serif Hebrew": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif Hentaigana": { italics: false, minWeight: 200, maxWeight: 900, fallback: "serif" },
  "Noto Serif JP": { italics: false, minWeight: 200, maxWeight: 900, fallback: "serif" },
  "Noto Serif KR": { italics: false, minWeight: 200, maxWeight: 900, fallback: "serif" },
  "Noto Serif Kannada": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif Khmer": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif Khojki": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Noto Serif Lao": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif Malayalam": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif NP Hmong": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Noto Serif Oriya": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Noto Serif SC": { italics: false, minWeight: 200, maxWeight: 900, fallback: "serif" },
  "Noto Serif Sinhala": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif TC": { italics: false, minWeight: 200, maxWeight: 900, fallback: "serif" },
  "Noto Serif Tamil": { italics: true, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif Telugu": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif Thai": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif Tibetan": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Noto Serif Toto": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Noto Serif Vithkuqi": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Noto Serif Yezidi": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Noto Traditional Nushu": { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Nunito: { italics: true, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  "Nunito Sans": { italics: true, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  Ojuju: { italics: false, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  "Old Standard TT": { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Oleo Script": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Oleo Script Swash Caps": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Onest: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Open Sans": { italics: true, minWeight: 300, maxWeight: 800, fallback: "sans-serif" },
  Orbitron: { italics: false, minWeight: 400, maxWeight: 900, fallback: "sans-serif" },
  Oregano: { italics: true, minWeight: 400, maxWeight: 400, fallback: "sans-serif" },
  Oswald: { italics: false, minWeight: 200, maxWeight: 700, fallback: "sans-serif" },
  Outfit: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Overlock: { italics: true, minWeight: 400, maxWeight: 900, fallback: "sans-serif" },
  Overpass: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Overpass Mono": { italics: false, minWeight: 300, maxWeight: 700, fallback: "monospace" },
  Oxanium: { italics: false, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  Oxygen: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "PT Sans": { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "PT Sans Caption": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "PT Sans Narrow": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "PT Serif": { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "PT Serif Caption": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  Padauk: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Palanquin: { italics: false, minWeight: 100, maxWeight: 700, fallback: "sans-serif" },
  "Palanquin Dark": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Parkinsans: { italics: false, minWeight: 300, maxWeight: 800, fallback: "sans-serif" },
  "Passion One": { italics: false, minWeight: 400, maxWeight: 900, fallback: "sans-serif" },
  "Pathway Extreme": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Petrona: { italics: true, minWeight: 100, maxWeight: 900, fallback: "serif" },
  Philosopher: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Phudu: { italics: false, minWeight: 300, maxWeight: 900, fallback: "sans-serif" },
  Piazzolla: { italics: true, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Pixelify Sans": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Platypi: { italics: true, minWeight: 300, maxWeight: 800, fallback: "serif" },
  Play: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Playfair: { italics: true, minWeight: 300, maxWeight: 900, fallback: "serif" },
  "Playfair Display": { italics: true, minWeight: 400, maxWeight: 900, fallback: "serif" },
  "Playfair Display SC": { italics: true, minWeight: 400, maxWeight: 900, fallback: "serif" },
  "Playpen Sans": { italics: false, minWeight: 100, maxWeight: 800, fallback: "cursive" },
  "Playpen Sans Arabic": { italics: false, minWeight: 100, maxWeight: 800, fallback: "cursive" },
  "Playpen Sans Deva": { italics: false, minWeight: 100, maxWeight: 800, fallback: "cursive" },
  "Playpen Sans Hebrew": { italics: false, minWeight: 100, maxWeight: 800, fallback: "cursive" },
  "Playpen Sans Thai": { italics: false, minWeight: 100, maxWeight: 800, fallback: "cursive" },
  "Playwrite AR": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite AT": { italics: true, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite AT Guides": { italics: true, minWeight: 400, maxWeight: 400, fallback: "cursive" },
  "Playwrite AU NSW": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite AU QLD": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite AU SA": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite AU TAS": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite AU VIC": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite BE VLG": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite BE WAL": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite BR": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite CA": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite CL": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite CO": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite CU": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite CZ": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite DE Grund": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite DE LA": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite DE SAS": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite DE VA": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite DK Loopet": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite DK Uloopet": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite ES": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite ES Deco": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite FR Moderne": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite FR Trad": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite GB J": { italics: true, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite GB J Guides": { italics: true, minWeight: 400, maxWeight: 400, fallback: "cursive" },
  "Playwrite GB S": { italics: true, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite GB S Guides": { italics: true, minWeight: 400, maxWeight: 400, fallback: "cursive" },
  "Playwrite HR": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite HR Lijeva": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite HU": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite ID": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite IE": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite IN": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite IS": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite IT Moderna": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite IT Trad": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite MX": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite NG Modern": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite NL": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite NO": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite NZ": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite PE": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite PL": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite PT": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite RO": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite SK": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite TZ": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite US Modern": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite US Trad": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite VN": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Playwrite ZA": { italics: false, minWeight: 100, maxWeight: 400, fallback: "cursive" },
  "Plus Jakarta Sans": { italics: true, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  Podkova: { italics: false, minWeight: 400, maxWeight: 800, fallback: "serif" },
  "Poltawski Nowy": { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Poly: { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "Pontano Sans": { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Poppins: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Pragati Narrow": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Pridi: { italics: false, minWeight: 200, maxWeight: 700, fallback: "serif" },
  Prompt: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Proza Libre": { italics: true, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Public Sans": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Puritan: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Quantico: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Quattrocento: { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Quattrocento Sans": { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Quicksand: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Qwitcher Grypen": { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  REM: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Radio Canada": { italics: true, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Radio Canada Big": { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Radley: { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  Rajdhani: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Raleway: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Rambla: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Ranga: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Rasa: { italics: true, minWeight: 300, maxWeight: 700, fallback: "serif" },
  "Readex Pro": { italics: false, minWeight: 200, maxWeight: 700, fallback: "sans-serif" },
  Recursive: { italics: false, minWeight: 300, maxWeight: 900, fallback: "sans-serif" },
  "Red Hat Display": { italics: true, minWeight: 300, maxWeight: 900, fallback: "sans-serif" },
  "Red Hat Mono": { italics: true, minWeight: 300, maxWeight: 700, fallback: "monospace" },
  "Red Hat Text": { italics: true, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Red Rose": { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Redacted Script": { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Reddit Mono": { italics: false, minWeight: 200, maxWeight: 900, fallback: "monospace" },
  "Reddit Sans": { italics: true, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  "Reddit Sans Condensed": { italics: false, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  "Reem Kufi": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Reem Kufi Fun": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Rethink Sans": { italics: true, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  Roboto: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Roboto Condensed": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Roboto Mono": { italics: true, minWeight: 100, maxWeight: 700, fallback: "monospace" },
  "Roboto Serif": { italics: true, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Roboto Slab": { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  Rokkitt: { italics: true, minWeight: 100, maxWeight: 900, fallback: "serif" },
  "Ropa Sans": { italics: true, minWeight: 400, maxWeight: 400, fallback: "sans-serif" },
  Rosario: { italics: true, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Rosarivo: { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  Rowdies: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Rubik: { italics: true, minWeight: 300, maxWeight: 900, fallback: "sans-serif" },
  Ruda: { italics: false, minWeight: 400, maxWeight: 900, fallback: "sans-serif" },
  Rufina: { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Ruwudu: { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "STIX Two Text": { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  SUSE: { italics: false, minWeight: 100, maxWeight: 800, fallback: "sans-serif" },
  Sahitya: { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Saira: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Saira Condensed": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Saira Extra Condensed": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Saira Semi Condensed": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Sanchez: { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  Sansation: { italics: true, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Sansita: { italics: true, minWeight: 400, maxWeight: 900, fallback: "sans-serif" },
  "Sansita Swashed": { italics: false, minWeight: 300, maxWeight: 900, fallback: "sans-serif" },
  Sarabun: { italics: true, minWeight: 100, maxWeight: 800, fallback: "sans-serif" },
  Sarala: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Sarpanch: { italics: false, minWeight: 400, maxWeight: 900, fallback: "sans-serif" },
  Scada: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Scheherazade New": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Schibsted Grotesk": { italics: true, minWeight: 400, maxWeight: 900, fallback: "sans-serif" },
  Sedan: { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  Sen: { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Shantell Sans": { italics: true, minWeight: 300, maxWeight: 800, fallback: "sans-serif" },
  Share: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Shippori Mincho": { italics: false, minWeight: 400, maxWeight: 800, fallback: "serif" },
  "Shippori Mincho B1": { italics: false, minWeight: 400, maxWeight: 800, fallback: "serif" },
  Signika: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Signika Negative": { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Silkscreen: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Simonetta: { italics: true, minWeight: 400, maxWeight: 900, fallback: "sans-serif" },
  Sintony: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Skranji: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Smooch Sans": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Sniglet: { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Sofia Sans": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Sofia Sans Condensed": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Sofia Sans Extra Condensed": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Sofia Sans Semi Condensed": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Solway: { italics: false, minWeight: 300, maxWeight: 800, fallback: "serif" },
  "Sometype Mono": { italics: true, minWeight: 400, maxWeight: 700, fallback: "monospace" },
  Sono: { italics: false, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  Sora: { italics: false, minWeight: 100, maxWeight: 800, fallback: "sans-serif" },
  "Sorts Mill Goudy": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "Sour Gummy": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Source Code Pro": { italics: true, minWeight: 200, maxWeight: 900, fallback: "monospace" },
  "Source Sans 3": { italics: true, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  "Source Serif 4": { italics: true, minWeight: 200, maxWeight: 900, fallback: "serif" },
  "Space Grotesk": { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Space Mono": { italics: true, minWeight: 400, maxWeight: 700, fallback: "monospace" },
  Spectral: { italics: true, minWeight: 200, maxWeight: 800, fallback: "serif" },
  "Spectral SC": { italics: true, minWeight: 200, maxWeight: 800, fallback: "serif" },
  "Spline Sans": { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Spline Sans Mono": { italics: true, minWeight: 300, maxWeight: 700, fallback: "monospace" },
  Srisakdi: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Stardos Stencil": { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Stick No Bills": { italics: false, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  Stoke: { italics: false, minWeight: 300, maxWeight: 400, fallback: "serif" },
  "Sulphur Point": { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Sumana: { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Sura: { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Suwannaphum: { italics: false, minWeight: 100, maxWeight: 900, fallback: "serif" },
  Syncopate: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Syne: { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Tai Heritage Pro": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Tajawal: { italics: false, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  Tangerine: { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  Taviraj: { italics: true, minWeight: 100, maxWeight: 900, fallback: "serif" },
  Teachers: { italics: true, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  Teko: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Tektur: { italics: false, minWeight: 400, maxWeight: 900, fallback: "sans-serif" },
  Texturina: { italics: true, minWeight: 100, maxWeight: 900, fallback: "serif" },
  Thasadith: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "The Nautigal": { italics: false, minWeight: 400, maxWeight: 700, fallback: "cursive" },
  Tienne: { italics: false, minWeight: 400, maxWeight: 900, fallback: "serif" },
  Tillana: { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  Tinos: { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  "Tiro Bangla": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "Tiro Devanagari Hindi": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "Tiro Devanagari Marathi": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "Tiro Devanagari Sanskrit": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "Tiro Gurmukhi": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "Tiro Kannada": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "Tiro Tamil": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "Tiro Telugu": { italics: true, minWeight: 400, maxWeight: 400, fallback: "serif" },
  "Titillium Web": { italics: true, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  Tomorrow: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Tourney: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Trirong: { italics: true, minWeight: 100, maxWeight: 900, fallback: "serif" },
  Trispace: { italics: false, minWeight: 100, maxWeight: 800, fallback: "sans-serif" },
  Trochut: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Truculenta: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Tsukimi Rounded": { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Tuffy: { italics: true, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  "Turret Road": { italics: false, minWeight: 200, maxWeight: 800, fallback: "sans-serif" },
  Ubuntu: { italics: true, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  "Ubuntu Mono": { italics: true, minWeight: 400, maxWeight: 700, fallback: "monospace" },
  "Ubuntu Sans": { italics: true, minWeight: 100, maxWeight: 800, fallback: "sans-serif" },
  "Ubuntu Sans Mono": { italics: true, minWeight: 400, maxWeight: 700, fallback: "monospace" },
  Unbounded: { italics: false, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  UnifrakturCook: { italics: false, minWeight: 700, maxWeight: 700, fallback: "sans-serif" },
  Unkempt: { italics: false, minWeight: 400, maxWeight: 700, fallback: "sans-serif" },
  Unna: { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Urbanist: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Varta: { italics: false, minWeight: 300, maxWeight: 700, fallback: "sans-serif" },
  Vazirmatn: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Vesper Libre": { italics: false, minWeight: 400, maxWeight: 900, fallback: "serif" },
  "Victor Mono": { italics: true, minWeight: 100, maxWeight: 700, fallback: "monospace" },
  Volkhov: { italics: true, minWeight: 400, maxWeight: 700, fallback: "serif" },
  Vollkorn: { italics: true, minWeight: 400, maxWeight: 900, fallback: "serif" },
  "Vollkorn SC": { italics: false, minWeight: 400, maxWeight: 900, fallback: "serif" },
  Wavefont: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  WindSong: { italics: false, minWeight: 400, maxWeight: 500, fallback: "cursive" },
  "Winky Rough": { italics: true, minWeight: 300, maxWeight: 900, fallback: "sans-serif" },
  "Winky Sans": { italics: true, minWeight: 300, maxWeight: 900, fallback: "sans-serif" },
  Wittgenstein: { italics: true, minWeight: 400, maxWeight: 900, fallback: "serif" },
  "Wix Madefor Display": { italics: false, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Wix Madefor Text": { italics: true, minWeight: 400, maxWeight: 800, fallback: "sans-serif" },
  "Work Sans": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Xanh Mono": { italics: true, minWeight: 400, maxWeight: 400, fallback: "monospace" },
  Yaldevi: { italics: false, minWeight: 200, maxWeight: 700, fallback: "sans-serif" },
  "Yanone Kaffeesatz": { italics: false, minWeight: 200, maxWeight: 700, fallback: "sans-serif" },
  Yantramanav: { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Yrsa: { italics: true, minWeight: 300, maxWeight: 700, fallback: "serif" },
  Ysabeau: { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Ysabeau Infant": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Ysabeau Office": { italics: true, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  "Ysabeau SC": { italics: false, minWeight: 100, maxWeight: 900, fallback: "sans-serif" },
  Zain: { italics: true, minWeight: 200, maxWeight: 900, fallback: "sans-serif" },
  "Zen Kaku Gothic Antique": { italics: false, minWeight: 300, maxWeight: 900, fallback: "sans-serif" },
  "Zen Kaku Gothic New": { italics: false, minWeight: 300, maxWeight: 900, fallback: "sans-serif" },
  "Zen Loop": { italics: true, minWeight: 400, maxWeight: 400, fallback: "sans-serif" },
  "Zen Maru Gothic": { italics: false, minWeight: 300, maxWeight: 900, fallback: "sans-serif" },
  "Zen Old Mincho": { italics: false, minWeight: 400, maxWeight: 900, fallback: "serif" },
  "Zilla Slab": { italics: true, minWeight: 300, maxWeight: 700, fallback: "serif" },
  "Zilla Slab Highlight": { italics: false, minWeight: 400, maxWeight: 700, fallback: "serif" },
};

export const constructFontSelectOptions = (fonts: FontRegistry) => {
  const fontOptions: StyleSelectOption[] = [];
  for (const fontName in fonts) {
    const fontDetails = fonts[fontName];
    fontOptions.push({
      label: fontName,
      value: `'${fontName}', ${fontDetails.fallback}`,
    });
  }
  return fontOptions;
};

/*
 * generateGoogleFontsURL takes a list of fonts and the available values for
 * their variable font axes and the <link> tags needed to load Google fonts
 * Note: Google does not return font file URLs if the params
 * fall outside of the font's supported values
 */
const constructGoogleFontLinkTags = (fonts: FontRegistry): string => {
  const prefix = `<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?`;
  const postfix = `display=swap" rel="stylesheet">`;

  const fontEntries = Object.entries(fonts);
  const chunkSize = 7;
  const linkTags: string[] = [];

  for (let i = 0; i < fontEntries.length; i += chunkSize) {
    const chunk = fontEntries.slice(i, i + chunkSize);

    const params = chunk
      .map(([fontName, fontDetails]) => {
        const axes = fontDetails.italics ? ":ital,wght@" : ":wght@";
        const weightRange = `${fontDetails.minWeight}..${fontDetails.maxWeight}`;
        const weightParam = fontDetails.italics
          ? `0,${weightRange};1,${weightRange}`
          : weightRange;
        return "family=" + fontName.replaceAll(" ", "+") + axes + weightParam;
      })
      .join("&");

    linkTags.push(`${prefix}${params}&${postfix}`);
  }

  return linkTags.join("\n");
};

export const googleFontLinkTags = constructGoogleFontLinkTags(defaultFonts);

const defaultWeightOptions = [
  { label: "Thin (100)", value: "100" },
  { label: "Extralight (200)", value: "200" },
  { label: "Light (300)", value: "300" },
  { label: "Normal (400)", value: "400" },
  { label: "Medium (500)", value: "500" },
  { label: "Semibold (600)", value: "600" },
  { label: "Bold (700)", value: "700" },
  { label: "Extrabold (800)", value: "800" },
  { label: "Black (900)", value: "900" },
];

type getFontWeightParams = {
  fontCssVariable?: string;
  weightOptions?: StyleSelectOption[];
  fontList?: FontRegistry;
};

/*
 * getFontWeightOptions returns the available font weights for a given CSS variable
 * for use in the theme.config.
 * Must return synchronously because the theme.config is processed synchronously
 */
export const getFontWeightOptions = (options: getFontWeightParams) => {
  const { fontCssVariable, weightOptions = defaultWeightOptions } = options;
  if (!fontCssVariable || typeof window === "undefined") {
    // return all options if no variable provided, or not in browser
    return weightOptions;
  }

  // get the preview iframe
  const iframe = document.getElementById(
    PUCK_PREVIEW_IFRAME_ID
  ) as HTMLIFrameElement;
  const styleElement = iframe?.contentDocument?.getElementById(
    "visual-editor-theme"
  ) as HTMLStyleElement;

  if (!styleElement) {
    return defaultWeightOptions;
  }

  return filterFontWeights(styleElement, options);
};

/*
 * getFontWeightOverrideOptions returns the available font weights for a given CSS variable
 * for use in the resolveFields function of individual components.
 * Must return a promise because resolveFields can run before the iframe is loaded.
 */
export const getFontWeightOverrideOptions = async (
  options: getFontWeightParams
) => {
  return new Promise<StyleSelectOption[]>((resolve) => {
    const getAndFilterFontWeights = () => {
      const iframe = document.getElementById(
        PUCK_PREVIEW_IFRAME_ID
      ) as HTMLIFrameElement;
      const styleTag = iframe.contentDocument?.getElementById(
        THEME_STYLE_TAG_ID
      ) as HTMLStyleElement;
      if (styleTag) {
        observer.disconnect();
        const weights = filterFontWeights(styleTag, options);
        resolve([{ label: "Default", value: "default" }, ...weights]);
      }
    };

    const observer = new MutationObserver(getAndFilterFontWeights);

    // Try to run, will succeed if the style tag has already loaded
    getAndFilterFontWeights();

    // If not, observe mutations until it loads
    observer.observe(document, {
      childList: true,
      subtree: true,
    });
  });
};

/*
 * filterFontWeights captures the font name from the CSS value and then returns
 * the available font weights for that font.
 */
const filterFontWeights = (
  styleElement: HTMLStyleElement,
  {
    fontCssVariable,
    weightOptions = defaultWeightOptions,
    fontList = defaultFonts,
  }: getFontWeightParams
) => {
  // get the font name from css variable in the style tag
  const styleContent = styleElement.textContent || styleElement.innerHTML;
  const regex = new RegExp( // matches Arial in "'Arial', sans-serif"
    `${fontCssVariable}:\\s*(['"]?([^',\\s]+(?:\\s+[^',\\s]+)*)['"]?)(?:,|\\s|;|$)`,
    "i"
  );
  const fontName = styleContent.match(regex)?.[2];

  if (!fontName || !fontList[fontName]) {
    return weightOptions;
  }

  // filter the font weights by the font's allowed values
  return weightOptions.filter(
    (weight) =>
      Number(weight.value) <= fontList[fontName].maxWeight &&
      Number(weight.value) >= fontList[fontName].minWeight
  );
};
