export const disallowedFonts = [
  // Symbol fonts
  "Wingdings",
  "Wingdings 2",
  "Wingdings 3",
  "Webdings",
  "Symbol",
  "Zapf Dingbats",
  "Marlett",

  // Not supported by Cloudflare Fonts
  "42dot Sans",
  "Afacad Flux",
  "Ancizar Sans",
  "Ancizar Serif",
  "Annapurna SIL",
  "Anta",
  "Anton SC",
  "Arsenal SC",
  "Atkinson Hyperlegible Mono",
  "Atkinson Hyperlegible Next",
  "Badeen Display",
  "Baskervville SC",
  "Beiruti",
  "Big Shoulders",
  "Big Shoulders Inline",
  "Big Shoulders Stencil",
  "Bodoni Moda SC",
  "Boldonse",
  "Bona Nova SC",
  "Bungee Tint",
  "Bytesized",
  "Cactus Classical Serif",
  "Cal Sans",
  "Cascadia Code",
  "Cascadia Mono",
  "Chocolate Classical Sans",
  "Comic Relief",
  "Coral Pixels",
  "Doto",
  "Edu AU VIC WA NT Arrows",
  "Edu AU VIC WA NT Dots",
  "Edu AU VIC WA NT Guides",
  "Edu AU VIC WA NT Hand",
  "Edu AU VIC WA NT Pre",
  "Edu AU VIC WA NT",
  "Exile",
  "Faculty Glyphic",
  "Freeman",
  "Funnel Display",
  "Funnel Sans",
  "Fustat",
  "Ga Maamli",
  "Geist",
  "Geist Mono",
  "Gidole",
  "Hind Mysuru",
  "Host Grotesk",
  "Hubot Sans",
  "Iansui",
  "Jacquard 12",
  "Jacquard 12 Charted",
  "Jacquard 24",
  "Jacquard 24 Charted",
  "Jacquarda Bastarda 9",
  "Jacquarda Bastarda 9 Charted",
  "Jaini",
  "Jaini Purva",
  "Jersey 10",
  "Jersey 10 Charted",
  "Jersey 15",
  "Jersey 15 Charted",
  "Jersey 20",
  "Jersey 20 Charted",
  "Jersey 25",
  "Jersey 25 Charted",
  "Kalnia Glaze",
  "Kanchenjunga",
  "Kapakana",
  "Kode Mono",
  "LXGW WenKai Mono TC",
  "LXGW WenKai TC",
  "Liter",
  "Madimi One",
  "Maname",
  "Matemasie",
  "Material Icons",
  "Material Icons Outlined",
  "Material Icons Round",
  "Material Icons Sharp",
  "Material Icons Two Tone",
  "Material Symbols",
  "Material Symbols Outlined",
  "Material Symbols Rounded",
  "Material Symbols Sharp",
  "Micro 5",
  "Micro 5 Charted",
  "Moderustic",
  "Molle",
  "Mona Sans",
  "Monomakh",
  "Montserrat Underline",
  "Namdhinggo",
  "National Park",
  "New Amsterdam",
  "Noto Sans PhagsPa",
  "Noto Serif Dives Akuru",
  "Noto Serif Hentaigana",
  "Noto Serif Todhri",
  "Noto Znamenny Musical Notation",
  "Ojuju",
  "Parkinsans",
  "Platypi",
  "Playpen Sans Arabic",
  "Playpen Sans Deva",
  "Playpen Sans Hebrew",
  "Playpen Sans Thai",
  "Playwrite AR",
  "Playwrite AR Guides",
  "Playwrite AT",
  "Playwrite AT Guides",
  "Playwrite AU NSW",
  "Playwrite AU NSW Guides",
  "Playwrite AU QLD",
  "Playwrite AU QLD Guides",
  "Playwrite AU SA",
  "Playwrite AU SA Guides",
  "Playwrite AU TAS",
  "Playwrite AU TAS Guides",
  "Playwrite AU VIC",
  "Playwrite AU VIC Guides",
  "Playwrite BE VLG",
  "Playwrite BE VLG Guides",
  "Playwrite BE WAL",
  "Playwrite BE WAL Guides",
  "Playwrite BR",
  "Playwrite BR Guides",
  "Playwrite CA",
  "Playwrite CA Guides",
  "Playwrite CL",
  "Playwrite CL Guides",
  "Playwrite CO",
  "Playwrite CO Guides",
  "Playwrite CU",
  "Playwrite CU Guides",
  "Playwrite CZ",
  "Playwrite CZ Guides",
  "Playwrite DE Grund",
  "Playwrite DE Grund Guides",
  "Playwrite DE LA",
  "Playwrite DE LA Guides",
  "Playwrite DE SAS",
  "Playwrite DE SAS Guides",
  "Playwrite DE VA",
  "Playwrite DE VA Guides",
  "Playwrite DK Loopet",
  "Playwrite DK Loopet Guides",
  "Playwrite DK Uloopet",
  "Playwrite DK Uloopet Guides",
  "Playwrite ES",
  "Playwrite ES Deco",
  "Playwrite ES Deco Guides",
  "Playwrite ES Guides",
  "Playwrite FR Moderne",
  "Playwrite FR Moderne Guides",
  "Playwrite FR Trad",
  "Playwrite FR Trad Guides",
  "Playwrite GB J",
  "Playwrite GB J Guides",
  "Playwrite GB S",
  "Playwrite GB S Guides",
  "Playwrite HR",
  "Playwrite HR Guides",
  "Playwrite HR Lijeva",
  "Playwrite HR Lijeva Guides",
  "Playwrite HU",
  "Playwrite HU Guides",
  "Playwrite ID",
  "Playwrite ID Guides",
  "Playwrite IE",
  "Playwrite IE Guides",
  "Playwrite IN",
  "Playwrite IN Guides",
  "Playwrite IS",
  "Playwrite IS Guides",
  "Playwrite IT Moderna",
  "Playwrite IT Moderna Guides",
  "Playwrite IT Trad",
  "Playwrite IT Trad Guides",
  "Playwrite MX",
  "Playwrite MX Guides",
  "Playwrite NG Modern",
  "Playwrite NG Modern Guides",
  "Playwrite NL",
  "Playwrite NL Guides",
  "Playwrite NO",
  "Playwrite NO Guides",
  "Playwrite NZ",
  "Playwrite NZ Guides",
  "Playwrite PE",
  "Playwrite PE Guides",
  "Playwrite PL",
  "Playwrite PL Guides",
  "Playwrite PT",
  "Playwrite PT Guides",
  "Playwrite RO",
  "Playwrite RO Guides",
  "Playwrite SK",
  "Playwrite SK Guides",
  "Playwrite TZ",
  "Playwrite TZ Guides",
  "Playwrite US Modern",
  "Playwrite US Modern Guides",
  "Playwrite US Trad",
  "Playwrite US Trad Guides",
  "Playwrite VN",
  "Playwrite VN Guides",
  "Playwrite ZA",
  "Playwrite ZA Guides",
  "Pochaevsk",
  "Poetsen One",
  "Ponnala",
  "Ponomar",
  "Protest Guerrilla",
  "Protest Revolution",
  "Protest Riot",
  "Protest Strike",
  "Radio Canada Big",
  "Reddit Mono",
  "Reddit Sans",
  "Reddit Sans Condensed",
  "Rubik Glitch Pop",
  "SUSE",
  "Sankofa Display",
  "Sansation",
  "Sedan",
  "Sedan SC",
  "Shafarik",
  "Sour Gummy",
  "Special Gothic",
  "Special Gothic Condensed One",
  "Special Gothic Expanded One",
  "Tac One",
  "Tagesschrift",
  "Teachers",
  "Tiny5",
  "Triodion",
  "Tuffy",
  "Ubuntu Sans",
  "Ubuntu Sans Mono",
  "WDXL Lubrifont TC",
  "Winky Rough",
  "Winky Sans",
  "Wittgenstein",
  "Yarndings 12",
  "Yarndings 12 Charted",
  "Yarndings 20",
  "Yarndings 20 Charted",
  "Zain",
];
