buildConfiguration:
  buildCommand: cd packages/visual-editor && pnpm run build-registry-docs
  installDependenciesStep:
    command: npm install -g pnpm && cd packages/visual-editor && pnpm install --ignore-scripts
    requiredFiles:
      - packages/visual-editor/package.json
      - pnpm-lock.yaml
      - .npmrc
      - tsconfig.json
