buildConfiguration:
  buildCommand: cd packages/visual-editor && pnpm docs:build
  installDependenciesStep:
    command: npm install -g pnpm && cd packages/visual-editor && pnpm install
    requiredFiles:
      - packages/visual-editor/package.json
      - packages/visual-editor/package-lock.json
      - packages/visual-editor/.npmrc
