/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */
import "@yext/visual-editor/style.css";
import "../index.css";
import {
  Template,
  GetPath,
  TemplateProps,
  TemplateRenderProps,
  TransformProps,
  GetHeadConfig,
  HeadConfig,
  TagType,
} from "@yext/pages";
import { Render, resolveAllData } from "@measured/puck";
import {
  applyTheme,
  VisualEditorProvider,
  normalizeSlug,
  getPageMetadata,
  applyAnalytics,
  applyHeaderScript,
  migrate,
  migrationRegistry,
  defaultThemeConfig,
  directoryConfig,
  getSchema,
  getCanonicalUrl,
  // clearPuckCache,
  // getPuckCacheSize,
  // clearPuckCacheAsync,
} from "@yext/visual-editor";
import { AnalyticsProvider, SchemaWrapper } from "@yext/pages-components";

export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = (
  data: TemplateRenderProps
): HeadConfig => {
  const { document, relativePrefixToRoot } = data;
  const { title, description } = getPageMetadata(document);
  const schema = getSchema(data);
  const faviconUrl = document?._favicon ?? document?._site?.favicon?.url;

  return {
    title: title,
    charset: "UTF-8",
    viewport: "width=device-width, initial-scale=1",
    tags: [
      {
        type: "link",
        attributes: {
          rel: "icon",
          type: "image/x-icon",
        },
      },
      ...(data.document.siteDomain
        ? [
            {
              type: "link",
              attributes: {
                rel: "canonical",
                href: getCanonicalUrl(data),
              },
            },
          ]
        : []),
      ...(description
        ? [
            {
              type: "meta" as TagType,
              attributes: {
                name: "description",
                content: description,
              },
            },
          ]
        : []),
      ...(faviconUrl
        ? [
            {
              type: "link" as TagType,
              attributes: {
                rel: "icon",
                type: "image/x-icon",
                href: faviconUrl,
              },
            },
          ]
        : []),
    ],
    other: [
      applyAnalytics(document),
      applyHeaderScript(document),
      applyTheme(document, relativePrefixToRoot, defaultThemeConfig),
      SchemaWrapper(schema),
    ].join("\n"),
  };
};

export const getPath: GetPath<TemplateProps> = ({ document }) => {
  if (document.slug) {
    return document.slug;
  }

  const localePath = document.locale !== "en" ? `${document.locale}/` : "";
  const path = `${localePath}${document.id}`;

  return normalizeSlug(path);
};

export const transformProps: TransformProps<TemplateProps> = async (props) => {
  const { document } = props;
  const migratedData = migrate(
    JSON.parse(document.__.layout),
    migrationRegistry,
    directoryConfig,
    document
  );

  // Log cache size before resolveAllData
  // const cacheSizeBefore = getPuckCacheSize();
  // console.log(
  //   `[VE transformProps] Before resolveAllData for document ${document.id}: cache size = ${cacheSizeBefore}`
  // );

  const updatedData = await resolveAllData(migratedData, directoryConfig, {
    streamDocument: document,
  });

  // Log cache size after resolveAllData but before clearing
  // const cacheSizeAfterResolve = getPuckCacheSize();
  // console.log(
  //   `[VE transformProps] After resolveAllData for document ${document.id}: cache size = ${cacheSizeAfterResolve} (was ${cacheSizeBefore})`
  // );

  // Clear Puck's internal cache after resolving data to prevent memory leaks
  // when processing many pages. The cache stores resolved data per component ID
  // and never gets cleared, causing memory to accumulate across page invocations.
  // The cache also stores parentData with references to document objects, which
  // prevents garbage collection and causes exponential memory growth.
  // Use async version for Deno compatibility
  // await clearPuckCacheAsync();

  return { ...props, data: updatedData };
};

const Directory: Template<TemplateRenderProps> = (props) => {
  const { document, data } = props;

  return (
    <AnalyticsProvider
      apiKey={document?._env?.YEXT_PUBLIC_VISUAL_EDITOR_APP_API_KEY}
      templateData={props}
      currency="USD"
    >
      <VisualEditorProvider templateProps={props}>
        <Render
          config={directoryConfig}
          data={data}
          metadata={{ streamDocument: document }}
        />
      </VisualEditorProvider>
    </AnalyticsProvider>
  );
};

export default Directory;
