/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */
import "@yext/visual-editor/editor.css";
import "../index.css";
import * as React from "react";
import { type Config, Render, resolveAllData } from "@puckeditor/core";
import {
  applyTheme,
  buildLocalEditorDocumentRequestPath,
  defaultThemeConfig,
  directoryConfig,
  Editor,
  locatorConfig,
  migrate,
  migrationRegistry,
  readLocalEditorPreviewLayoutData,
  usePlatformBridgeDocument,
  usePlatformBridgeEntityFields,
  VisualEditorProvider,
} from "@yext/visual-editor";
import {
  GetPath,
  TemplateProps,
  TemplateConfig,
  HeadConfig,
  TemplateRenderProps,
  GetHeadConfig,
} from "@yext/pages";
import tailwindConfig from "../../tailwind.config";

const componentRegistry: Record<string, Config<any>> = {
  directory: directoryConfig,
  locator: locatorConfig,
};

const editPath = "__YEXT_VISUAL_EDITOR_PATH__";
const previewModeParam = "preview";
const previewStorageKeyParam = "previewStorageKey";
const localEditorApiBasePath = "/__yext_visual_editor/local-editor";

// Editor path is injected at generation time based on the available templates.
export const getPath: GetPath<TemplateProps> = () => {
  return editPath;
};

export const config: TemplateConfig = {
  name: "__YEXT_VISUAL_EDITOR_TEMPLATE_NAME__",
};

export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = ({
  document,
}): HeadConfig => {
  return {
    title: "__YEXT_VISUAL_EDITOR_TEMPLATE_NAME__",
    other: fullStorySnippet + applyTheme(document, "./", defaultThemeConfig),
  };
};

const Preview = () => {
  const [previewState, setPreviewState] = React.useState<{
    document: Record<string, unknown>;
    entityFields: any;
    data: any;
  } | null>(null);
  const [previewError, setPreviewError] = React.useState<string | null>(null);

  const searchParams = React.useMemo(() => {
    if (typeof window === "undefined") {
      return new URLSearchParams();
    }

    return new URLSearchParams(window.location.search);
  }, []);

  const previewTemplateId = searchParams.get("templateId") ?? "";
  const previewEntityId = searchParams.get("entityId") ?? undefined;
  const previewLocale = searchParams.get("locale") ?? "";
  const previewStorageKey = searchParams.get(previewStorageKeyParam);
  const previewConfig = componentRegistry[previewTemplateId];

  React.useEffect(() => {
    if (!previewTemplateId || !previewLocale || !previewConfig) {
      setPreviewError("Missing preview context.");
      return;
    }

    let isCurrent = true;

    const loadPreview = async () => {
      try {
        const documentRequestPath = buildLocalEditorDocumentRequestPath({
          apiBasePath: localEditorApiBasePath,
          templateId: previewTemplateId,
          entityId: previewEntityId,
          locale: previewLocale,
        });

        if (!documentRequestPath) {
          throw new Error("Missing preview document request parameters.");
        }

        const response = await fetch(documentRequestPath);

        if (!response.ok) {
          throw new Error(
            `Failed to load preview document (${response.status})`
          );
        }

        const payload = (await response.json()) as {
          document: Record<string, unknown> | null;
          entityFields: any;
        };

        const document = payload.document;
        if (!document) {
          throw new Error("Preview document not available.");
        }

        const localLayoutData = readLocalEditorPreviewLayoutData({
          previewStorageKey,
          document,
        });

        const migratedLayoutData = migrate(
          localLayoutData as any,
          migrationRegistry,
          previewConfig,
          document
        );

        const resolvedLayoutData = await resolveAllData(
          migratedLayoutData as any,
          previewConfig,
          {
            streamDocument: document,
          }
        );

        if (!isCurrent) {
          return;
        }

        setPreviewState({
          document,
          entityFields: payload.entityFields,
          data: resolvedLayoutData,
        });
      } catch (error) {
        if (!isCurrent) {
          return;
        }

        setPreviewError(error instanceof Error ? error.message : String(error));
      }
    };

    void loadPreview();

    return () => {
      isCurrent = false;
    };
  }, [
    previewConfig,
    previewEntityId,
    previewLocale,
    previewStorageKey,
    previewTemplateId,
  ]);

  if (previewError) {
    return <p>{previewError}</p>;
  }

  if (!previewState) {
    return <p>Loading preview...</p>;
  }

  const renderConfig = previewConfig as Config<any>;

  return (
    <VisualEditorProvider
      templateProps={{ document: previewState.document }}
      entityFields={previewState.entityFields}
      tailwindConfig={tailwindConfig}
    >
      <Render
        config={renderConfig}
        data={previewState.data}
        metadata={{ streamDocument: previewState.document }}
      />
    </VisualEditorProvider>
  );
};

// Render the editor
const Edit: () => JSX.Element = () => {
  // Wait for URLSearchParams to be available
  const [isClientReady, setIsClientReady] = React.useState(false);

  React.useEffect(() => {
    setIsClientReady(true);
  }, []);

  if (!isClientReady) {
    return null;
  }

  const searchParams = new URLSearchParams(window.location.search);
  const isPreviewMode = searchParams.get(previewModeParam) === "1";

  if (isPreviewMode) {
    return <Preview />;
  }

  const entityDocument = usePlatformBridgeDocument();
  const entityFields = usePlatformBridgeEntityFields();

  return (
    <VisualEditorProvider
      templateProps={{
        document: entityDocument,
      }}
      entityFields={entityFields}
      tailwindConfig={tailwindConfig}
    >
      <Editor
        document={entityDocument}
        componentRegistry={componentRegistry}
        themeConfig={defaultThemeConfig}
      />
    </VisualEditorProvider>
  );
};

export default Edit;

const fullStorySnippet = `<script>
window['_fs_run_in_iframe'] = true;
window['_fs_debug'] = false;
window['_fs_host'] = 'fullstory.com';
window['_fs_script'] = 'edge.fullstory.com/s/fs.js';
window['_fs_org'] = 'o-1RWKDJ-na1';
window['_fs_namespace'] = 'FS';
!function(m,n,e,t,l,o,g,y){var s,f,a=function(h){
return!(h in m)||(m.console&&m.console.log&&m.console.log('FullStory namespace conflict. Please set window["_fs_namespace"].'),!1)}(e)
;function j(b){var h,d=[];function k(){h&&(d.forEach((function(b){var d;try{d=b[h[0]]&&b[h[0]](h[1])}catch(h){return void(b[3]&&b[3](h))}
d&&d.then?d.then(b[2],b[3]):b[2]&&b[2](d)})),d.length=0)}function r(b){return function(d){h||(h=[b,d],k())}}return b(r(0),r(1)),{
then:function(b,h){return j((function(r,i){d.push([b,h,r,i]),k()}))}}}a&&(g=m[e]=function(){var b=function(b,d,k,r){function i(i,c){
h(b,d,k,i,c,r)}r=r||2;var c,u=/Async$/;return u.test(b)?(b=b.replace(u,""),"function"==typeof Promise?new Promise(i):j(i)):h(b,d,k,c,c,r)}
;function h(h,d,k,r,i,c){return b._api?b._api(h,d,k,r,i,c):(b.q&&b.q.push([h,d,k,r,i,c]),null)}return b.q=[],b}(),y=function(b){function h(h){
"function"==typeof h[4]&&h[4](new Error(b))}var d=g.q;if(d){for(var k=0;k<d.length;k++)h(d[k]);d.length=0,d.push=h}},function(){
(o=n.createElement(t)).async=!0,o.crossOrigin="anonymous",o.src="https://"+l,o.onerror=function(){y("Error loading "+l)}
;var b=n.getElementsByTagName(t)[0];b.parentNode.insertBefore(o,b)}(),function(){function b(){}function h(b,h,d){g(b,h,d,1)}function d(b,d,k){
h("setProperties",{type:b,properties:d},k)}function k(b,h){d("user",b,h)}function r(b,h,d){k({uid:b},d),h&&k(h,d)}g.identify=r,g.setUserVars=k,
g.identifyAccount=b,g.clearUserCookie=b,g.setVars=d,g.event=function(b,d,k){h("trackEvent",{name:b,properties:d},k)},g.anonymize=function(){r(!1)
},g.shutdown=function(){h("shutdown")},g.restart=function(){h("restart")},g.log=function(b,d){h("log",{level:b,msg:d})},g.consent=function(b){
h("setIdentity",{consent:!arguments.length||b})}}(),s="fetch",f="XMLHttpRequest",g._w={},g._w[f]=m[f],g._w[s]=m[s],m[s]&&(m[s]=function(){
return g._w[s].apply(this,arguments)}),g._v="2.0.0")}(window,document,window._fs_namespace,"script",window._fs_script);
</script>`;
