/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */
import React from "react";
import {
  GetHeadConfig,
  GetPath,
  HeadConfig,
  Template,
  TemplateConfig,
  TemplateProps,
  TemplateRenderProps,
} from "@yext/pages";

const entryMode = "__YEXT_VISUAL_EDITOR_ENTRY_MODE__" as "redirect" | "chooser";
const redirectTargetPath = "__YEXT_VISUAL_EDITOR_COMPAT_TARGET_PATH__";
const templateIds = JSON.parse(
  atob("__YEXT_VISUAL_EDITOR_ENTRY_TEMPLATE_IDS_BASE64__")
) as string[];

export const getPath: GetPath<TemplateProps> = () => {
  return "edit";
};

export const config: TemplateConfig = {
  name: "edit",
};

export const getHeadConfig: GetHeadConfig<
  TemplateRenderProps
> = (): HeadConfig => {
  return {
    title: entryMode === "redirect" ? "Redirecting to Editor" : "Choose Editor",
    other: `<script>
(function() {
  var entryMode = ${JSON.stringify(entryMode)};
  var redirectTargetPath = ${JSON.stringify(redirectTargetPath)};
  var search = window.location.search || "";
  var hash = window.location.hash || "";

  document
    .querySelectorAll("[data-template-path]")
    .forEach(function(link) {
      var templatePath = link.getAttribute("data-template-path");
      if (!templatePath) {
        return;
      }

      var normalizedPath = "/" + templatePath.replace(/^\\/+/, "");
      link.setAttribute("href", normalizedPath + search + hash);
    });

  if (entryMode !== "redirect") {
    return;
  }

  var normalizedTargetPath = "/" + redirectTargetPath.replace(/^\\/+/, "");
  if (window.location.pathname === normalizedTargetPath) {
    return;
  }
  var nextUrl =
    normalizedTargetPath + search + hash;
  window.location.replace(nextUrl);
})();
</script>`,
  };
};

const EditCompat: Template<TemplateRenderProps> = () => {
  if (entryMode === "redirect") {
    return <p>Redirecting to editor...</p>;
  }

  return (
    <main
      style={{
        fontFamily: "sans-serif",
        padding: "32px 24px",
        maxWidth: "720px",
        margin: "0 auto",
      }}
    >
      <h1 style={{ fontSize: "28px", marginBottom: "12px" }}>
        Choose a local editor
      </h1>
      <p style={{ marginBottom: "24px", lineHeight: 1.5 }}>
        This local starter repo has multiple custom templates. Pick which local
        editor page to open.
      </p>
      <ul style={{ listStyle: "none", padding: 0, margin: 0 }}>
        {templateIds.map((templateId) => {
          const templatePath = `edit/${templateId}`;
          return (
            <li key={templateId} style={{ marginBottom: "12px" }}>
              <a
                data-template-path={templatePath}
                href={`/${templatePath}`}
                style={{
                  display: "block",
                  padding: "14px 16px",
                  border: "1px solid #d0d7de",
                  borderRadius: "8px",
                  color: "#0969da",
                  textDecoration: "none",
                }}
              >
                {templateId}
              </a>
            </li>
          );
        })}
      </ul>
    </main>
  );
};

export default EditCompat;
