/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */
import type {
  GetPath,
  Template,
  TemplateConfig,
  TemplateProps,
} from "@yext/pages";
import localEditorStreamConfigJson from "__LOCAL_EDITOR_STREAM_CONFIG_IMPORT__";

type LocalEditorStreamDefinition = {
  $id?: string;
  fields?: Array<string | { name: string }>;
  filter?: {
    entityIds?: string[];
    entityTypes?: string[];
    savedFilterIds?: string[];
  };
  localization?: {
    locales?: string[];
    primary?: true;
  };
  transform?: {
    expandOptionFields?: string[];
    replaceOptionValuesWithDisplayNames?: string[];
  };
  includeCertifiedFacts?: boolean;
};

type LocalEditorStreamConfig = {
  templates?: Record<
    string,
    {
      stream?: LocalEditorStreamDefinition;
    }
  >;
  stream?: LocalEditorStreamDefinition;
};

const localEditorTemplateId = "__LOCAL_EDITOR_TEMPLATE_ID__";
const localEditorDataTemplateName = "__LOCAL_EDITOR_DATA_TEMPLATE_NAME__";

const normalizeLocalEditorPagesStream = (
  streamConfig?: LocalEditorStreamDefinition
) => {
  if (!streamConfig) {
    return undefined;
  }

  const fields = (streamConfig.fields ?? [])
    .map((field) => {
      return typeof field === "string" ? field : field.name;
    })
    .filter((fieldName): fieldName is string => {
      return !!fieldName && fieldName !== "locale";
    })
    .filter((fieldName, index, values) => {
      return values.indexOf(fieldName) === index;
    });

  return {
    ...streamConfig,
    fields,
  };
};

const templateStreamConfig =
  (localEditorStreamConfigJson as LocalEditorStreamConfig).templates?.[
    localEditorTemplateId
  ]?.stream ?? (localEditorStreamConfigJson as LocalEditorStreamConfig).stream;

const localEditorStreamConfig =
  normalizeLocalEditorPagesStream(templateStreamConfig);

export const getPath: GetPath<TemplateProps> = ({ document }) => {
  const entityId =
    (typeof document.id === "string" || typeof document.id === "number") &&
    String(document.id).length > 0
      ? String(document.id)
      : "local-editor-document";
  const locale =
    typeof document.locale === "string" && document.locale.length > 0
      ? document.locale
      : "en";

  return `__yext_visual_editor/local-editor-data/${locale}/${entityId}`;
};

export const config: TemplateConfig = localEditorStreamConfig
  ? {
      name: localEditorDataTemplateName,
      stream: localEditorStreamConfig,
    }
  : {
      name: localEditorDataTemplateName,
    };

const LocalEditorData: Template = () => {
  return null;
};

export default LocalEditorData;
