/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */
import "@yext/visual-editor/editor.css";
import "../index.css";
import {
  GetPath,
  Template,
  TemplateConfig,
  TemplateProps,
  TemplateRenderProps,
  GetHeadConfig,
  HeadConfig,
} from "@yext/pages";
import { type Config } from "@puckeditor/core";
import {
  defaultThemeConfig,
  directoryConfig,
  LocalEditorShell,
  locatorConfig,
} from "@yext/visual-editor";
import tailwindConfig from "../../tailwind.config";

const DEFAULT_LOCAL_EDITOR_ROUTE = "/local-editor";
const localEditorStylesheetHrefs: string[] | string =
  "__LOCAL_EDITOR_STYLESHEET_HREFS__";

const componentRegistry: Record<string, Config<any>> = {
  directory: directoryConfig,
  locator: locatorConfig,
};

export const getPath: GetPath<TemplateProps> = () => {
  return DEFAULT_LOCAL_EDITOR_ROUTE.slice(1);
};

export const config: TemplateConfig = {
  name: "local-editor",
};

export const getHeadConfig: GetHeadConfig<
  TemplateRenderProps
> = (): HeadConfig => {
  const stylesheetLinks = (
    Array.isArray(localEditorStylesheetHrefs) ? localEditorStylesheetHrefs : []
  ).map((href) => {
    return `<link href="${href}" rel="stylesheet" data-visual-editor-font="true">`;
  });

  return {
    title: "Local Editor",
    ...(stylesheetLinks.length > 0
      ? {
          other: stylesheetLinks.join("\n"),
        }
      : {}),
  };
};

const LocalEditor: Template<TemplateRenderProps> = () => {
  return (
    <LocalEditorShell
      apiBasePath="/__yext_visual_editor/local-editor"
      routePath={DEFAULT_LOCAL_EDITOR_ROUTE}
      componentRegistry={componentRegistry}
      tailwindConfig={tailwindConfig}
      themeConfig={defaultThemeConfig}
    />
  );
};

export default LocalEditor;
