/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */
import "@yext/visual-editor/style.css";
import "../index.css";
import {
  Template,
  GetPath,
  TemplateProps,
  TemplateRenderProps,
  GetHeadConfig,
  HeadConfig,
  TagType,
} from "@yext/pages";
import { Render } from "@measured/puck";
import {
  applyTheme,
  VisualEditorProvider,
  getPageMetadata,
  applyAnalytics,
  applyHeaderScript,
  migrate,
  migrationRegistry,
  filterComponentsFromConfig,
  resolveUrlTemplate,
  defaultThemeConfig,
  mainConfig,
} from "@yext/visual-editor";
import { AnalyticsProvider, SchemaWrapper } from "@yext/pages-components";

export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = ({
  document,
}): HeadConfig => {
  const { title, description } = getPageMetadata(document);
  const faviconUrl = document?._favicon ?? document?._site?.favicon?.url;

  return {
    title: title,
    charset: "UTF-8",
    viewport: "width=device-width, initial-scale=1",
    tags: [
      {
        type: "link",
        attributes: {
          rel: "icon",
          type: "image/x-icon",
        },
      },
      ...(description
        ? [
            {
              type: "meta" as TagType,
              attributes: {
                name: "description",
                content: description,
              },
            },
          ]
        : []),
      ...(faviconUrl
        ? [
            {
              type: "link" as TagType,
              attributes: {
                rel: "icon",
                type: "image/x-icon",
                href: faviconUrl,
              },
            },
          ]
        : []),
    ],
    other: (() => {
      const analytics = applyAnalytics(document);
      const headerScript = applyHeaderScript(document);
      const theme = applyTheme(document, defaultThemeConfig);
      const schema = SchemaWrapper(document._schema);
      const result = [analytics, headerScript, theme, schema].join("\n");
      console.log("🔵 getHeadConfig other field length:", result.length);
      console.log(
        "🔵 getHeadConfig other field includes Google Fonts:",
        result.includes("fonts.googleapis.com")
      );
      console.log(
        "🔵 getHeadConfig other field preview:",
        result.substring(0, 300) + "..."
      );
      return result;
    })(),
  };
};

export const getPath: GetPath<TemplateProps> = ({
  document,
  relativePrefixToRoot,
}) => {
  return resolveUrlTemplate(document, relativePrefixToRoot);
};

const Location: Template<TemplateRenderProps> = (props) => {
  const { document } = props;
  const filteredConfig = filterComponentsFromConfig(
    mainConfig,
    document?._additionalLayoutComponents,
    document?._additionalLayoutCategories
  );

  return (
    <AnalyticsProvider
      apiKey={document?._env?.YEXT_PUBLIC_VISUAL_EDITOR_APP_API_KEY}
      templateData={props}
      currency="USD"
    >
      <VisualEditorProvider templateProps={props}>
        <Render
          config={filteredConfig}
          data={migrate(
            JSON.parse(document.__.layout),
            migrationRegistry,
            filteredConfig
          )}
        />
      </VisualEditorProvider>
    </AnalyticsProvider>
  );
};

export default Location;
