export const PageSectionCategory = [
  "AboutSection",
  "BannerSection",
  "BreadcrumbsSection",
  "CoreInfoSection",
  "EventSection",
  "FAQSection",
  "HeroSection",
  "InsightSection",
  "NearbyLocationsSection",
  "PhotoGallerySection",
  "ProductSection",
  "ProfessionalHeroSection",
  "PromoSection",
  "ReviewsSection",
  "StaticMapSection",
  "TeamSection",
  "TestimonialSection",
  "VideoSection",
] as const;
