export const verticalPaddingClasses = [
  { label: "0", value: "py-0" },
  { label: "0.5", value: "py-0.5" },
  { label: "1", value: "py-1" },
  { label: "1.5", value: "py-1.5" },
  { label: "2", value: "py-2" },
  { label: "2.5", value: "py-2.5" },
  { label: "3", value: "py-3" },
  { label: "3.5", value: "py-3.5" },
  { label: "4", value: "py-4" },
  { label: "5", value: "py-5" },
  { label: "6", value: "py-6" },
  { label: "7", value: "py-7" },
  { label: "8", value: "py-8" },
  { label: "9", value: "py-9" },
  { label: "10", value: "py-10" },
  { label: "11", value: "py-11" },
  { label: "12", value: "py-12" },
  { label: "14", value: "py-14" },
  { label: "16", value: "py-16" },
  { label: "20", value: "py-20" },
  { label: "24", value: "py-24" },
];

export const horizontalPaddingClasses = [
  { label: "0", value: "px-0" },
  { label: "0.5", value: "px-0.5" },
  { label: "1", value: "px-1" },
  { label: "1.5", value: "px-1.5" },
  { label: "2", value: "px-2" },
  { label: "2.5", value: "px-2.5" },
  { label: "3", value: "px-3" },
  { label: "3.5", value: "px-3.5" },
  { label: "4", value: "px-4" },
  { label: "5", value: "px-5" },
  { label: "6", value: "px-6" },
  { label: "7", value: "px-7" },
  { label: "8", value: "px-8" },
  { label: "9", value: "px-9" },
  { label: "10", value: "px-10" },
  { label: "11", value: "px-11" },
  { label: "12", value: "px-12" },
  { label: "14", value: "px-14" },
  { label: "16", value: "px-16" },
  { label: "20", value: "px-20" },
  { label: "24", value: "px-24" },
];
