import path from "node:path";
import fs from "fs-extra";
import editTemplate from "./templates/edit.tsx?raw";
import editDevEntryTemplate from "./templates/editDevEntry.tsx?raw";
import {
  getEditorTemplateFilePath,
  getEditorTemplateInfosFromTemplateNames,
  isManagedEditorTemplateFileName,
  injectEditorTemplateInfo,
  type EditorTemplateInfo,
} from "./editorRoute.ts";
import {
  getEditorDevEntryTemplateInfoFromTemplateNames,
  injectEditorDevEntryTemplateInfo,
  type EditorDevEntryTemplateInfo,
} from "./editorDevMode.ts";
import { isAutogeneratedTemplateFile } from "./generatedTemplateFiles.ts";
import { writeFileIfChanged } from "./writeFileIfChanged.ts";

const GENERATED_EDIT_LOCAL_DATA_HASH = "cfcd208495d565ef66e7dff9f98764da";
const GENERATED_EDIT_LOCAL_DATA_LOCALE = "en";
const GENERATED_EDIT_LOCAL_DATA_PREFIX =
  "cog-internal-feature-static-file-generation-";

type GeneratedFileTracker = (filePath: string) => void;

type SyncGeneratedEditorFilesOptions = {
  rootDir: string;
  availableTemplateNames: string[];
  isBuildMode: boolean;
  trackFileForCleanup: GeneratedFileTracker;
};

const getGeneratedEditLocalDataFilename = (configName: string): string => {
  return `${GENERATED_EDIT_LOCAL_DATA_PREFIX}${configName}__${GENERATED_EDIT_LOCAL_DATA_LOCALE}__${GENERATED_EDIT_LOCAL_DATA_HASH}.json`;
};

const writeGeneratedEditLocalDataFile = (
  filePath: string,
  configName: string
) => {
  writeFileIfChanged(
    filePath,
    `${JSON.stringify(
      {
        __: {
          name: configName,
          staticPage: {},
        },
        _site: {},
        businessId: 0,
        locale: GENERATED_EDIT_LOCAL_DATA_LOCALE,
        meta: {
          locale: GENERATED_EDIT_LOCAL_DATA_LOCALE,
        },
        siteDomain: "",
        siteId: 0,
        siteInternalHostName: "",
      },
      null,
      2
    )}\n`
  );
};

const syncGeneratedEditLocalData = (
  rootDir: string,
  configNames: string[],
  trackFileForCleanup: GeneratedFileTracker
) => {
  const localDataDir = path.join(rootDir, "localData");
  const expectedFileNames = new Set(
    configNames.map(getGeneratedEditLocalDataFilename)
  );

  if (expectedFileNames.size > 0) {
    fs.ensureDirSync(localDataDir);
  }

  if (fs.existsSync(localDataDir)) {
    for (const entry of fs.readdirSync(localDataDir, {
      withFileTypes: true,
    })) {
      if (!entry.isFile()) {
        continue;
      }

      const isGeneratedEditLocalData =
        entry.name.startsWith(`${GENERATED_EDIT_LOCAL_DATA_PREFIX}edit`) &&
        entry.name.endsWith(".json");
      if (!isGeneratedEditLocalData || expectedFileNames.has(entry.name)) {
        continue;
      }

      fs.removeSync(path.join(localDataDir, entry.name));
    }
  }

  for (const configName of configNames) {
    const filePath = path.join(
      localDataDir,
      getGeneratedEditLocalDataFilename(configName)
    );
    writeGeneratedEditLocalDataFile(filePath, configName);
    trackFileForCleanup(filePath);
  }
};

/**
 * Keeps the dev-only `/edit` entry page aligned with the current repo shape.
 *
 * The entry page only exists when a repo has real editor pages at
 * `/edit/{templateId}`. In the legacy `main` case, `src/templates/edit.tsx`
 * remains the real editor template instead.
 */
const syncEditDevEntryTemplate = (
  rootDir: string,
  entryTemplateInfo: EditorDevEntryTemplateInfo | null,
  trackFileForCleanup: GeneratedFileTracker,
  options?: {
    preserveExistingEditTemplate?: boolean;
  }
) => {
  const entryTemplatePath = path.join(rootDir, "src", "templates", "edit.tsx");

  if (!entryTemplateInfo) {
    if (options?.preserveExistingEditTemplate) {
      return;
    }

    if (isAutogeneratedTemplateFile(entryTemplatePath)) {
      fs.removeSync(entryTemplatePath);
    }
    return;
  }

  fs.mkdirSync(path.dirname(entryTemplatePath), { recursive: true });

  if (
    fs.existsSync(entryTemplatePath) &&
    !isAutogeneratedTemplateFile(entryTemplatePath)
  ) {
    throw new Error(
      `Refusing to overwrite hand-authored edit entry template at ${entryTemplatePath}`
    );
  }

  writeFileIfChanged(
    entryTemplatePath,
    injectEditorDevEntryTemplateInfo(editDevEntryTemplate, entryTemplateInfo)
  );
  trackFileForCleanup(entryTemplatePath);
};

/**
 * Syncs the real editor templates that render the editor shell itself.
 *
 * In a legacy repo this is just `src/templates/edit.tsx`. In a custom-only
 * repo this becomes one generated template per custom template id.
 */
const syncEditorInstanceTemplates = (
  rootDir: string,
  availableTemplateNames: string[],
  trackFileForCleanup: GeneratedFileTracker,
  additionalManagedTemplatePathsToPreserve: string[] = []
): EditorTemplateInfo[] => {
  const desiredEditorTemplateInfos = getEditorTemplateInfosFromTemplateNames(
    availableTemplateNames
  );
  const desiredTemplatePaths = new Set([
    ...desiredEditorTemplateInfos.map((editorTemplateInfo) =>
      path.join(rootDir, getEditorTemplateFilePath(editorTemplateInfo))
    ),
    ...additionalManagedTemplatePathsToPreserve.map((templatePath) =>
      path.join(rootDir, templatePath)
    ),
  ]);
  const templatesDirectory = path.join(rootDir, "src", "templates");
  fs.ensureDirSync(templatesDirectory);

  if (fs.existsSync(templatesDirectory)) {
    for (const entry of fs.readdirSync(templatesDirectory, {
      withFileTypes: true,
    })) {
      if (!entry.isFile() || path.extname(entry.name) !== ".tsx") {
        continue;
      }

      const templateName = entry.name.replace(/\.tsx$/, "");
      if (!isManagedEditorTemplateFileName(templateName)) {
        continue;
      }

      const templatePath = path.join(templatesDirectory, entry.name);
      if (desiredTemplatePaths.has(templatePath)) {
        continue;
      }

      if (isAutogeneratedTemplateFile(templatePath)) {
        fs.removeSync(templatePath);
      }
    }
  }

  for (const editorTemplateInfo of desiredEditorTemplateInfos) {
    const editorTemplatePath = path.join(
      rootDir,
      getEditorTemplateFilePath(editorTemplateInfo)
    );
    const desiredTemplateSource = injectEditorTemplateInfo(
      editTemplate,
      editorTemplateInfo
    );
    fs.mkdirSync(path.dirname(editorTemplatePath), { recursive: true });

    if (
      fs.existsSync(editorTemplatePath) &&
      !isAutogeneratedTemplateFile(editorTemplatePath)
    ) {
      throw new Error(
        `Refusing to overwrite hand-authored editor template at ${editorTemplatePath}`
      );
    }

    const shouldRewriteExistingTemplate =
      fs.existsSync(editorTemplatePath) &&
      isAutogeneratedTemplateFile(editorTemplatePath) &&
      !fs
        .readFileSync(editorTemplatePath, "utf8")
        .includes("componentRegistry");

    if (!fs.existsSync(editorTemplatePath) || shouldRewriteExistingTemplate) {
      writeFileIfChanged(editorTemplatePath, desiredTemplateSource);
    }

    trackFileForCleanup(editorTemplatePath);
  }

  return desiredEditorTemplateInfos;
};

/**
 * Generates the editor-facing files managed by the plugin itself:
 * - the real editor templates
 * - the dev-only `/edit` entry page
 * - the localData stubs that let Pages dev resolve those routes locally
 */
export const syncGeneratedEditorFiles = ({
  rootDir,
  availableTemplateNames,
  isBuildMode,
  trackFileForCleanup,
}: SyncGeneratedEditorFilesOptions): EditorTemplateInfo[] => {
  const entryTemplateInfo = isBuildMode
    ? null
    : getEditorDevEntryTemplateInfoFromTemplateNames(availableTemplateNames);
  const editorTemplateInfos = syncEditorInstanceTemplates(
    rootDir,
    availableTemplateNames,
    trackFileForCleanup,
    entryTemplateInfo ? ["src/templates/edit.tsx"] : []
  );

  syncEditDevEntryTemplate(
    rootDir,
    editorTemplateInfos.some(
      (editorTemplateInfo) => editorTemplateInfo.configName !== "edit"
    )
      ? entryTemplateInfo
      : null,
    trackFileForCleanup,
    {
      preserveExistingEditTemplate: editorTemplateInfos.some(
        (editorTemplateInfo) => editorTemplateInfo.configName === "edit"
      ),
    }
  );

  syncGeneratedEditLocalData(
    rootDir,
    isBuildMode
      ? []
      : Array.from(
          new Set([
            ...editorTemplateInfos.map(
              (editorTemplateInfo) => editorTemplateInfo.configName
            ),
            ...(entryTemplateInfo ? [entryTemplateInfo.configName] : []),
          ])
        ),
    trackFileForCleanup
  );

  return editorTemplateInfos;
};
