import path from "node:path";
import { pathToFileURL } from "node:url";
import fs from "fs-extra";
import { tsImport } from "tsx/esm/api";
import { YextSchemaField } from "../types/entityFields.ts";
import { buildLocalEditorScaffoldSource } from "./localEditorScaffold.ts";

export const DEFAULT_LOCAL_EDITOR_ROUTE = "/local-editor";
export const DEFAULT_LOCAL_EDITOR_STREAM_CONFIG_PATH = "stream.config.ts";
export const DEFAULT_LOCAL_EDITOR_STREAM_PATH = "stream.ts";
export const LEGACY_LOCAL_EDITOR_STREAM_CONFIG_PATH =
  "local-editor/stream.json";
export const LOCAL_EDITOR_API_BASE_PATH = "/__yext_visual_editor/local-editor";
export const LOCAL_EDITOR_DATA_TEMPLATE_PREFIX = "local-editor-data-";
export const LEGACY_LOCAL_EDITOR_DATA_TEMPLATE_PATH =
  "src/templates/local-editor-data.tsx";
export const GENERATED_LOCAL_EDITOR_TEMPLATE_PREFIX =
  "/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */";

type TemplateManifestEntry = {
  name: string;
  defaultLayoutData?: unknown;
};

type TemplateManifestFile = {
  templates?: TemplateManifestEntry[];
};

type LocalEditorDefaults = {
  templateId?: string;
  locale?: string;
  entityId?: string;
};

export type LocalEditorStreamField =
  | string
  | {
      name: string;
      fullObject?: boolean;
    };

export type LocalEditorStreamDefinition = {
  fields?: LocalEditorStreamField[];
} & Record<string, unknown>;

export type LocalEditorPagesStream = {
  $id?: string;
  fields: string[];
  filter?: {
    entityIds?: string[];
    entityTypes?: string[];
    savedFilterIds?: string[];
  };
  localization?: {
    locales?: string[];
    primary?: true;
  };
  transform?: {
    expandOptionFields?: string[];
    replaceOptionValuesWithDisplayNames?: string[];
  };
  includeCertifiedFacts?: boolean;
};

export type LocalEditorTemplateConfig = {
  defaults?: Omit<LocalEditorDefaults, "templateId">;
  stream?: LocalEditorStreamDefinition;
};

export type LocalEditorConfig = {
  defaults?: LocalEditorDefaults;
  templates?: Record<string, LocalEditorTemplateConfig>;
};

type LegacyLocalEditorConfig = {
  templateIds?: string[];
  defaults?: LocalEditorDefaults;
  stream?: LocalEditorStreamDefinition;
};

type SupportedLocalEditorConfig = LocalEditorConfig | LegacyLocalEditorConfig;

type ResolvedLocalEditorTemplateConfig = {
  templateId: string;
  dataTemplateName: string;
  defaults: Omit<LocalEditorDefaults, "templateId">;
  stream?: LocalEditorStreamDefinition;
  defaultLayoutData?: unknown;
};

type LocalEditorDocumentIndexEntry = {
  templateId: string;
  entityId: string;
  displayName: string;
  locale: string;
  filePath: string;
  fileName: string;
};

type LocalEditorEntityOption = {
  entityId: string;
  displayName: string;
  locales: string[];
};

export type LocalEditorManifestResponse = {
  templates: string[];
  entitiesByTemplate: Record<string, LocalEditorEntityOption[]>;
  templateDefaults: Record<
    string,
    {
      entityId?: string;
      locale?: string;
      defaultLayoutData?: unknown;
    }
  >;
  defaults: {
    templateId?: string;
    entityId?: string;
    locale?: string;
  };
  diagnostics: string[];
  streamConfigPath: string;
  localDataPath: string;
};

export type LocalEditorDocumentResponse = {
  document: Record<string, unknown> | null;
  entityFields: {
    fields: YextSchemaField[];
    displayNames: Record<string, string>;
  };
  diagnostics: string[];
};

type LocalEditorContext = {
  diagnostics: string[];
  streamConfigPath: string;
  localDataPath: string;
  templates: string[];
  defaults: LocalEditorDefaults;
  templateDefaults: Record<
    string,
    {
      entityId?: string;
      locale?: string;
      defaultLayoutData?: unknown;
    }
  >;
  templateStreams: Record<string, LocalEditorStreamDefinition | undefined>;
  entitiesByTemplate: Record<string, LocalEditorEntityOption[]>;
  documents: LocalEditorDocumentIndexEntry[];
};

type ResolvedLocalEditorConfig = {
  defaults: LocalEditorDefaults;
  templates: ResolvedLocalEditorTemplateConfig[];
};

export const normalizeLocalEditorRoute = (route?: string): string => {
  if (!route) {
    return DEFAULT_LOCAL_EDITOR_ROUTE;
  }

  const trimmedRoute = route.trim();
  if (!trimmedRoute) {
    return DEFAULT_LOCAL_EDITOR_ROUTE;
  }

  const normalizedRoute = `/${trimmedRoute.replace(/^\/+/, "").replace(/\/+$/, "")}`;
  return normalizedRoute === "/" ? DEFAULT_LOCAL_EDITOR_ROUTE : normalizedRoute;
};

export const toTemplatePathSegment = (route: string): string => {
  return normalizeLocalEditorRoute(route).replace(/^\/+/, "");
};

export const buildLocalEditorDataTemplateName = (
  templateId: string
): string => {
  const normalizedTemplateSegment = templateId
    .trim()
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  return `${LOCAL_EDITOR_DATA_TEMPLATE_PREFIX}${normalizedTemplateSegment || "template"}`;
};

export const buildLocalEditorDataTemplatePath = (
  templateId: string
): string => {
  return path.join(
    "src",
    "templates",
    `${buildLocalEditorDataTemplateName(templateId)}.tsx`
  );
};

export const buildLocalEditorTemplateSource = (
  templateSource: string,
  route: string
): string => {
  return templateSource.replaceAll(
    '"__LOCAL_EDITOR_ROUTE__"',
    JSON.stringify(toTemplatePathSegment(route))
  );
};

export const buildLocalEditorDataTemplateSource = (
  templateSource: string,
  streamConfigImportPath: string,
  templateId: string
): string => {
  return templateSource
    .replaceAll(
      '"__LOCAL_EDITOR_STREAM_CONFIG_IMPORT__"',
      JSON.stringify(streamConfigImportPath)
    )
    .replaceAll('"__LOCAL_EDITOR_TEMPLATE_ID__"', JSON.stringify(templateId))
    .replaceAll(
      '"__LOCAL_EDITOR_DATA_TEMPLATE_NAME__"',
      JSON.stringify(buildLocalEditorDataTemplateName(templateId))
    );
};

export const normalizeLocalEditorPagesStream = (
  stream?: LocalEditorStreamDefinition
): LocalEditorPagesStream | undefined => {
  if (!stream) {
    return undefined;
  }

  const normalizedFields = (stream.fields ?? [])
    .map((field) => {
      return typeof field === "string" ? field : field.name;
    })
    .filter((fieldName): fieldName is string => {
      return !!fieldName && fieldName !== "locale";
    })
    .filter((fieldName, index, values) => {
      return values.indexOf(fieldName) === index;
    });

  return {
    ...stream,
    fields: normalizedFields,
  };
};

export const isGeneratedLocalEditorTemplate = (
  templatePath: string
): boolean => {
  if (!fs.existsSync(templatePath)) {
    return false;
  }

  const fileContents = fs.readFileSync(templatePath, "utf8");
  return fileContents.startsWith(GENERATED_LOCAL_EDITOR_TEMPLATE_PREFIX);
};

export const resolveLocalEditorStreamConfigPath = async (
  rootDir: string,
  configuredPath?: string
): Promise<string> => {
  if (configuredPath) {
    return configuredPath;
  }

  for (const candidatePath of [
    DEFAULT_LOCAL_EDITOR_STREAM_CONFIG_PATH,
    DEFAULT_LOCAL_EDITOR_STREAM_PATH,
    LEGACY_LOCAL_EDITOR_STREAM_CONFIG_PATH,
  ]) {
    if (fs.existsSync(path.join(rootDir, candidatePath))) {
      return candidatePath;
    }
  }

  return DEFAULT_LOCAL_EDITOR_STREAM_CONFIG_PATH;
};

export const ensureLocalEditorStreamConfig = async (
  rootDir: string,
  streamConfigPath: string
): Promise<void> => {
  const absoluteStreamConfigPath = path.join(rootDir, streamConfigPath);
  if (fs.existsSync(absoluteStreamConfigPath)) {
    return;
  }

  if (streamConfigPath !== DEFAULT_LOCAL_EDITOR_STREAM_CONFIG_PATH) {
    return;
  }

  fs.ensureDirSync(path.dirname(absoluteStreamConfigPath));
  fs.writeFileSync(
    absoluteStreamConfigPath,
    buildLocalEditorScaffoldSource(rootDir)
  );
};

export const getLocalEditorManifest = async (
  rootDir: string,
  streamConfigPath = DEFAULT_LOCAL_EDITOR_STREAM_CONFIG_PATH
): Promise<LocalEditorManifestResponse> => {
  const context = await getLocalEditorContext(rootDir, streamConfigPath);
  const selectedTemplateId =
    context.defaults.templateId ?? context.templates[0];
  const selectedTemplateDefaults = selectedTemplateId
    ? context.templateDefaults[selectedTemplateId]
    : undefined;
  const selectedTemplateEntities = selectedTemplateId
    ? (context.entitiesByTemplate[selectedTemplateId] ?? [])
    : [];

  return {
    templates: context.templates,
    entitiesByTemplate: context.entitiesByTemplate,
    templateDefaults: context.templateDefaults,
    defaults: {
      templateId: selectedTemplateId,
      entityId:
        selectedTemplateDefaults?.entityId ??
        context.defaults.entityId ??
        selectedTemplateEntities[0]?.entityId,
      locale:
        selectedTemplateDefaults?.locale ??
        context.defaults.locale ??
        selectedTemplateEntities[0]?.locales[0],
    },
    diagnostics: context.diagnostics,
    streamConfigPath: context.streamConfigPath,
    localDataPath: context.localDataPath,
  };
};

export const getLocalEditorDocument = async (
  rootDir: string,
  streamConfigPath: string,
  templateId?: string,
  entityId?: string,
  locale?: string
): Promise<LocalEditorDocumentResponse> => {
  const context = await getLocalEditorContext(rootDir, streamConfigPath);
  const selectedTemplateId =
    templateId ?? context.defaults.templateId ?? context.templates[0];
  const entityOptions = selectedTemplateId
    ? (context.entitiesByTemplate[selectedTemplateId] ?? [])
    : [];
  const selectedTemplateDefaults = selectedTemplateId
    ? context.templateDefaults[selectedTemplateId]
    : undefined;
  const selectedEntityId =
    entityId ??
    selectedTemplateDefaults?.entityId ??
    context.defaults.entityId ??
    entityOptions[0]?.entityId;
  const selectedEntity = entityOptions.find((entityOption) => {
    return entityOption.entityId === selectedEntityId;
  });
  const selectedLocale =
    locale ??
    selectedTemplateDefaults?.locale ??
    context.defaults.locale ??
    selectedEntity?.locales[0];

  const selectedDocumentEntry = context.documents.find((documentEntry) => {
    return (
      documentEntry.templateId === selectedTemplateId &&
      documentEntry.entityId === selectedEntityId &&
      documentEntry.locale === selectedLocale
    );
  });

  if (!selectedDocumentEntry) {
    return {
      document: null,
      entityFields: {
        fields: [],
        displayNames: {},
      },
      diagnostics: context.diagnostics,
    };
  }

  const document = readJsonFile<Record<string, unknown>>(
    selectedDocumentEntry.filePath,
    `local editor snapshot ${selectedDocumentEntry.fileName}`
  );
  const entityFields = inferEntityFields(
    document,
    context.templateStreams[selectedDocumentEntry.templateId]
  );

  return {
    document,
    entityFields,
    diagnostics: context.diagnostics,
  };
};

export const inferEntityFields = (
  document: Record<string, unknown>,
  stream?: LocalEditorStreamDefinition
): {
  fields: YextSchemaField[];
  displayNames: Record<string, string>;
} => {
  const configuredDisplayNames = buildConfiguredDisplayNames(stream);
  const rootNodes = new Map<string, MutableFieldNode>();

  for (const [key, value] of Object.entries(document)) {
    if (shouldSkipField(key)) {
      continue;
    }

    mergeFieldNode(rootNodes, inferFieldNode(key, value));
  }

  const fields = Array.from(rootNodes.values())
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((node) => {
      return toSchemaField(node, configuredDisplayNames, node.name);
    });

  return {
    fields,
    displayNames: configuredDisplayNames,
  };
};

const getLocalEditorContext = async (
  rootDir: string,
  streamConfigPath = DEFAULT_LOCAL_EDITOR_STREAM_CONFIG_PATH
): Promise<LocalEditorContext> => {
  const diagnostics: string[] = [];
  const localDataPath = path.join(rootDir, "localData");
  const templateManifestEntries = readTemplateManifestEntries(
    rootDir,
    diagnostics
  );
  const resolvedConfig = await readResolvedTemplateConfigs(
    rootDir,
    streamConfigPath,
    templateManifestEntries,
    diagnostics
  );
  const templateConfigs = resolvedConfig.templates;
  const templates = templateConfigs.map(
    (templateConfig) => templateConfig.templateId
  );
  const documents = readLocalEditorDocuments(
    localDataPath,
    templateConfigs,
    diagnostics
  );
  const entitiesByTemplate = buildEntitiesByTemplate(templates, documents);
  const templateDefaults = Object.fromEntries(
    templateConfigs.map((templateConfig) => {
      return [
        templateConfig.templateId,
        {
          entityId: templateConfig.defaults.entityId,
          locale: templateConfig.defaults.locale,
          defaultLayoutData: templateConfig.defaultLayoutData,
        },
      ];
    })
  );
  const templateStreams = Object.fromEntries(
    templateConfigs.map((templateConfig) => {
      return [templateConfig.templateId, templateConfig.stream];
    })
  );
  const defaultTemplateId =
    templateConfigs.find((templateConfig) => {
      return templateConfig.templateId === resolvedConfig.defaults.templateId;
    })?.templateId ?? templateConfigs[0]?.templateId;

  return {
    diagnostics,
    streamConfigPath,
    localDataPath: "localData",
    templates,
    defaults: {
      templateId: defaultTemplateId,
      entityId: resolvedConfig.defaults.entityId,
      locale: resolvedConfig.defaults.locale,
    },
    templateDefaults,
    templateStreams,
    entitiesByTemplate,
    documents,
  };
};

const readResolvedTemplateConfigs = async (
  rootDir: string,
  streamConfigPath: string,
  templateManifestEntries: TemplateManifestEntry[],
  diagnostics: string[]
): Promise<ResolvedLocalEditorConfig> => {
  const absoluteStreamConfigPath = path.join(rootDir, streamConfigPath);
  if (!fs.existsSync(absoluteStreamConfigPath)) {
    diagnostics.push(
      `Missing local editor config at ${path.relative(process.cwd(), absoluteStreamConfigPath)}. Create this file to configure templates and snapshot defaults.`
    );
    return {
      defaults: {},
      templates: templateManifestEntries.map((templateEntry) => {
        return {
          templateId: templateEntry.name,
          dataTemplateName: buildLocalEditorDataTemplateName(
            templateEntry.name
          ),
          defaults: {},
          defaultLayoutData: normalizeDefaultLayoutData(
            templateEntry.defaultLayoutData
          ),
        };
      }),
    };
  }

  let streamConfig: SupportedLocalEditorConfig | undefined;
  try {
    streamConfig = await loadLocalEditorConfig(absoluteStreamConfigPath);
  } catch (error) {
    diagnostics.push(toErrorMessage(error));
    return {
      defaults: {},
      templates: [],
    };
  }

  return buildResolvedTemplateConfigs(templateManifestEntries, streamConfig);
};

const buildResolvedTemplateConfigs = (
  templateManifestEntries: TemplateManifestEntry[],
  streamConfig: SupportedLocalEditorConfig
): ResolvedLocalEditorConfig => {
  if (
    isTemplateAwareLocalEditorConfig(streamConfig) &&
    streamConfig.templates
  ) {
    return buildTemplateAwareResolvedConfig(
      templateManifestEntries,
      streamConfig
    );
  }

  return buildLegacyResolvedConfig(
    templateManifestEntries,
    streamConfig as LegacyLocalEditorConfig
  );
};

const loadLocalEditorConfig = async (
  absoluteStreamConfigPath: string
): Promise<SupportedLocalEditorConfig> => {
  const extension = path.extname(absoluteStreamConfigPath);
  if (extension === ".json") {
    return loadJsonLocalEditorConfig(absoluteStreamConfigPath);
  }

  return loadTypeScriptLocalEditorConfig(absoluteStreamConfigPath);
};

const loadJsonLocalEditorConfig = (
  absoluteStreamConfigPath: string
): SupportedLocalEditorConfig => {
  return readJsonFile<SupportedLocalEditorConfig>(
    absoluteStreamConfigPath,
    "local editor stream config"
  );
};

const loadTypeScriptLocalEditorConfig = async (
  absoluteStreamConfigPath: string
): Promise<SupportedLocalEditorConfig> => {
  const cacheBypassPath = buildLocalEditorConfigCacheBypassPath(
    absoluteStreamConfigPath
  );
  fs.copyFileSync(absoluteStreamConfigPath, cacheBypassPath);

  try {
    const importedModule = await tsImport(
      pathToFileURL(cacheBypassPath).href,
      import.meta.url
    );
    return validateLoadedLocalEditorConfig(
      absoluteStreamConfigPath,
      unwrapDefaultExport(importedModule)
    );
  } finally {
    fs.removeSync(cacheBypassPath);
  }
};

const validateLoadedLocalEditorConfig = (
  absoluteStreamConfigPath: string,
  loadedConfig: unknown
): SupportedLocalEditorConfig => {
  if (!loadedConfig || typeof loadedConfig !== "object") {
    throw new Error(
      `Failed to parse local editor stream config at ${path.relative(process.cwd(), absoluteStreamConfigPath)}: expected a default-exported object`
    );
  }

  return loadedConfig as SupportedLocalEditorConfig;
};

const buildTemplateAwareResolvedConfig = (
  templateManifestEntries: TemplateManifestEntry[],
  streamConfig: LocalEditorConfig
): ResolvedLocalEditorConfig => {
  const manifestTemplates = getManifestTemplateIds(templateManifestEntries);
  const templateEntryMap = createTemplateEntryMap(templateManifestEntries);
  const orderedTemplateIds = [
    ...manifestTemplates.filter((templateId) => {
      return !!streamConfig.templates?.[templateId];
    }),
    ...Object.keys(streamConfig.templates ?? {}).filter((templateId) => {
      return !manifestTemplates.includes(templateId);
    }),
  ];

  const activeTemplateConfigs = orderedTemplateIds.flatMap((templateId) => {
    const templateConfig = streamConfig.templates?.[templateId] ?? {};
    if (!templateConfig.stream) {
      return [];
    }

    return [
      buildResolvedTemplateConfig({
        templateId,
        defaults: {
          entityId: templateConfig.defaults?.entityId,
          locale:
            templateConfig.defaults?.locale ?? streamConfig.defaults?.locale,
        },
        stream: templateConfig.stream,
        templateEntryMap,
      }),
    ];
  });

  return {
    defaults: {
      templateId: streamConfig.defaults?.templateId,
      entityId: streamConfig.defaults?.entityId,
      locale: streamConfig.defaults?.locale,
    },
    templates: activeTemplateConfigs,
  };
};

const buildLegacyResolvedConfig = (
  templateManifestEntries: TemplateManifestEntry[],
  legacyStreamConfig: LegacyLocalEditorConfig
): ResolvedLocalEditorConfig => {
  const manifestTemplates = getManifestTemplateIds(templateManifestEntries);
  const templateEntryMap = createTemplateEntryMap(templateManifestEntries);
  const legacyTemplateIds = (
    legacyStreamConfig.templateIds?.length
      ? legacyStreamConfig.templateIds
      : manifestTemplates
  ).filter((templateId, index, values) => {
    return values.indexOf(templateId) === index;
  });

  return {
    defaults: {
      templateId: legacyStreamConfig.defaults?.templateId,
      entityId: legacyStreamConfig.defaults?.entityId,
      locale: legacyStreamConfig.defaults?.locale,
    },
    templates: legacyTemplateIds.map((templateId) => {
      return buildResolvedTemplateConfig({
        templateId,
        defaults: {
          entityId: legacyStreamConfig.defaults?.entityId,
          locale: legacyStreamConfig.defaults?.locale,
        },
        stream: legacyStreamConfig.stream,
        templateEntryMap,
      });
    }),
  };
};

const buildResolvedTemplateConfig = ({
  templateId,
  defaults,
  stream,
  templateEntryMap,
}: {
  templateId: string;
  defaults: Omit<LocalEditorDefaults, "templateId">;
  stream?: LocalEditorStreamDefinition;
  templateEntryMap: Map<string, TemplateManifestEntry>;
}): ResolvedLocalEditorTemplateConfig => {
  return {
    templateId,
    dataTemplateName: buildLocalEditorDataTemplateName(templateId),
    defaults,
    stream,
    defaultLayoutData: normalizeDefaultLayoutData(
      templateEntryMap.get(templateId)?.defaultLayoutData
    ),
  };
};

const getManifestTemplateIds = (
  templateManifestEntries: TemplateManifestEntry[]
): string[] => {
  return templateManifestEntries.map((templateEntry) => {
    return templateEntry.name;
  });
};

const createTemplateEntryMap = (
  templateManifestEntries: TemplateManifestEntry[]
): Map<string, TemplateManifestEntry> => {
  return new Map(
    templateManifestEntries.map((templateEntry) => {
      return [templateEntry.name, templateEntry];
    })
  );
};

const readTemplateManifestEntries = (
  rootDir: string,
  diagnostics: string[]
): TemplateManifestEntry[] => {
  const manifestPath = path.join(rootDir, ".template-manifest.json");
  if (!fs.existsSync(manifestPath)) {
    diagnostics.push(
      "Missing .template-manifest.json. Start the Vite dev server with the Visual Editor plugin enabled to generate template metadata."
    );
    return [];
  }

  const manifest = readJsonFile<TemplateManifestFile>(
    manifestPath,
    "template manifest"
  );
  return (manifest.templates ?? []).map((templateEntry) => {
    return {
      name: templateEntry.name,
      defaultLayoutData: templateEntry.defaultLayoutData,
    };
  });
};

const readLocalEditorDocuments = (
  localDataPath: string,
  templateConfigs: ResolvedLocalEditorTemplateConfig[],
  diagnostics: string[]
): LocalEditorDocumentIndexEntry[] => {
  if (!fs.existsSync(localDataPath)) {
    diagnostics.push(
      `Missing localData snapshots at ${path.relative(process.cwd(), localDataPath)}. Run your existing Pages local data generation flow first.`
    );
    return [];
  }

  const mappingPath = path.join(localDataPath, "mapping.json");
  if (!fs.existsSync(mappingPath)) {
    diagnostics.push(
      `Missing local editor snapshot mapping at ${path.relative(process.cwd(), mappingPath)}. Run yext pages generate-test-data to populate local editor snapshots.`
    );
    return [];
  }

  let mapping: Record<string, string[]>;
  try {
    mapping = readJsonFile<Record<string, string[]>>(
      mappingPath,
      "local data mapping"
    );
  } catch (error) {
    diagnostics.push(toErrorMessage(error));
    return [];
  }

  const documents: LocalEditorDocumentIndexEntry[] = [];

  for (const templateConfig of templateConfigs) {
    const referencedFileNames = new Set(
      mapping[templateConfig.dataTemplateName] ?? []
    );
    if (referencedFileNames.size === 0) {
      diagnostics.push(
        `Missing local editor snapshot mapping for template "${templateConfig.templateId}" in ${path.relative(process.cwd(), mappingPath)}. Expected generated mapping key "${templateConfig.dataTemplateName}". Run yext pages generate-test-data after enabling localEditor.`
      );
      continue;
    }

    Array.from(referencedFileNames)
      .sort((left, right) => left.localeCompare(right))
      .forEach((fileName) => {
        const filePath = path.join(localDataPath, fileName);
        if (!fs.existsSync(filePath)) {
          diagnostics.push(
            `Snapshot file ${path.join("localData", fileName)} is referenced but missing.`
          );
          return;
        }

        try {
          const document = readJsonFile<Record<string, unknown>>(
            filePath,
            `local editor snapshot ${fileName}`
          );
          const locale = getDocumentLocale(document, fileName);
          const entityId = getDocumentEntityId(document, fileName);
          documents.push({
            templateId: templateConfig.templateId,
            entityId,
            displayName:
              typeof document.name === "string" && document.name.length > 0
                ? document.name
                : entityId,
            locale,
            filePath,
            fileName,
          });
        } catch (error) {
          diagnostics.push(toErrorMessage(error));
        }
      });
  }

  return documents;
};

const buildEntitiesByTemplate = (
  templateIds: string[],
  documents: LocalEditorDocumentIndexEntry[]
): Record<string, LocalEditorEntityOption[]> => {
  const entries = Object.fromEntries(
    templateIds.map((templateId) => {
      return [templateId, buildEntityOptionsForTemplate(templateId, documents)];
    })
  );
  return entries;
};

const buildEntityOptionsForTemplate = (
  templateId: string,
  documents: LocalEditorDocumentIndexEntry[]
): LocalEditorEntityOption[] => {
  const entityMap = new Map<string, LocalEditorEntityOption>();

  for (const document of documents) {
    if (document.templateId !== templateId) {
      continue;
    }

    const existingEntity = entityMap.get(document.entityId);
    if (!existingEntity) {
      entityMap.set(document.entityId, {
        entityId: document.entityId,
        displayName: document.displayName,
        locales: [document.locale],
      });
      continue;
    }

    if (!existingEntity.locales.includes(document.locale)) {
      existingEntity.locales.push(document.locale);
      existingEntity.locales.sort((left, right) => left.localeCompare(right));
    }
  }

  return Array.from(entityMap.values()).sort((left, right) => {
    return left.displayName.localeCompare(right.displayName);
  });
};

type MutableFieldNode = {
  name: string;
  isList?: boolean;
  typeName?: string;
  typeRegistryId?: string;
  children: Map<string, MutableFieldNode>;
};

const inferFieldNode = (name: string, value: unknown): MutableFieldNode => {
  if (Array.isArray(value)) {
    const sampleValue = value.find(
      (item) => item !== null && item !== undefined
    );
    if (isPlainObject(sampleValue)) {
      const childNodes = inferObjectChildren(sampleValue);
      return {
        name,
        isList: true,
        typeRegistryId: "type.object",
        children: childNodes,
      };
    }

    return {
      name,
      isList: true,
      typeRegistryId: inferScalarType(sampleValue),
      children: new Map(),
    };
  }

  if (isPlainObject(value)) {
    return {
      name,
      typeRegistryId: "type.object",
      children: inferObjectChildren(value),
    };
  }

  return {
    name,
    typeRegistryId: inferScalarType(value),
    children: new Map(),
  };
};

const inferObjectChildren = (
  value: Record<string, unknown>
): Map<string, MutableFieldNode> => {
  const children = new Map<string, MutableFieldNode>();
  for (const [childName, childValue] of Object.entries(value)) {
    if (shouldSkipField(childName)) {
      continue;
    }

    mergeFieldNode(children, inferFieldNode(childName, childValue));
  }

  return children;
};

const mergeFieldNode = (
  target: Map<string, MutableFieldNode>,
  incoming: MutableFieldNode
) => {
  const existing = target.get(incoming.name);
  if (!existing) {
    target.set(incoming.name, incoming);
    return;
  }

  existing.isList = existing.isList || incoming.isList;
  existing.typeRegistryId = pickPreferredType(
    existing.typeRegistryId,
    incoming.typeRegistryId
  );

  for (const childNode of incoming.children.values()) {
    mergeFieldNode(existing.children, childNode);
  }
};

const toSchemaField = (
  node: MutableFieldNode,
  displayNames: Record<string, string>,
  currentPath: string
): YextSchemaField => {
  const children = Array.from(node.children.values())
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((childNode) => {
      return toSchemaField(
        childNode,
        displayNames,
        `${currentPath}.${childNode.name}`
      );
    });

  return {
    name: node.name,
    displayName: displayNames[currentPath] ?? toDisplayName(currentPath),
    definition: {
      name: node.name,
      isList: node.isList,
      typeName: node.typeName,
      typeRegistryId: node.typeRegistryId ?? "type.string",
      type: {},
    },
    children: children.length ? { fields: children } : undefined,
  };
};

const buildConfiguredDisplayNames = (
  stream?: LocalEditorStreamDefinition
): Record<string, string> => {
  const displayNames: Record<string, string> = {};

  for (const field of stream?.fields ?? []) {
    const fieldName = typeof field === "string" ? field : field.name;
    if (!fieldName) {
      continue;
    }

    const segments = fieldName.split(".");
    segments.reduce((currentPath, segment) => {
      const nextPath = currentPath ? `${currentPath}.${segment}` : segment;
      if (!displayNames[nextPath]) {
        displayNames[nextPath] = toDisplayName(nextPath);
      }
      return nextPath;
    }, "");
  }

  return displayNames;
};

const shouldSkipField = (fieldName: string): boolean => {
  return fieldName.startsWith("_");
};

const inferScalarType = (value: unknown): string => {
  if (typeof value === "boolean") {
    return "type.boolean";
  }
  if (typeof value === "number") {
    return "type.number";
  }
  if (typeof value === "string") {
    return "type.string";
  }
  return "type.string";
};

const pickPreferredType = (
  existingType?: string,
  incomingType?: string
): string | undefined => {
  if (!existingType) {
    return incomingType;
  }
  if (!incomingType) {
    return existingType;
  }
  if (existingType === "type.string" && incomingType !== "type.string") {
    return incomingType;
  }
  return existingType;
};

const getDocumentLocale = (
  document: Record<string, unknown>,
  fileName: string
): string => {
  if (typeof document.locale === "string" && document.locale.length > 0) {
    return document.locale;
  }

  const match = fileName.match(/__(.+?)__[^_]+\.json$/);
  return match?.[1] ?? "en";
};

const getDocumentEntityId = (
  document: Record<string, unknown>,
  fileName: string
): string => {
  if (
    (typeof document.id === "string" || typeof document.id === "number") &&
    String(document.id).length > 0
  ) {
    return String(document.id);
  }

  const match = fileName.match(/__([^_]+)\.json$/);
  return match?.[1] ?? fileName.replace(/\.json$/, "");
};

const toDisplayName = (pathName: string): string => {
  return pathName
    .split(".")
    .map((segment) => {
      return segment
        .replace(/[_-]+/g, " ")
        .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
        .replace(/\b\w/g, (character) => character.toUpperCase());
    })
    .join(" > ");
};

const isTemplateAwareLocalEditorConfig = (
  value: SupportedLocalEditorConfig
): value is LocalEditorConfig => {
  return "templates" in value;
};

const unwrapDefaultExport = (value: unknown): unknown => {
  let currentValue = value;

  while (isModuleWrapper(currentValue)) {
    currentValue = (currentValue as { default: unknown }).default;
  }

  return currentValue;
};

const isModuleWrapper = (
  value: unknown
): value is { default: unknown; __esModule?: boolean } => {
  if (!value || typeof value !== "object" || !("default" in value)) {
    return false;
  }

  return Object.keys(value).every((key) => {
    return key === "default" || key === "__esModule";
  });
};

const buildLocalEditorConfigCacheBypassPath = (
  absoluteStreamConfigPath: string
): string => {
  const extension = path.extname(absoluteStreamConfigPath);
  const baseName = path.basename(absoluteStreamConfigPath, extension);
  const cacheBypassSuffix = `${Date.now()}-${Math.random()
    .toString(36)
    .slice(2, 10)}`;

  return path.join(
    path.dirname(absoluteStreamConfigPath),
    `.${baseName}.local-editor.${cacheBypassSuffix}${extension}`
  );
};

const normalizeDefaultLayoutData = (defaultLayoutData: unknown): unknown => {
  if (typeof defaultLayoutData !== "string") {
    return defaultLayoutData;
  }

  try {
    return JSON.parse(defaultLayoutData) as unknown;
  } catch {
    return defaultLayoutData;
  }
};

const isPlainObject = (value: unknown): value is Record<string, unknown> => {
  return !!value && typeof value === "object" && !Array.isArray(value);
};

const readJsonFile = <T>(filePath: string, description: string): T => {
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf8")) as T;
  } catch (error) {
    throw new Error(
      `Failed to parse ${description} at ${path.relative(process.cwd(), filePath)}: ${toErrorMessage(error)}`
    );
  }
};

const toErrorMessage = (error: unknown): string => {
  return error instanceof Error ? error.message : String(error);
};
