import path from "node:path";
import fs from "fs-extra";
import { Plugin } from "vite";
import baseTemplate from "./templates/base.tsx?raw";
import editTemplate from "./templates/edit.tsx?raw";
import editDevEntryTemplate from "./templates/editDevEntry.tsx?raw";
import directoryTemplate from "./templates/directory.tsx?raw";
import locatorTemplate from "./templates/locator.tsx?raw";
import { ComponentField } from "../types/fields.ts";
import { defaultLayoutData } from "./defaultLayoutData.ts";
import {
  generateRegistryTemplateFiles,
  getCollectedRegistryTemplateNames,
} from "./registryTemplateGenerator.ts";
import {
  getEditorTemplateFilePath,
  getEditorTemplateInfosFromTemplateNames,
  isManagedEditorTemplateFileName,
  injectEditorTemplateInfo,
} from "./editorRoute.ts";
import { getEffectiveEditorTemplateNames } from "./editorTemplateNames.ts";
import {
  getEditorDevEntryTemplateInfoFromTemplateNames,
  injectEditorDevEntryTemplateInfo,
} from "./editorDevMode.ts";

type TemplateManifestEntry = {
  name: string;
  description: string;
  exampleSiteUrl: string;
  layoutRequired: boolean;
  defaultLayoutData?: any;
  componentFields?: ComponentField[];
};

type VirtualFile = {
  filepath: string;
  content: any;
  templateManifestEntry?: TemplateManifestEntry;
};

/**
 * virtualFiles defines the template files that are to be generated and inserted into
 * the repo during buildStart
 *
 * It also defines entries that will be used to generate the template-manifest.json
 */
const virtualFiles: VirtualFile[] = [
  {
    filepath: "src/templates/directory.tsx",
    content: directoryTemplate,
    templateManifestEntry: {
      name: "directory",
      description:
        "Use this template to generate pages for each of your Directory entities.",
      exampleSiteUrl: "",
      layoutRequired: true,
      defaultLayoutData: defaultLayoutData.directory,
      // no componentFields are defined because this is handled in the back-end for the dynamically
      // generated DM fields
    },
  },
  {
    filepath: "src/templates/locator.tsx",
    content: locatorTemplate,
    templateManifestEntry: {
      name: "locator",
      description: "Use this template to generate pages for your Locators.",
      exampleSiteUrl: "",
      layoutRequired: true,
      defaultLayoutData: defaultLayoutData.locator,
    },
  },
  {
    filepath: "src/templates/edit.tsx",
    content: editTemplate,
  },
].filter((virtualFile) => virtualFile.filepath !== "src/templates/edit.tsx");

const GENERATED_TEMPLATE_FILE_PREFIX =
  "/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */";
const GENERATED_EDIT_LOCAL_DATA_HASH = "cfcd208495d565ef66e7dff9f98764da";
const GENERATED_EDIT_LOCAL_DATA_LOCALE = "en";
const GENERATED_EDIT_LOCAL_DATA_PREFIX =
  "cog-internal-feature-static-file-generation-";
const cleanupFilePaths = new Set<string>();
let cleanupSignalHandlersRegistered = false;

const registerCleanupSignalHandlers = () => {
  if (cleanupSignalHandlersRegistered) {
    return;
  }

  const cleanupGeneratedFiles = () => {
    for (const filePath of cleanupFilePaths) {
      fs.rmSync(filePath, { force: true });
    }
    cleanupFilePaths.clear();
  };

  process.on("SIGINT", () => {
    cleanupGeneratedFiles();
    process.nextTick(() => process.exit(0));
  });

  process.on("SIGTERM", () => {
    cleanupGeneratedFiles();
    process.nextTick(() => process.exit(0));
  });

  cleanupSignalHandlersRegistered = true;
};

const writeFileIfChanged = (filePath: string, content: string): boolean => {
  if (fs.existsSync(filePath)) {
    const existingContent = fs.readFileSync(filePath, "utf8");
    if (existingContent === content) {
      return false;
    }
  }

  fs.writeFileSync(filePath, content);
  return true;
};

export const yextVisualEditorPlugin = (): Plugin => {
  let isBuildMode = false;
  const filesToCleanup: string[] = [];
  registerCleanupSignalHandlers();

  const trackFileForCleanup = (filePath: string) => {
    if (!filesToCleanup.includes(filePath)) {
      filesToCleanup.push(filePath);
    }
    cleanupFilePaths.add(filePath);
  };

  const isAutogeneratedTemplateFile = (filePath: string): boolean => {
    if (!fs.existsSync(filePath)) {
      return false;
    }

    return fs
      .readFileSync(filePath, "utf8")
      .startsWith(GENERATED_TEMPLATE_FILE_PREFIX);
  };

  const hasExplicitLocalMainTemplate = (rootDir: string): boolean => {
    const mainTemplatePath = path.join(rootDir, "src", "templates", "main.tsx");
    return (
      fs.existsSync(mainTemplatePath) &&
      !isAutogeneratedTemplateFile(mainTemplatePath)
    );
  };

  const getGeneratedEditLocalDataFilename = (configName: string): string => {
    return `${GENERATED_EDIT_LOCAL_DATA_PREFIX}${configName}__${GENERATED_EDIT_LOCAL_DATA_LOCALE}__${GENERATED_EDIT_LOCAL_DATA_HASH}.json`;
  };

  const writeGeneratedEditLocalDataFile = (
    filePath: string,
    configName: string
  ) => {
    writeFileIfChanged(
      filePath,
      `${JSON.stringify(
        {
          __: {
            name: configName,
            staticPage: {},
          },
          _site: {},
          businessId: 1000167251,
          locale: GENERATED_EDIT_LOCAL_DATA_LOCALE,
          meta: {
            locale: GENERATED_EDIT_LOCAL_DATA_LOCALE,
          },
          siteDomain: "",
          siteId: 0,
          siteInternalHostName: "",
        },
        null,
        2
      )}\n`
    );
  };

  const syncGeneratedEditLocalData = (
    rootDir: string,
    configNames: string[]
  ) => {
    const localDataDir = path.join(rootDir, "localData");
    const expectedFileNames = new Set(
      configNames.map(getGeneratedEditLocalDataFilename)
    );

    if (expectedFileNames.size > 0) {
      fs.ensureDirSync(localDataDir);
    }

    if (fs.existsSync(localDataDir)) {
      for (const entry of fs.readdirSync(localDataDir, {
        withFileTypes: true,
      })) {
        if (!entry.isFile()) {
          continue;
        }

        const isGeneratedEditLocalData =
          entry.name.startsWith(`${GENERATED_EDIT_LOCAL_DATA_PREFIX}edit`) &&
          entry.name.endsWith(".json");
        if (!isGeneratedEditLocalData || expectedFileNames.has(entry.name)) {
          continue;
        }

        fs.removeSync(path.join(localDataDir, entry.name));
      }
    }

    for (const configName of configNames) {
      const filePath = path.join(
        localDataDir,
        getGeneratedEditLocalDataFilename(configName)
      );
      writeGeneratedEditLocalDataFile(filePath, configName);
      trackFileForCleanup(filePath);
    }
  };

  /**
   * Keeps the dev-only `/edit` entry page aligned with the current repo shape.
   *
   * The entry page only exists when a repo has real editor pages at
   * `/edit/{templateId}`. In the legacy `main` case, `src/templates/edit.tsx`
   * remains the real editor template instead.
   */
  const syncEditDevEntryTemplate = (
    rootDir: string,
    entryTemplateInfo: ReturnType<
      typeof getEditorDevEntryTemplateInfoFromTemplateNames
    >,
    options?: {
      preserveExistingEditTemplate?: boolean;
    }
  ) => {
    const entryTemplatePath = path.join(
      rootDir,
      "src",
      "templates",
      "edit.tsx"
    );

    if (!entryTemplateInfo) {
      if (options?.preserveExistingEditTemplate) {
        return;
      }

      if (isAutogeneratedTemplateFile(entryTemplatePath)) {
        fs.removeSync(entryTemplatePath);
      }
      return;
    }

    fs.mkdirSync(path.dirname(entryTemplatePath), { recursive: true });

    if (
      fs.existsSync(entryTemplatePath) &&
      !isAutogeneratedTemplateFile(entryTemplatePath)
    ) {
      throw new Error(
        `Refusing to overwrite hand-authored edit entry template at ${entryTemplatePath}`
      );
    }

    writeFileIfChanged(
      entryTemplatePath,
      injectEditorDevEntryTemplateInfo(editDevEntryTemplate, entryTemplateInfo)
    );
    trackFileForCleanup(entryTemplatePath);
  };

  /**
   * Syncs the real editor templates that render the editor shell itself.
   *
   * In a legacy repo this is just `src/templates/edit.tsx`. In a custom-only
   * repo this becomes one generated template per custom template id.
   */
  const syncEditorInstanceTemplates = (
    rootDir: string,
    availableTemplateNames: string[],
    additionalManagedTemplatePathsToPreserve: string[] = []
  ) => {
    const desiredEditorTemplateInfos = getEditorTemplateInfosFromTemplateNames(
      availableTemplateNames
    );
    const desiredTemplatePaths = new Set([
      ...desiredEditorTemplateInfos.map((editorTemplateInfo) =>
        path.join(rootDir, getEditorTemplateFilePath(editorTemplateInfo))
      ),
      ...additionalManagedTemplatePathsToPreserve.map((templatePath) =>
        path.join(rootDir, templatePath)
      ),
    ]);
    const templatesDirectory = path.join(rootDir, "src", "templates");
    fs.ensureDirSync(templatesDirectory);

    if (fs.existsSync(templatesDirectory)) {
      for (const entry of fs.readdirSync(templatesDirectory, {
        withFileTypes: true,
      })) {
        if (!entry.isFile() || path.extname(entry.name) !== ".tsx") {
          continue;
        }

        const templateName = entry.name.replace(/\.tsx$/, "");
        if (!isManagedEditorTemplateFileName(templateName)) {
          continue;
        }

        const templatePath = path.join(templatesDirectory, entry.name);
        if (desiredTemplatePaths.has(templatePath)) {
          continue;
        }

        if (isAutogeneratedTemplateFile(templatePath)) {
          fs.removeSync(templatePath);
        }
      }
    }

    for (const editorTemplateInfo of desiredEditorTemplateInfos) {
      const editorTemplatePath = path.join(
        rootDir,
        getEditorTemplateFilePath(editorTemplateInfo)
      );
      const desiredTemplateSource = injectEditorTemplateInfo(
        editTemplate,
        editorTemplateInfo
      );
      fs.mkdirSync(path.dirname(editorTemplatePath), { recursive: true });

      if (
        fs.existsSync(editorTemplatePath) &&
        !isAutogeneratedTemplateFile(editorTemplatePath)
      ) {
        throw new Error(
          `Refusing to overwrite hand-authored editor template at ${editorTemplatePath}`
        );
      }

      const shouldRewriteExistingTemplate =
        fs.existsSync(editorTemplatePath) &&
        isAutogeneratedTemplateFile(editorTemplatePath) &&
        !fs
          .readFileSync(editorTemplatePath, "utf8")
          .includes("componentRegistry");

      if (!fs.existsSync(editorTemplatePath) || shouldRewriteExistingTemplate) {
        writeFileIfChanged(editorTemplatePath, desiredTemplateSource);
      }

      trackFileForCleanup(editorTemplatePath);
    }

    return desiredEditorTemplateInfos;
  };

  /**
   * generateFiles generates the template files and .temlpate-manifest.json file
   *
   * Overview:
   * 1. Ensure the built-in virtual template files exist on disk.
   * 2. Collect manifest entries for the generated template manifest.
   * 3. Sync the generated editor templates and dev entry page with the
   *    resolved editor route metadata.
   * 4. Write the .template-manifest.json file when it does not already exist.
   *
   * Does not overwrite files that already exists
   *
   * Created files will be marked for deletion on buildEnd
   */
  const generateFiles = () => {
    const rootDir = process.cwd();

    // Create a structure to store the manifest data
    const manifest: {
      templates: TemplateManifestEntry[];
    } = { templates: [] };

    // Iterate over each template definition
    virtualFiles.forEach((virtualFile: VirtualFile) => {
      const filePath = path.join(rootDir, virtualFile.filepath);

      // Ensure the directory exists
      fs.mkdirSync(path.dirname(filePath), { recursive: true });

      // Write the content to the file if it doesn't already exist
      if (!fs.existsSync(filePath)) {
        trackFileForCleanup(filePath);
        fs.writeFileSync(filePath, virtualFile.content);
      }

      // populate template-manifest object
      if (virtualFile.templateManifestEntry) {
        manifest.templates.push(virtualFile.templateManifestEntry);
      }
    });

    const explicitLocalTemplateNames = [
      ...(hasExplicitLocalMainTemplate(rootDir) ? ["main"] : []),
      ...getCollectedRegistryTemplateNames(rootDir),
    ];
    const { templateNames: availableTemplateNames } =
      getEffectiveEditorTemplateNames(explicitLocalTemplateNames);
    const entryTemplateInfo = isBuildMode
      ? null
      : getEditorDevEntryTemplateInfoFromTemplateNames(availableTemplateNames);
    const editorTemplateInfos = syncEditorInstanceTemplates(
      rootDir,
      availableTemplateNames,
      entryTemplateInfo ? ["src/templates/edit.tsx"] : []
    );
    syncEditDevEntryTemplate(
      rootDir,
      editorTemplateInfos.some(
        (editorTemplateInfo) => editorTemplateInfo.configName !== "edit"
      )
        ? entryTemplateInfo
        : null,
      {
        preserveExistingEditTemplate: editorTemplateInfos.some(
          (editorTemplateInfo) => editorTemplateInfo.configName === "edit"
        ),
      }
    );
    syncGeneratedEditLocalData(
      rootDir,
      isBuildMode
        ? []
        : Array.from(
            new Set([
              ...editorTemplateInfos.map(
                (editorTemplateInfo) => editorTemplateInfo.configName
              ),
              ...(entryTemplateInfo ? [entryTemplateInfo.configName] : []),
            ])
          )
    );

    const manifestPath = path.join(rootDir, ".template-manifest.json");
    if (!fs.existsSync(manifestPath)) {
      // Write the manifest to the .template-manifest.json file
      fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
    }
  };

  const cleanupFiles = () => {
    filesToCleanup.forEach((filePath) => {
      fs.rmSync(filePath, { force: true });
      cleanupFilePaths.delete(filePath);
    });
  };

  return {
    name: "vite-plugin-yext-visual-editor",
    config(_, { command }) {
      isBuildMode = command === "build";
    },
    buildStart() {
      generateFiles();
      generateRegistryTemplateFiles({
        rootDir: process.cwd(),
        generatedBaseTemplateSource: baseTemplate,
      });
    },
    buildEnd() {
      if (isBuildMode) {
        cleanupFiles();
      }
    },
  };
};
