/**
 * High-level overview:
 *
 * 1) Discover templates from `<starter>/src/registry/*`.
 *    - Each subdirectory under `<starter>/src/registry` is treated as a
 *      template name.
 *    - Example: `<starter>/src/registry/main` -> template name `main`.
 *
 * 2) Generate one config per template.
 *    - Scan template-specific components from
 *      `<starter>/src/registry/<template>/components`.
 *    - Emit `<starter>/src/registry/<template>/config.tsx`.
 *    - Ignore registry templates that do not contain any component source files.
 *
 * 3) Materialize template files for discovered registry templates.
 *    - Use the plugin's internal `base.tsx` source as the shared base template.
 *    - Emit `<starter>/src/templates/<template>.tsx` for each registry
 *      template that has components.
 *    - Insert the matching `<starter>/src/registry/<template>/config.tsx`
 *      import.
 *    - Adapt `baseConfig` and rename the exported `Base` component to match the
 *      template name.
 *
 * 4) Update `<starter>/.template-manifest.json`.
 *    - Read `<starter>/src/registry/<template>/defaultLayout.json` when
 *      present.
 *    - Fall back to a generic default layout when that file is missing.
 *    - Write that JSON into the matching template's `defaultLayoutData`.
 *    - Create a manifest entry when a registry template is missing.
 *
 * 5) Update editor wiring.
 *    - Patch `<starter>/src/templates/edit.tsx`.
 *    - Import each generated config into `componentRegistry`.
 *    - Ensure `componentRegistry` points each generated template name to its
 *      config while preserving existing `directory` and `locator` entries.
 *    - Set `editPath` using the final available template set.
 */
import path from "node:path";
import fs from "fs-extra";
import { Project, QuoteKind, SyntaxKind, type SourceFile } from "ts-morph";
import { getEditorPathFromTemplateNames } from "./editorRoute.ts";

type TemplateManifestEntry = {
  name: string;
  description: string;
  exampleSiteUrl: string;
  layoutRequired: boolean;
  defaultLayoutData?: unknown;
};

type ManifestFile = {
  templates?: TemplateManifestEntry[];
};

type TemplatePaths = {
  templateName: string;
  registryDirectory: string;
  componentsDirectory: string;
  defaultLayoutPath: string;
  configPath: string;
  templatePath: string;
};

type CollectedItem = {
  importName: string;
  exportName: string;
  componentName: string;
  categoryKey: string;
  categoryTitle: string;
  fileRelativeToRoot: string;
};

type CollectedTemplate = {
  templateName: string;
  templatePaths: TemplatePaths;
  items: CollectedItem[];
};

type ImportDefinition = string | { name: string; alias?: string };

type InsertNamedImportOptions = {
  moduleSpecifier: string;
  namedImports: ImportDefinition[];
};

const VALID_EXTENSIONS = new Set([".tsx", ".ts", ".jsx", ".js"]);
const PRESERVED_EDIT_REGISTRY_KEYS = new Set(["directory", "locator"]);
const PROTECTED_TEMPLATE_FILE_NAMES = new Set(["edit", "directory", "locator"]);
const AUTOGENERATED_TEMPLATE_DESCRIPTION_PREFIX =
  "Autogenerated template entry for ";
const GENERATED_CONFIG_FILE_PREFIX =
  "/** THIS FILE IS AUTOGENERATED BY @yext/visual-editor/plugin */";
const GENERATED_TEMPLATE_FILE_PREFIX =
  "/** THIS FILE IS AUTOGENERATED AND SHOULD NOT BE EDITED */";
const AST_PROJECT = new Project({
  manipulationSettings: {
    quoteKind: QuoteKind.Double,
  },
});

export const DEFAULT_LAYOUT = {
  root: {
    props: {
      version: 1,
      title: {
        field: "",
        constantValue: {
          defaultValue: "Page Title",
        },
        constantValueEnabled: true,
      },
      description: {
        field: "",
        constantValue: {
          defaultValue: "Page Description",
        },
        constantValueEnabled: true,
      },
    },
  },
  content: [],
  zones: {},
};

/**
 * Generates all template configs, generated template.tsx files, matching
 * `.template-manifest.json` entries, and `edit.tsx` registry wiring for
 * registry templates that contain component files.
 * @param {{
 *   rootDir: string,
 *   generatedBaseTemplateSource: string
 * }} options
 */
export const generateRegistryTemplateFiles = ({
  rootDir,
  generatedBaseTemplateSource,
}: {
  rootDir: string;
  generatedBaseTemplateSource: string;
}): void => {
  // 1) Discover templates from `<starter>/src/registry/*`.
  const collectedTemplates: CollectedTemplate[] = getTemplateNames(rootDir)
    .map((templateName) => {
      if (PRESERVED_EDIT_REGISTRY_KEYS.has(templateName)) {
        console.warn(
          `Skipping registry template "${templateName}" because it conflicts with a reserved componentRegistry key`
        );
        return null;
      }

      return {
        templateName,
        templatePaths: getTemplatePaths(rootDir, templateName),
        items: collectTemplateComponents(rootDir, templateName),
      };
    })
    .filter((template): template is CollectedTemplate => template !== null)
    .filter(({ items }) => items.length > 0);

  const templateNames = collectedTemplates.map(
    ({ templateName }) => templateName
  );

  // 2) and 3) Generate the current config/template files and prune stale
  // autogenerated outputs that no longer correspond to a collected template.
  syncGeneratedRegistryFiles(
    rootDir,
    generatedBaseTemplateSource,
    collectedTemplates
  );

  // 4) Update `<starter>/.template-manifest.json`.
  const availableTemplateNames = updateTemplateManifest(rootDir, templateNames);

  // 5) Update editor wiring.
  updateEditTemplate(rootDir, templateNames, availableTemplateNames);
};

export const getCollectedRegistryTemplateNames = (
  rootDir: string
): string[] => {
  return getTemplateNames(rootDir)
    .filter((templateName) => !PRESERVED_EDIT_REGISTRY_KEYS.has(templateName))
    .filter(
      (templateName) =>
        collectTemplateComponents(rootDir, templateName).length > 0
    );
};

/**
 * 1) Discover templates from `<starter>/src/registry/*`.
 */
const getTemplateNames = (rootDir: string): string[] => {
  const registryDir = path.join(rootDir, "src", "registry");
  if (!fs.existsSync(registryDir)) {
    return [];
  }

  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(registryDir, { withFileTypes: true });
  } catch (error) {
    throw new Error(
      `Failed to read registry directory at ${registryDir}: ${toErrorMessage(error)}`
    );
  }

  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));
};

/**
 * Generate the current config/template files and prune stale
 * autogenerated outputs that no longer correspond to a collected template.
 */
const syncGeneratedRegistryFiles = (
  rootDir: string,
  generatedBaseTemplateSource: string,
  collectedTemplates: CollectedTemplate[]
): void => {
  const activeTemplateNames = new Set(
    collectedTemplates.map(({ templateName }) => templateName)
  );

  for (const { templateName, templatePaths, items } of collectedTemplates) {
    // 2) Generate `<starter>/src/registry/<template>/config.tsx`.
    const configSource = buildConfigSource(
      rootDir,
      items,
      templatePaths.configPath,
      templateName
    );
    fs.ensureDirSync(path.dirname(templatePaths.configPath));
    fs.writeFileSync(templatePaths.configPath, configSource);

    // 3) Materialize `<starter>/src/templates/<template>.tsx` from the internal base template.
    const configImportPath = toPosixPath(
      path
        .relative(
          path.dirname(templatePaths.templatePath),
          templatePaths.configPath
        )
        .replace(/\.[^/.]+$/, "")
    );
    const templateSource = buildTemplateSource(
      generatedBaseTemplateSource,
      templateName,
      configImportPath.startsWith(".")
        ? configImportPath
        : `./${configImportPath}`,
      getTemplateConfigExportName(templateName)
    );
    fs.ensureDirSync(path.dirname(templatePaths.templatePath));
    assertCanWriteGeneratedTemplateFile(
      templateName,
      templatePaths.templatePath
    );
    fs.writeFileSync(templatePaths.templatePath, templateSource);
  }

  pruneStaleGeneratedTemplateFiles(rootDir, activeTemplateNames);
  pruneStaleGeneratedConfigFiles(rootDir, activeTemplateNames);
};

/**
 * 2) Collect template-specific components and reject invalid or colliding
 * generated identifiers before config generation.
 */
const collectTemplateComponents = (
  rootDir: string,
  templateName: string
): CollectedItem[] => {
  const templatePaths = getTemplatePaths(rootDir, templateName);
  const componentPaths = discoverComponents(templatePaths.componentsDirectory);
  if (!componentPaths.length) {
    return [];
  }

  const templateKey = requireValidTypeScriptIdentifier(
    requireNonEmpty(
      toPascalCase(templateName),
      `Could not derive a template key from ${templateName}`
    ),
    `Template name "${templateName}" must normalize to a valid TypeScript identifier`
  );
  const componentNameToSourcePath = new Map<string, string>();

  return componentPaths.map((absolutePath) => {
    const fileRelativeToRoot = toPosixPath(
      path.relative(rootDir, absolutePath)
    );
    const fileRelativeToGroup = toPosixPath(
      path.relative(templatePaths.componentsDirectory, absolutePath)
    );
    const category = getComponentCategory(fileRelativeToGroup);

    const baseName = requireValidTypeScriptIdentifier(
      requireNonEmpty(
        toPascalCase(path.basename(fileRelativeToGroup)),
        `Could not derive a component name from ${fileRelativeToRoot}`
      ),
      `Component path "${fileRelativeToRoot}" must normalize to a valid TypeScript identifier`
    );

    const componentName = baseName;
    const existingSourcePath = componentNameToSourcePath.get(componentName);
    if (existingSourcePath) {
      throw new Error(
        `Component name collision in template "${templateName}": ${existingSourcePath} and ${fileRelativeToRoot} both normalize to "${componentName}"`
      );
    }
    componentNameToSourcePath.set(componentName, fileRelativeToRoot);

    return {
      importName: `${templateKey}Component${componentName}`,
      exportName: baseName,
      componentName,
      categoryKey: category.key,
      categoryTitle: category.title,
      fileRelativeToRoot,
    };
  });
};

/**
 * 2) Generate `<starter>/src/registry/<template>/config.tsx`.
 */
const buildConfigSource = (
  rootDir: string,
  items: CollectedItem[],
  outputFilePath: string,
  templateName: string
): string => {
  const configExportName = getTemplateConfigExportName(templateName);
  const importLines = items.map((item) => {
    const importPath = toPosixPath(
      path
        .relative(
          path.dirname(outputFilePath),
          path.join(rootDir, item.fileRelativeToRoot)
        )
        .replace(/\.[^/.]+$/, "")
    );
    const normalizedImportPath = importPath.startsWith(".")
      ? importPath
      : `./${importPath}`;
    return `import { ${item.exportName} as ${item.importName} } from "${normalizedImportPath}";`;
  });
  const components = Object.fromEntries(
    items.map((item) => [item.componentName, item.importName])
  ) as Record<string, string>;
  const categories = buildPuckCategories(items);

  return [
    "/** THIS FILE IS AUTOGENERATED BY @yext/visual-editor/plugin */",
    'import type { Config } from "@puckeditor/core";',
    ...(importLines.length ? ["", ...importLines] : []),
    "",
    `export const ${configExportName}: Config = {`,
    items.length
      ? `  components: ${renderIdentifierMap(components)},`
      : "  components: {},",
    items.length ? "" : "  // No components found in this template registry",
    `  categories: ${JSON.stringify(categories, null, 2)},`,
    "};",
    "",
  ]
    .filter(Boolean)
    .join("\n");
};

/**
 * 3) Materialize `<starter>/src/templates/<template>.tsx` from the internal
 * base template.
 */
const buildTemplateSource = (
  baseSource: string,
  templateName: string,
  configImportPath: string,
  configExportName: string
): string => {
  const templateComponentName = requireValidTypeScriptIdentifier(
    requireNonEmpty(
      toPascalCase(templateName),
      `Could not derive a template component name from ${templateName}`
    ),
    `Template name "${templateName}" must normalize to a valid TypeScript identifier`
  );
  const sourceFilePath = path.join(
    process.cwd(),
    "__generated_template_source__.tsx"
  );
  AST_PROJECT.getSourceFile(sourceFilePath)?.forget();

  const sourceFile = AST_PROJECT.createSourceFile(sourceFilePath, baseSource, {
    overwrite: true,
  });

  insertNamedImport(sourceFile, {
    namedImports: [configExportName],
    moduleSpecifier: configImportPath,
  });
  removeNamedImports(sourceFile, "@puckeditor/core", ["Config"]);

  const baseConfigDeclaration = sourceFile.getVariableDeclaration("baseConfig");
  if (!baseConfigDeclaration) {
    sourceFile.forget();
    throw new Error("Could not find baseConfig in generated base template");
  }

  for (const referenceNode of baseConfigDeclaration.findReferencesAsNodes()) {
    if (
      referenceNode.getStart() ===
      baseConfigDeclaration.getNameNode().getStart()
    ) {
      continue;
    }

    referenceNode.replaceWithText(configExportName);
  }

  const baseConfigStatement = baseConfigDeclaration.getFirstAncestorByKind(
    SyntaxKind.VariableStatement
  );
  if (!baseConfigStatement) {
    sourceFile.forget();
    throw new Error(
      "Could not find baseConfig declaration in generated base template"
    );
  }
  baseConfigStatement.remove();

  const baseDeclaration = sourceFile.getVariableDeclaration("Base");
  if (!baseDeclaration) {
    sourceFile.forget();
    throw new Error(
      "Could not find Base component placeholder in generated base template"
    );
  }
  baseDeclaration.rename(templateComponentName);

  const exportAssignment = sourceFile.getExportAssignment((assignment) => {
    return !assignment.isExportEquals();
  });
  if (!exportAssignment) {
    sourceFile.forget();
    throw new Error(
      "Could not find default export placeholder in generated base template"
    );
  }
  exportAssignment.setExpression(templateComponentName);

  sourceFile.formatText();
  const renderedTemplateSource = sourceFile.getFullText();
  sourceFile.forget();
  return renderedTemplateSource;
};

/**
 * 4) Update `<starter>/.template-manifest.json` from matching
 * `defaultLayout.json` files, falling back to a generic layout when missing.
 */
const updateTemplateManifest = (
  rootDir: string,
  templateNames: string[]
): string[] => {
  const manifestPath = path.join(rootDir, ".template-manifest.json");
  const manifest: ManifestFile = fs.existsSync(manifestPath)
    ? readJsonFile<ManifestFile>(manifestPath, "template manifest JSON")
    : { templates: [] };

  if (!Array.isArray(manifest.templates)) {
    manifest.templates = [];
  }

  let updated = false;

  for (const templateName of templateNames) {
    const { defaultLayoutPath } = getTemplatePaths(rootDir, templateName);
    const defaultLayoutData = fs.existsSync(defaultLayoutPath)
      ? readJsonFile<unknown>(
          defaultLayoutPath,
          `default layout JSON for template "${templateName}"`
        )
      : DEFAULT_LAYOUT;
    const existingEntry = manifest.templates.find(
      (template) => template.name === templateName
    );

    if (!existingEntry) {
      manifest.templates.push({
        name: templateName,
        description: `${AUTOGENERATED_TEMPLATE_DESCRIPTION_PREFIX}${templateName}.`,
        exampleSiteUrl: "",
        layoutRequired: true,
        defaultLayoutData,
      });
      updated = true;
      continue;
    }

    if (
      JSON.stringify(existingEntry.defaultLayoutData) !==
      JSON.stringify(defaultLayoutData)
    ) {
      existingEntry.defaultLayoutData = defaultLayoutData;
      updated = true;
    }
  }

  const prunedTemplates = manifest.templates.filter((template) => {
    return (
      templateNames.includes(template.name) ||
      !template.description.startsWith(
        AUTOGENERATED_TEMPLATE_DESCRIPTION_PREFIX
      )
    );
  });

  if (prunedTemplates.length !== manifest.templates.length) {
    manifest.templates = prunedTemplates;
    updated = true;
  }

  if (updated) {
    fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  }

  return getAvailableTemplateNames(
    rootDir,
    manifest.templates.map((template) => template.name)
  );
};

/**
 * 5) Update `<starter>/src/templates/edit.tsx` to import and register each
 * generated config.
 */
const updateEditTemplate = (
  rootDir: string,
  templateNames: string[],
  availableTemplateNames: string[]
): void => {
  const editTemplatePath = path.join(rootDir, "src", "templates", "edit.tsx");
  if (!fs.existsSync(editTemplatePath)) {
    return;
  }

  const originalSource = readUtf8File(editTemplatePath, "edit template source");
  const sourceFile = getAstSourceFile(editTemplatePath);

  removeGeneratedConfigImports(sourceFile);
  ensureSideEffectImport(sourceFile, "@yext/visual-editor/editor.css");
  ensureSideEffectImport(sourceFile, "../index.css");

  for (const templateName of templateNames) {
    const templatePaths = getTemplatePaths(rootDir, templateName);
    const moduleSpecifier = toPosixPath(
      path
        .relative(path.dirname(editTemplatePath), templatePaths.configPath)
        .replace(/\.[^/.]+$/, "")
    );

    insertNamedImport(sourceFile, {
      namedImports: [
        {
          name: getTemplateConfigExportName(templateName),
          alias: getEditConfigIdentifier(templateName),
        },
      ],
      moduleSpecifier: moduleSpecifier.startsWith(".")
        ? moduleSpecifier
        : `./${moduleSpecifier}`,
    });
  }

  setEditComponentRegistry(sourceFile, templateNames);
  setEditPath(sourceFile, availableTemplateNames);

  const updatedSource = sourceFile.getFullText();
  sourceFile.forget();

  if (updatedSource !== originalSource) {
    fs.writeFileSync(editTemplatePath, updatedSource);
  }
};

/**
 * Builds the `<starter>` paths associated with one registry template.
 */
const getTemplatePaths = (
  rootDir: string,
  templateName: string
): TemplatePaths => {
  const registryDirectory = path.join(rootDir, "src", "registry", templateName);
  return {
    templateName,
    registryDirectory,
    componentsDirectory: path.join(registryDirectory, "components"),
    defaultLayoutPath: path.join(registryDirectory, "defaultLayout.json"),
    configPath: path.join(registryDirectory, "config.tsx"),
    templatePath: path.join(rootDir, "src", "templates", `${templateName}.tsx`),
  };
};

/**
 * Recursively returns supported component source files under a template's
 * `components` directory.
 */
const discoverComponents = (directory: string): string[] => {
  if (!fs.existsSync(directory)) {
    return [];
  }

  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(directory, { withFileTypes: true });
  } catch (error) {
    throw new Error(
      `Failed to read registry directory at ${directory}: ${toErrorMessage(error)}`
    );
  }

  return entries
    .flatMap((entry) => {
      const absolutePath = path.join(directory, entry.name);
      if (entry.isDirectory()) {
        return discoverComponents(absolutePath);
      }
      if (!entry.isFile() || !VALID_EXTENSIONS.has(path.extname(entry.name))) {
        return [];
      }

      return [absolutePath];
    })
    .sort((a, b) => a.localeCompare(b));
};

/**
 * Deletes autogenerated `src/templates/*.tsx` files whose template names are no
 * longer part of the current registry set.
 */
const pruneStaleGeneratedTemplateFiles = (
  rootDir: string,
  activeTemplateNames: Set<string>
): void => {
  const templatesDirectory = path.join(rootDir, "src", "templates");
  if (!fs.existsSync(templatesDirectory)) {
    return;
  }

  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(templatesDirectory, { withFileTypes: true });
  } catch (error) {
    throw new Error(
      `Failed to read templates directory at ${templatesDirectory}: ${toErrorMessage(error)}`
    );
  }

  for (const entry of entries) {
    if (!entry.isFile() || path.extname(entry.name) !== ".tsx") {
      continue;
    }

    const templateName = entry.name.replace(/\.tsx$/, "");
    if (
      activeTemplateNames.has(templateName) ||
      PROTECTED_TEMPLATE_FILE_NAMES.has(templateName)
    ) {
      continue;
    }

    const templatePath = path.join(templatesDirectory, entry.name);
    if (!isAutogeneratedFile(templatePath, GENERATED_TEMPLATE_FILE_PREFIX)) {
      continue;
    }

    fs.removeSync(templatePath);
  }
};

/**
 * Deletes autogenerated `src/registry/<template>/config.tsx` files for
 * templates that no longer have any collected components.
 */
const pruneStaleGeneratedConfigFiles = (
  rootDir: string,
  activeTemplateNames: Set<string>
): void => {
  const registryDirectory = path.join(rootDir, "src", "registry");
  if (!fs.existsSync(registryDirectory)) {
    return;
  }

  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(registryDirectory, { withFileTypes: true });
  } catch (error) {
    throw new Error(
      `Failed to read registry directory at ${registryDirectory}: ${toErrorMessage(error)}`
    );
  }

  for (const entry of entries) {
    if (!entry.isDirectory() || activeTemplateNames.has(entry.name)) {
      continue;
    }

    const configPath = path.join(registryDirectory, entry.name, "config.tsx");
    if (!fs.existsSync(configPath)) {
      continue;
    }

    if (!isAutogeneratedFile(configPath, GENERATED_CONFIG_FILE_PREFIX)) {
      continue;
    }

    fs.removeSync(configPath);
  }
};

/**
 * Refuses to overwrite an existing hand-authored template file. Reserved
 * template names and already-autogenerated files may still be rewritten.
 */
const assertCanWriteGeneratedTemplateFile = (
  templateName: string,
  templatePath: string
): void => {
  if (!fs.existsSync(templatePath)) {
    return;
  }

  if (PRESERVED_EDIT_REGISTRY_KEYS.has(templateName)) {
    return;
  }

  if (isAutogeneratedFile(templatePath, GENERATED_TEMPLATE_FILE_PREFIX)) {
    return;
  }

  throw new Error(
    `Refusing to overwrite hand-authored template "${templateName}" at ${templatePath} while writing generated output from buildTemplateSource`
  );
};

// AST helpers used by steps 3 and 5 when generating template source files and
// patching `<starter>/src/templates/edit.tsx`.

function getAstSourceFile(filePath: string): SourceFile {
  AST_PROJECT.getSourceFile(filePath)?.forget();
  try {
    return AST_PROJECT.addSourceFileAtPath(filePath);
  } catch (error) {
    throw new Error(
      `Failed to read TypeScript source at ${filePath}: ${toErrorMessage(error)}`
    );
  }
}

function removeNamedImports(
  sourceFile: SourceFile,
  moduleSpecifier: string,
  namesToRemove: string[]
): void {
  const declaration = sourceFile.getImportDeclarations().find((item) => {
    return item.getModuleSpecifierValue() === moduleSpecifier;
  });
  if (!declaration) {
    return;
  }

  for (const namedImport of declaration.getNamedImports()) {
    if (namesToRemove.includes(namedImport.getName())) {
      namedImport.remove();
    }
  }

  if (
    declaration.getNamedImports().length === 0 &&
    !declaration.getDefaultImport() &&
    !declaration.getNamespaceImport()
  ) {
    declaration.remove();
  }
}

function removeGeneratedConfigImports(sourceFile: SourceFile): void {
  for (const declaration of sourceFile.getImportDeclarations()) {
    const moduleSpecifier = declaration.getModuleSpecifierValue();
    if (
      moduleSpecifier === "../config" ||
      moduleSpecifier === "./config" ||
      moduleSpecifier.endsWith("/config")
    ) {
      declaration.remove();
    }
  }
}

function insertNamedImport(
  sourceFile: SourceFile,
  options: InsertNamedImportOptions
): void {
  const pagesComponentsImport = sourceFile
    .getImportDeclarations()
    .find((item) => {
      return item.getModuleSpecifierValue() === "@yext/pages-components";
    });

  if (pagesComponentsImport) {
    sourceFile.insertImportDeclaration(
      pagesComponentsImport.getChildIndex() + 1,
      {
        namedImports: options.namedImports,
        moduleSpecifier: options.moduleSpecifier,
      }
    );
    return;
  }

  sourceFile.addImportDeclaration({
    namedImports: options.namedImports,
    moduleSpecifier: options.moduleSpecifier,
  });
}

function ensureSideEffectImport(
  sourceFile: SourceFile,
  moduleSpecifier: string
): void {
  const exists = sourceFile.getImportDeclarations().some((item) => {
    return item.getModuleSpecifierValue() === moduleSpecifier;
  });
  if (!exists) {
    sourceFile.insertImportDeclaration(0, {
      moduleSpecifier,
    });
  }
}

function setEditComponentRegistry(
  sourceFile: SourceFile,
  templateNames: string[]
): void {
  const declaration = sourceFile.getVariableDeclaration("componentRegistry");
  if (!declaration) {
    return;
  }

  const initializer = declaration.getInitializerIfKind(
    SyntaxKind.ObjectLiteralExpression
  );
  if (!initializer) {
    const registryEntries = templateNames
      .map((templateName) => {
        return `  "${templateName}": ${getEditConfigIdentifier(templateName)},`;
      })
      .join("\n");
    declaration.setInitializer(`{
${registryEntries}
}`);
    return;
  }

  for (const property of initializer.getProperties()) {
    const propertyAssignment = property.asKind(SyntaxKind.PropertyAssignment);
    if (!propertyAssignment) {
      continue;
    }

    const propertyName = propertyAssignment.getName();
    if (PRESERVED_EDIT_REGISTRY_KEYS.has(propertyName)) {
      continue;
    }

    propertyAssignment.remove();
  }

  for (const templateName of templateNames) {
    initializer.addPropertyAssignment({
      name: `"${templateName}"`,
      initializer: getEditConfigIdentifier(templateName),
    });
  }
}

function setEditPath(sourceFile: SourceFile, templateNames: string[]): void {
  const declaration = sourceFile.getVariableDeclaration("editPath");
  if (!declaration) {
    return;
  }

  declaration.setInitializer(
    JSON.stringify(getEditorPathFromTemplateNames(templateNames))
  );
}

function getAvailableTemplateNames(
  rootDir: string,
  manifestTemplateNames: string[]
): string[] {
  const builtInTemplateNames = [...PRESERVED_EDIT_REGISTRY_KEYS].filter(
    (templateName) => {
      return fs.existsSync(
        path.join(rootDir, "src", "templates", `${templateName}.tsx`)
      );
    }
  );

  return [...new Set([...builtInTemplateNames, ...manifestTemplateNames])];
}

function getTemplateConfigExportName(templateName: string): string {
  return `${requireValidTypeScriptIdentifier(
    requireNonEmpty(
      toPascalCase(templateName),
      `Could not derive a config export name from ${templateName}`
    ),
    `Template name "${templateName}" must normalize to a valid TypeScript identifier`
  )}Config`;
}

function getEditConfigIdentifier(templateName: string): string {
  return `${requireValidTypeScriptIdentifier(
    requireNonEmpty(
      toCamelCase(templateName),
      `Could not derive an edit config identifier from ${templateName}`
    ),
    `Template name "${templateName}" must normalize to a valid TypeScript identifier`
  )}Config`;
}

function buildPuckCategories(items: CollectedItem[]): Record<string, unknown> {
  const categories: Record<
    string,
    { title: string; components: string[]; visible?: boolean }
  > = {};

  for (const item of items) {
    if (!categories[item.categoryKey]) {
      categories[item.categoryKey] = {
        title: item.categoryTitle,
        components: [],
      };
    }

    categories[item.categoryKey].components.push(item.componentName);
  }

  categories.other = {
    title: "Other",
    visible: false,
    components: [],
  };

  return categories;
}

function getComponentCategory(fileRelativeToGroup: string): {
  key: string;
  title: string;
} {
  const relativeDirectory = toPosixPath(path.dirname(fileRelativeToGroup));
  if (relativeDirectory === ".") {
    return {
      key: "components",
      title: "Components",
    };
  }

  return {
    key: `group:${relativeDirectory}`,
    title: toCategoryTitle(relativeDirectory),
  };
}

function toCategoryTitle(value: string): string {
  return value
    .split(path.posix.sep)
    .map((segment) => {
      return requireNonEmpty(
        toPascalCase(segment),
        `Could not derive a category title from ${value}`
      ).replace(/([a-z0-9])([A-Z])/g, "$1 $2");
    })
    .join(" / ");
}

function renderIdentifierMap(value: Record<string, string>): string {
  return [
    "{",
    ...Object.entries(value).map(([key, identifier]) => {
      return `    ${JSON.stringify(key)}: ${identifier},`;
    }),
    "  }",
  ].join("\n");
}

function isAutogeneratedFile(filePath: string, prefix: string): boolean {
  return readUtf8File(filePath, "autogenerated file").startsWith(prefix);
}

function toPascalCase(value: string): string {
  return value
    .replace(/\.[^/.]+$/, "")
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((segment) => {
      return segment[0].toUpperCase() + segment.slice(1);
    })
    .join("");
}

function toCamelCase(value: string): string {
  const pascalValue = toPascalCase(value);
  if (!pascalValue) {
    return "";
  }

  return pascalValue[0].toLowerCase() + pascalValue.slice(1);
}

function requireNonEmpty(value: string, errorMessage: string): string {
  if (!value) {
    throw new Error(errorMessage);
  }

  return value;
}

function requireValidTypeScriptIdentifier(
  value: string,
  errorMessage: string
): string {
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value)) {
    throw new Error(`${errorMessage}: "${value}"`);
  }

  return value;
}

function toPosixPath(value: string): string {
  return value.split(path.sep).join(path.posix.sep);
}

function toErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function readUtf8File(filePath: string, description: string): string {
  try {
    return fs.readFileSync(filePath, "utf8");
  } catch (error) {
    throw new Error(
      `Failed to read ${description} at ${filePath}: ${toErrorMessage(error)}`
    );
  }
}

function readJsonFile<T>(filePath: string, description: string): T {
  const source = readUtf8File(filePath, description);

  try {
    return JSON.parse(source) as T;
  } catch (error) {
    throw new Error(
      `Failed to parse ${description} at ${filePath}: ${toErrorMessage(error)}`
    );
  }
}
