buildConfiguration:
  buildCommand: pnpm run build
  installDependenciesStep:
    command: npm install -g pnpm && pnpm install --ignore-scripts --frozen-lockfile
    requiredFiles:
      - package.json
      - ../pnpm-lock.yaml
      - ../pnpm-workspace.yaml
livePreviewConfiguration:
  setupCommand: ":"
# authentication:
#   policyName: auth-policy
#   includePaths:
#     - /edit
