import path from "node:path";
import fs from "fs-extra";
import sectionLibraryConfigTemplate from "../templates/section-library-config.tsx?raw";
import {
  type SectionFrontmatter,
  readSectionFrontmatter,
} from "./sectionFrontmatter.ts";

const GENERATED_FILE_PREFIX =
  "/** THIS FILE IS GENERATED BY THE SECTION LIBRARY PLUGIN */";

type LibraryMetadata = {
  schemaVersion: 1;
  id: string;
  displayName: string;
  description: string;
};

type EntityLayoutMetadata = {
  id: string;
  displayName: string;
  previewImageUrl: string;
  vertical?: string[];
  purpose?: string[];
  pageSetType: "ENTITY";
};

type DirectoryLayoutMetadata = {
  id: string;
  displayName: string;
  pageSetType: "DIRECTORY";
};

type LocatorLayoutMetadata = {
  id: string;
  displayName: string;
  pageSetType: "LOCATOR";
};

type LayoutMetadata =
  | EntityLayoutMetadata
  | DirectoryLayoutMetadata
  | LocatorLayoutMetadata;

/**
 * A Section Library section and its static config metadata.
 *
 * `id` is the file name used in layouts and generated imports.
 * `displayName` is the name shown to the user in the editor.
 * `description` is used by AI agents when generating layouts using existing components.
 * `category` is the sidebar group for the section. When it is omitted, the
 * section appears in the "Sections" group.
 * `sourcePath` is the path used in generated imports.
 */
type Section = SectionFrontmatter & {
  id: string;
  sourcePath: string;
};

type ValidatedSection = Section & {
  displayName: string;
  description: string;
  category?: string;
  pageSetTypes: ["ENTITY", ..."ENTITY"[]];
};

type Layout<TMetadata extends LayoutMetadata = EntityLayoutMetadata> = {
  metadata: TMetadata;
  defaultLayout: Record<string, any>;
};

type SectionLibrary = {
  metadata: LibraryMetadata;
  sections: ValidatedSection[];
  layout: Layout;
};

type GeneratedSectionLibrary = {
  generatedFiles: string[];
  manifestSource?: string;
};

/**
 * Generates the Puck config and Pages templates that exist only while a build
 * or development session runs. It also produces metadata for one Entity-only
 * Section Library. It returns no files when the starter has no library.json.
 *
 * 1. Read and validate the library, section, and layout source under `src/library`.
 * 2. Generate a Puck config and Pages render and editor templates for the layout.
 * 3. Write legacy Platform template metadata and return the Section Library artifact manifest.
 */
export const generateSectionLibraryFiles = (
  rootDir: string
): GeneratedSectionLibrary => {
  const library = readSectionLibrary(rootDir);
  if (!library) {
    return { generatedFiles: [] };
  }

  const generatedDirectory = path.join(rootDir, "src", "library", ".generated");
  const configPath = path.join(generatedDirectory, "libraryConfig.tsx");
  const layoutId = library.layout.metadata.id;
  const templatePaths = [
    configPath,
    path.join(rootDir, "src", "templates", `${layoutId}.tsx`),
    path.join(rootDir, "src", "templates", "main.tsx"),
    path.join(rootDir, "src", "templates", `edit-${layoutId}.tsx`),
    path.join(rootDir, "src", "templates", "edit.tsx"),
  ];
  const templateSources = [
    buildConfigSource(rootDir, library.sections),
    buildRenderTemplateSource(layoutId),
    buildRenderTemplateSource(layoutId),
    buildEditorTemplateSource(layoutId),
    buildEditorTemplateSource(layoutId, "edit"),
  ];
  const generatedFiles = templatePaths.filter((filePath, index) => {
    return writeGeneratedFile(filePath, templateSources[index]);
  });
  writeLegacyTemplateManifest(rootDir, library.layout);

  return {
    generatedFiles,
    manifestSource: `${JSON.stringify(
      {
        schemaVersion: 1,
        library: library.metadata,
        layouts: [
          {
            ...library.layout.metadata,
            templateId: layoutId,
            editorPath: `edit/${layoutId}`,
            defaultLayout: library.layout.defaultLayout,
          },
        ],
      },
      null,
      2
    )}\n`,
  };
};

/** Reads and validates the Entity-only Section Library source. */
const readSectionLibrary = (rootDir: string): SectionLibrary | undefined => {
  const libraryDirectory = path.join(rootDir, "src", "library");
  const libraryJsonPath = path.join(libraryDirectory, "library.json");
  if (!fs.existsSync(libraryJsonPath)) {
    return undefined;
  }

  const metadata = readLibraryMetadata(libraryJsonPath);
  const sections = readSections(rootDir, libraryDirectory);
  const layout = readLayout(libraryDirectory);
  validateLayoutReferences(layout, sections);
  return { metadata, sections, layout };
};

export const cleanupGeneratedSectionLibraryFiles = (
  generatedFiles: string[]
): void => {
  for (const filePath of generatedFiles) {
    fs.removeSync(filePath);
  }
};

const readLibraryMetadata = (filePath: string): LibraryMetadata => {
  const value = readJson(filePath, "library metadata");
  if (value.schemaVersion !== 1) {
    throw new Error(`${filePath} must set schemaVersion to 1`);
  }
  return {
    schemaVersion: 1,
    id: requireString(value.id, filePath, "id"),
    displayName: requireString(value.displayName, filePath, "displayName"),
    description: requireString(value.description, filePath, "description"),
  };
};

const readSections = (
  rootDir: string,
  libraryDirectory: string
): ValidatedSection[] => {
  const sectionsDirectory = path.join(libraryDirectory, "sections");
  if (!fs.existsSync(sectionsDirectory)) {
    return [];
  }

  const sectionIds = new Set<string>();
  return fs
    .readdirSync(sectionsDirectory, { withFileTypes: true })
    .sort((left, right) =>
      left.name < right.name ? -1 : left.name > right.name ? 1 : 0
    )
    .map((entry) => {
      const sourcePath = path.join(sectionsDirectory, entry.name);
      if (entry.isDirectory()) {
        throw new Error(`Section directories are not supported: ${sourcePath}`);
      }
      const extension = path.extname(entry.name);
      if (!entry.isFile() || ![".tsx", ".jsx"].includes(extension)) {
        throw new Error(`Sections must be .tsx or .jsx files: ${sourcePath}`);
      }

      const id = path.basename(entry.name, extension);
      if (!isSafeId(id) || sectionIds.has(id)) {
        throw new Error(`Section ID is not unique or valid: ${id}`);
      }
      sectionIds.add(id);
      return readSection(sourcePath, path.relative(rootDir, sourcePath), id);
    });
};

const readSection = (
  sourcePath: string,
  relativePath: string,
  id: string
): ValidatedSection => {
  const section: Section = {
    id,
    ...readSectionFrontmatter(sourcePath, id),
    sourcePath: relativePath,
  };
  validateSection(section, sourcePath);
  return section;
};

function validateSection(
  section: Section,
  sourcePath: string
): asserts section is ValidatedSection {
  const {
    category,
    description,
    displayName,
    hasSectionConfigType,
    isConfigObject,
    pageSetTypes,
  } = section;
  if (sourcePath.endsWith(".tsx") && !hasSectionConfigType) {
    throw new Error(`${sourcePath} config must use the SectionConfig type`);
  }
  if (!isConfigObject) {
    throw new Error(`${sourcePath} config must be an object literal`);
  }
  if (
    !pageSetTypes ||
    pageSetTypes.length === 0 ||
    pageSetTypes.some((pageSetType) => pageSetType !== "ENTITY")
  ) {
    throw new Error(
      `${sourcePath} config.pageSetTypes must contain only ENTITY`
    );
  }

  if (!displayName) {
    throw new Error(`${sourcePath} config must define a non-empty displayName`);
  }
  if (!description) {
    throw new Error(`${sourcePath} config must define a non-empty description`);
  }
  if (category !== undefined && !category) {
    throw new Error(`${sourcePath} config category must be a non-empty string`);
  }
}

const readLayout = (libraryDirectory: string): Layout => {
  const layoutsDirectory = path.join(libraryDirectory, "layouts");
  if (!fs.existsSync(layoutsDirectory)) {
    throw new Error(`Missing layouts directory at ${layoutsDirectory}`);
  }
  const layouts = fs
    .readdirSync(layoutsDirectory, { withFileTypes: true })
    .filter((entry) => entry.isDirectory());
  if (layouts.length !== 1) {
    throw new Error(
      "Section Library build mode requires exactly one ENTITY layout"
    );
  }

  const layoutDirectory = path.join(layoutsDirectory, layouts[0].name);
  const metadataPath = path.join(layoutDirectory, "metadata.json");
  const metadataValue = readJson(metadataPath, "layout metadata");
  if (metadataValue.pageSetType !== "ENTITY") {
    throw new Error(`${metadataPath} must set pageSetType to ENTITY`);
  }
  const vertical = getOptionalStringListProperty(
    metadataValue,
    "vertical",
    metadataPath
  );
  const purpose = getOptionalStringListProperty(
    metadataValue,
    "purpose",
    metadataPath
  );
  const metadata: EntityLayoutMetadata = {
    id: requireString(metadataValue.id, metadataPath, "id"),
    displayName: requireString(
      metadataValue.displayName,
      metadataPath,
      "displayName"
    ),
    previewImageUrl: requireString(
      metadataValue.previewImageUrl,
      metadataPath,
      "previewImageUrl"
    ),
    ...(vertical === undefined ? {} : { vertical }),
    ...(purpose === undefined ? {} : { purpose }),
    pageSetType: "ENTITY",
  };
  if (!isSafeId(metadata.id)) {
    throw new Error(`Layout ID is not valid: ${metadata.id}`);
  }
  return {
    metadata,
    defaultLayout: readJson(
      path.join(layoutDirectory, "defaultLayout.json"),
      `default layout for ${metadata.id}`
    ),
  };
};

const validateLayoutReferences = (
  layout: Layout,
  sections: Section[]
): void => {
  const sectionIds = new Set(sections.map((section) => section.id));
  for (const componentId of collectComponentIds(layout.defaultLayout)) {
    if (!sectionIds.has(componentId)) {
      throw new Error(
        `Layout ${layout.metadata.id} references missing section ${componentId}`
      );
    }
  }
};

const collectComponentIds = (value: unknown): string[] => {
  if (!value || typeof value !== "object") {
    return [];
  }
  const layout = value as Record<string, unknown>;
  return [
    ...collectComponentList(layout.content),
    ...Object.values(layout.zones ?? {}).flatMap(collectComponentList),
  ];
};

const collectComponentList = (value: unknown): string[] => {
  if (!Array.isArray(value)) {
    return [];
  }
  return value.flatMap((value) => {
    if (!value || typeof value !== "object") {
      return [];
    }
    const component = value as Record<string, unknown>;
    if (typeof component.type !== "string" || !component.props) {
      return [];
    }
    const props = component.props as Record<string, unknown>;
    const slots =
      props.slots && typeof props.slots === "object"
        ? Object.values(props.slots).flatMap(collectComponentList)
        : [];
    const mainContent =
      component.type === "MainContent"
        ? collectComponentList(props.content)
        : [];
    return [
      ...(component.type === "MainContent" ? [] : [component.type]),
      ...slots,
      ...mainContent,
    ];
  });
};

/**
 * Writes temporary Platform compatibility entries for main and the real layout
 * ID. Remove these entries when Platform reads section-library-manifest.json.
 */
const writeLegacyTemplateManifest = (rootDir: string, layout: Layout): void => {
  const manifestPath = path.join(rootDir, ".template-manifest.json");
  if (fs.existsSync(manifestPath)) {
    return;
  }
  const defaultLayoutData = JSON.stringify(layout.defaultLayout);
  fs.writeFileSync(
    manifestPath,
    JSON.stringify(
      {
        templates: [
          {
            name: "main",
            description:
              "Use this template to generate pages for each of your Locations.",
            exampleSiteUrl: "",
            layoutRequired: true,
            defaultLayoutData,
          },
          {
            name: layout.metadata.id,
            description: layout.metadata.displayName,
            exampleSiteUrl: "",
            layoutRequired: true,
            defaultLayoutData,
          },
        ],
      },
      null,
      2
    )
  );
};

const buildConfigSource = (
  rootDir: string,
  sections: ValidatedSection[]
): string => {
  const generatedPath = path.join(
    rootDir,
    "src",
    "library",
    ".generated",
    "libraryConfig.tsx"
  );
  const imports = sections.map((section, index) => {
    const importPath = path
      .relative(
        path.dirname(generatedPath),
        path.join(rootDir, section.sourcePath)
      )
      .replace(/\.(tsx|jsx)$/, "")
      .split(path.sep)
      .join("/");
    const specifier = importPath.startsWith(".")
      ? importPath
      : `./${importPath}`;
    return `import { ${section.id} as Section${index}, config as sectionConfig${index} } from ${JSON.stringify(specifier)};`;
  });
  const entries = sections.map((section, index) => {
    return `  { id: ${JSON.stringify(section.id)}, component: Section${index}, config: sectionConfig${index} },`;
  });
  return sectionLibraryConfigTemplate
    .replace("/* SECTION_LIBRARY_GENERATED_FILE */", GENERATED_FILE_PREFIX)
    .replace("/* SECTION_LIBRARY_IMPORTS */", imports.join("\n"))
    .replace("/* SECTION_LIBRARY_ENTRIES */", entries.join("\n"));
};

const buildRenderTemplateSource = (layoutId: string): string => {
  return [
    GENERATED_FILE_PREFIX,
    'import "@yext/visual-editor/style.css";',
    'import "../index.css";',
    'import { Render, resolveAllData } from "@puckeditor/core";',
    'import { AnalyticsProvider, SchemaWrapper } from "@yext/pages-components";',
    'import { type GetHeadConfig, type GetPath, type HeadConfig, type TagType, type Template, type TemplateProps, type TemplateRenderProps, type TransformProps } from "@yext/pages";',
    'import { applyAnalytics, applyCertifiedFacts, applyHeaderScript, applyTheme, defaultThemeConfig, getCanonicalUrl, getPageMetadata, getSchema, GTMBody, injectTranslations, resolveUrlTemplate, VisualEditorProvider } from "@yext/visual-editor";',
    'import { sectionLibraryConfig } from "../library/.generated/libraryConfig";',
    "",
    `const layoutId = ${JSON.stringify(layoutId)};`,
    "",
    "export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = (data): HeadConfig => {",
    "  const { title, description } = getPageMetadata(data.document);",
    "  const faviconUrl = data.document?._favicon ?? data.document?._site?.favicon?.url;",
    "  return {",
    '    title: title ?? "",',
    '    charset: "UTF-8",',
    '    viewport: "width=device-width, initial-scale=1",',
    "    tags: [",
    '      ...(data.document.siteDomain ? [{ type: "link" as TagType, attributes: { rel: "canonical", href: getCanonicalUrl(data) } }] : []),',
    '      ...(description ? [{ type: "meta" as TagType, attributes: { name: "description", content: description } }] : []),',
    '      ...(faviconUrl ? [{ type: "link" as TagType, attributes: { rel: "icon", type: "image/png", href: faviconUrl } }] : []),',
    "    ],",
    '    other: [applyAnalytics(data.document), applyHeaderScript(data.document), applyTheme(data.document, data.relativePrefixToRoot, defaultThemeConfig), SchemaWrapper(getSchema(data)), applyCertifiedFacts(data.document)].join("\\n"),',
    "  };",
    "};",
    "",
    "export const getPath: GetPath<TemplateProps> = ({ document }) => {",
    '  try { return resolveUrlTemplate(document, ""); } catch { return layoutId; }',
    "};",
    "",
    "export const transformProps: TransformProps<TemplateProps> = async (props) => {",
    "  const layout = props.document.__?.layout;",
    "  if (layout) {",
    "    props.document.__.layout = JSON.stringify(await resolveAllData(JSON.parse(layout), sectionLibraryConfig, { streamDocument: props.document }));",
    "  }",
    "  return { ...props, document: props.document, translations: await injectTranslations(props.document) };",
    "};",
    "",
    "const SectionLibraryLayout: Template<TemplateRenderProps> = (props) => {",
    "  let data = {};",
    '  try { data = JSON.parse(props.document.__?.layout ?? "{}"); } catch { /* Render an empty page when Platform has no layout. */ }',
    "  return (",
    '    <AnalyticsProvider apiKey={props.document?._env?.YEXT_PUBLIC_VISUAL_EDITOR_APP_API_KEY} templateData={props} currency="USD">',
    "      <VisualEditorProvider templateProps={props}>",
    "        <GTMBody><Render config={sectionLibraryConfig} data={data} metadata={{ streamDocument: props.document }} /></GTMBody>",
    "      </VisualEditorProvider>",
    "    </AnalyticsProvider>",
    "  );",
    "};",
    "",
    "export default SectionLibraryLayout;",
    "",
  ].join("\n");
};

const buildEditorTemplateSource = (
  layoutId: string,
  templateId = `edit-${layoutId}`
): string => {
  return [
    GENERATED_FILE_PREFIX,
    'import "@yext/visual-editor/editor.css";',
    'import "../index.css";',
    'import { type GetHeadConfig, type GetPath, type HeadConfig, type TemplateConfig, type TemplateProps, type TemplateRenderProps } from "@yext/pages";',
    'import { applyTheme, defaultThemeConfig, Editor, usePlatformBridgeDocument, usePlatformBridgeEntityFields, VisualEditorProvider } from "@yext/visual-editor";',
    'import tailwindConfig from "../../tailwind.config";',
    'import { sectionLibraryConfig } from "../library/.generated/libraryConfig";',
    "",
    `const editorPath = ${JSON.stringify(templateId === "edit" ? "edit" : `edit/${layoutId}`)};`,
    `const editorName = ${JSON.stringify(templateId)};`,
    "",
    "export const getPath: GetPath<TemplateProps> = () => editorPath;",
    "export const config: TemplateConfig = { name: editorName };",
    "export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = ({ document }): HeadConfig => ({",
    "  title: editorName,",
    '  other: applyTheme(document, "./", defaultThemeConfig),',
    "});",
    "",
    "const Edit = (): JSX.Element => {",
    "  const document = usePlatformBridgeDocument();",
    "  const entityFields = usePlatformBridgeEntityFields();",
    "  return <VisualEditorProvider templateProps={{ document }} entityFields={entityFields} tailwindConfig={tailwindConfig}><Editor document={document} componentRegistry={{ main: sectionLibraryConfig }} themeConfig={defaultThemeConfig} /></VisualEditorProvider>;",
    "};",
    "",
    "export default Edit;",
    "",
  ].join("\n");
};

const writeGeneratedFile = (filePath: string, source: string): boolean => {
  fs.ensureDirSync(path.dirname(filePath));
  if (fs.existsSync(filePath)) {
    return false;
  }
  fs.writeFileSync(filePath, source);
  return true;
};

const readJson = (
  filePath: string,
  description: string
): Record<string, unknown> => {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing ${description} at ${filePath}`);
  }
  try {
    const value: unknown = JSON.parse(fs.readFileSync(filePath, "utf8"));
    if (!value || typeof value !== "object" || Array.isArray(value)) {
      throw new Error("must be a JSON object");
    }
    return value as Record<string, unknown>;
  } catch (error) {
    throw new Error(
      `Could not parse ${description} at ${filePath}: ${error instanceof Error ? error.message : String(error)}`
    );
  }
};

const requireString = (
  value: unknown,
  filePath: string,
  field: string
): string => {
  if (typeof value !== "string") {
    throw new Error(`${filePath} must define a string ${field}`);
  }
  return value;
};

const getOptionalStringListProperty = (
  metadata: Record<string, unknown>,
  name: string,
  filePath: string
): string[] | undefined => {
  const value = metadata[name];
  if (value === undefined) {
    return;
  }
  if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) {
    throw new Error(`${filePath} must define ${name} as a string list`);
  }
  return value;
};

/** Returns true when an ID is safe to use in generated file names and imports. */
const isSafeId = (value: string): boolean => /^[A-Za-z0-9_-]+$/.test(value);
