import path from "node:path";
import fs from "fs-extra";
import sectionLibraryConfigTemplate from "../templates/section-library-config.tsx?raw";
import sectionLibraryEditorTemplate from "../templates/section-library-editor.tsx?raw";
import sectionLibraryRenderTemplate from "../templates/section-library-render.tsx?raw";
import {
  type PageSetType,
  type SectionLibraryLayout,
  type SharedHiddenPuckComponent,
} from "../../types/sectionLibrary.ts";
import { validateLibraryMetadata } from "../../internal/sectionLibraryValidation/stages/api/libraryMetadata.ts";
import { validateSectionLibraryStructure } from "../../internal/sectionLibraryValidation/stages/structure/structure.ts";
import { sortValidationIssues } from "../../internal/sectionLibraryValidation/validateSectionLibrary.ts";
import { SectionLibraryValidationError } from "../../internal/sectionLibraryValidation/validationError.ts";
import type {
  ResolvedSection,
  SectionLibraryTranslationResources,
} from "../../internal/sectionLibraryValidation/types.ts";
import { readBuiltInTranslations } from "../../internal/sectionLibraryValidation/builtInTranslationResources.ts";
import { locales } from "../../utils/i18n/locales.ts";
import {
  mergeTranslationDictionaries,
  type TranslationDictionary,
} from "../../utils/i18n/translationResources.ts";

const GENERATED_FILE_PREFIX =
  "/** THIS FILE IS GENERATED BY THE SECTION LIBRARY PLUGIN */";

/** A Section Library layout and its metadata. */
type Layout = SectionLibraryLayout;

/** Section Library files and metadata generated for a build. */
type GeneratedSectionLibrary = {
  generatedFiles: string[];
  manifestSource?: string;
  layouts: Layout[];
};

/**
 * Generates the temporary Pages source files and build metadata for a Section
 * Library. The files exist only while Vite runs. It returns no files when the
 * starter has no library metadata.
 *
 * 1. Read and validate the library, section, shared-registry, and layout source.
 * 2. Generate one Puck config, Pages render template, and editor template per layout.
 * 3. Write build metadata and return the Section Library artifact manifest.
 */
export const generateSectionLibraryFiles = (
  rootDir: string,
  sectionLibraryRevisionId?: string
): GeneratedSectionLibrary => {
  if (!sectionLibraryRevisionId?.trim()) {
    throw new Error(
      "Section Library builds require SECTION_LIBRARY_REVISION_ID"
    );
  }

  if (!fs.existsSync(path.join(rootDir, "src", "library", "library.json"))) {
    return { generatedFiles: [], layouts: [] };
  }
  const metadataResult = validateLibraryMetadata(rootDir);
  const structureResult = validateSectionLibraryStructure(rootDir);
  const issues = sortValidationIssues([
    ...metadataResult.issues,
    ...structureResult.issues,
  ]);
  const errors = issues.filter((issue) => issue.severity !== "warning");
  if (errors.length > 0) {
    throw new SectionLibraryValidationError(errors);
  }
  for (const warning of issues.filter(
    (issue) => issue.severity === "warning"
  )) {
    console.warn(`${warning.filePath}: ${warning.message}`);
  }
  if (!metadataResult.metadata || !structureResult.structure) {
    throw new Error(
      "Section Library metadata and structure validation did not run."
    );
  }
  const metadata = metadataResult.metadata;
  const structure = structureResult.structure;

  const generatedDirectory = path.join(rootDir, "src", "library", ".generated");
  const generatedTranslations = generateMergedTranslationResources(
    rootDir,
    generatedDirectory,
    structure.translationResources
  );
  const i18nPath = path.join(generatedDirectory, "i18n.ts");
  const generatedFiles = [...generatedTranslations.generatedFiles];
  if (
    writeGeneratedFile(
      i18nPath,
      buildTranslationLoadersSource(
        i18nPath,
        generatedTranslations.resourcePaths
      )
    )
  ) {
    generatedFiles.push(i18nPath);
  }
  generatedFiles.push(
    ...structure.layouts.flatMap((layout) => {
      const configPath = path.join(
        generatedDirectory,
        `libraryConfig-${layout.metadata.id}.tsx`
      );
      return writeGeneratedFile(
        configPath,
        buildConfigSource(
          rootDir,
          layout,
          structure.sections,
          structure.sharedComponents,
          structure.sharedRootPageSetTypes
        )
      )
        ? [configPath]
        : [];
    })
  );

  generatedFiles.push(
    ...structure.layouts.flatMap((layout) => {
      const filePath = path.join(
        rootDir,
        "src",
        "templates",
        `${layout.metadata.id}.tsx`
      );
      return writeGeneratedFile(filePath, buildRenderTemplateSource(layout))
        ? [filePath]
        : [];
    })
  );
  generatedFiles.push(
    ...structure.layouts.flatMap((layout) => {
      const filePath = path.join(
        rootDir,
        "src",
        "templates",
        `edit-${layout.metadata.id}.tsx`
      );
      return writeGeneratedFile(
        filePath,
        buildEditorTemplateSource(
          [[layout.metadata.id, layout]],
          `edit/${layout.metadata.id}/${encodeURIComponent(sectionLibraryRevisionId)}`,
          `edit-${layout.metadata.id}`
        )
      )
        ? [filePath]
        : [];
    })
  );
  writeTemplateManifest(rootDir, structure.layouts);

  return {
    generatedFiles,
    layouts: structure.layouts,
    manifestSource: `${JSON.stringify(
      {
        schemaVersion: 1,
        library: metadata,
        layouts: structure.layouts.map((layout) => ({
          ...layout.metadata,
          templateId: layout.metadata.id,
          editorPath: `edit/${layout.metadata.id}/${encodeURIComponent(sectionLibraryRevisionId)}`,
          defaultLayout: layout.defaultLayout,
        })),
      },
      null,
      2
    )}\n`,
  };
};

const buildTranslationLoadersSource = (
  generatedPath: string,
  resources: SectionLibraryTranslationResources
): string => {
  const buildEntries = (resourcePaths: Record<string, string>): string =>
    Object.entries(resourcePaths)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([locale, resourcePath]) => {
        const relativePath = path
          .relative(path.dirname(generatedPath), resourcePath)
          .split(path.sep)
          .join("/");
        const specifier = relativePath.startsWith(".")
          ? relativePath
          : `./${relativePath}`;
        return `  ${JSON.stringify(locale)}: () => import(${JSON.stringify(specifier)}).then(({ default: translations }) => translations),`;
      })
      .join("\n");

  return [
    GENERATED_FILE_PREFIX,
    'import type { SectionLibraryTranslationLoaders } from "@yext/visual-editor";',
    "",
    "export const translationLoaders: SectionLibraryTranslationLoaders = {",
    "  platform: {",
    buildEntries(resources.platform),
    "  },",
    "  page: {",
    buildEntries(resources.page),
    "  },",
    "};",
    "",
  ].join("\n");
};

const generateMergedTranslationResources = (
  rootDir: string,
  generatedDirectory: string,
  repoResources: SectionLibraryTranslationResources
): {
  generatedFiles: string[];
  resourcePaths: SectionLibraryTranslationResources;
} => {
  const generatedFiles: string[] = [];
  const resourcePaths: SectionLibraryTranslationResources = {
    platform: {},
    page: {},
  };

  for (const locale of locales) {
    for (const [resourceKind, builtInKind] of [
      ["platform", "platform"],
      ["page", "page"],
    ] as const) {
      const builtIn = readBuiltInTranslations(builtInKind, locale);
      if (!builtIn) {
        throw new Error(
          `Could not find built-in ${resourceKind} translations for ${locale}.`
        );
      }
      const repoPath = repoResources[resourceKind][locale];
      const repo = repoPath
        ? (JSON.parse(
            fs.readFileSync(path.join(rootDir, repoPath), "utf8")
          ) as TranslationDictionary)
        : undefined;
      const translations = repo
        ? mergeTranslationDictionaries(builtIn, repo)
        : builtIn;
      const generatedPath = path.join(
        generatedDirectory,
        "i18n",
        builtInKind,
        `${locale}.ts`
      );
      const source = [
        GENERATED_FILE_PREFIX,
        `const translations = ${JSON.stringify(sortTranslationDictionary(translations), null, 2)};`,
        "export default translations;",
        "",
      ].join("\n");
      if (!writeGeneratedFile(generatedPath, source)) {
        throw new Error(
          `Refusing to overwrite translation resource at ${generatedPath}.`
        );
      }
      generatedFiles.push(generatedPath);
      resourcePaths[resourceKind][locale] = generatedPath;
    }
  }

  return { generatedFiles, resourcePaths };
};

const sortTranslationDictionary = (
  translations: TranslationDictionary
): TranslationDictionary =>
  Object.fromEntries(
    Object.entries(translations)
      .sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0))
      .map(([key, value]) => [
        key,
        typeof value === "string" ? value : sortTranslationDictionary(value),
      ])
  );

export const cleanupGeneratedSectionLibraryFiles = (
  generatedFiles: string[]
): void => {
  const generatedDirectories = new Set<string>();
  for (const filePath of generatedFiles) {
    fs.removeSync(filePath);
    let directory = path.dirname(filePath);
    generatedDirectories.add(directory);
    while (
      directory.includes(`${path.sep}.generated${path.sep}`) &&
      path.basename(directory) !== ".generated"
    ) {
      directory = path.dirname(directory);
      generatedDirectories.add(directory);
    }
    if (filePath.endsWith(".tsx")) {
      fs.removeSync(filePath.replace(/\.tsx$/, ".client.tsx"));
    }
  }
  for (const directory of [...generatedDirectories].sort(
    (left, right) => right.length - left.length
  )) {
    if (fs.existsSync(directory) && fs.readdirSync(directory).length === 0) {
      fs.removeSync(directory);
    }
  }
};

/**
 * Marks generated layout render templates as in-platform templates so the
 * Pages build does not also expose them as features in features.json.
 */
const writeTemplateManifest = (rootDir: string, layouts: Layout[]): void => {
  const manifestPath = path.join(rootDir, ".template-manifest.json");
  const source = JSON.stringify(
    {
      templates: layouts.map((layout) => ({
        name: layout.metadata.id,
        description: layout.metadata.displayName,
        exampleSiteUrl: "",
        layoutRequired: true,
        defaultLayoutData: JSON.stringify(layout.defaultLayout),
      })),
    },
    null,
    2
  );
  if (
    !fs.existsSync(manifestPath) ||
    fs.readFileSync(manifestPath, "utf8") !== source
  ) {
    fs.writeFileSync(manifestPath, source);
  }
};

const buildConfigSource = (
  rootDir: string,
  layout: Layout,
  sections: ResolvedSection[],
  sharedComponents: SharedHiddenPuckComponent[],
  sharedRootPageSetTypes: PageSetType[]
): string => {
  const layoutId = layout.metadata.id;
  const generatedPath = path.join(
    rootDir,
    "src",
    "library",
    ".generated",
    `libraryConfig-${layoutId}.tsx`
  );
  const supportedSections = sections.filter((section) => {
    return section.pageSetTypes.includes(layout.metadata.pageSetType);
  });
  const imports = supportedSections.map((section, index) => {
    const importPath = path
      .relative(
        path.dirname(generatedPath),
        path.join(rootDir, section.sourcePath)
      )
      .replace(/\.(tsx|jsx)$/, "")
      .split(path.sep)
      .join("/");
    const specifier = importPath.startsWith(".")
      ? importPath
      : `./${importPath}`;
    return `import { ${section.componentName} as Section${index}, config as sectionConfig${index} } from ${JSON.stringify(specifier)};`;
  });
  const entries = supportedSections.map((section, index) => {
    return `  { id: ${JSON.stringify(section.id)}, component: Section${index}, config: sectionConfig${index} },`;
  });
  const categories = buildCategorySource(supportedSections);
  const hasSharedComponentRegistry =
    sharedComponents.some((component) => {
      return component.pageSetTypes.includes(layout.metadata.pageSetType);
    }) || sharedRootPageSetTypes.includes(layout.metadata.pageSetType);
  return sectionLibraryConfigTemplate
    .replace("/* SECTION_LIBRARY_GENERATED_FILE */", GENERATED_FILE_PREFIX)
    .replace("/* SECTION_LIBRARY_IMPORTS */", imports.join("\n"))
    .replace("/* SECTION_LIBRARY_ENTRIES */", entries.join("\n"))
    .replace("/* SECTION_LIBRARY_CATEGORIES */", categories)
    .replace(
      "/* SECTION_LIBRARY_SHARED_COMPONENT_REGISTRY */",
      hasSharedComponentRegistry
        ? 'import { sharedComponentConfigs, sharedComponentMetadata, sharedRootAllowedComponentIds, sharedRootConfigs } from "../shared/componentRegistry";'
        : 'const sharedComponentMetadata: { id: string; pageSetTypes: string[] }[] = [];\nconst sharedComponentConfigs: Config["components"] = {};\nconst sharedRootAllowedComponentIds: Partial<Record<string, string[]>> = {};\nconst sharedRootConfigs: Partial<Record<string, NonNullable<Config["root"]>>> = {};'
    )
    .replace(
      "__SECTION_LIBRARY_PAGE_SET_TYPE__",
      JSON.stringify(layout.metadata.pageSetType)
    )
    .replace(
      "__SECTION_LIBRARY_HAS_SHARED_COMPONENT_REGISTRY__",
      hasSharedComponentRegistry ? "true" : "false"
    );
};

const buildCategorySource = (sections: ResolvedSection[]): string => {
  const categories = new Map<string, { title: string; componentIds: string[] }>(
    [["other", { title: "Other", componentIds: ["CustomCodeSection"] }]]
  );

  for (const section of sections) {
    const title = section.category ?? "Sections";
    const normalizedTitle = title.toLowerCase();
    const category = categories.get(normalizedTitle);
    if (category) {
      category.componentIds.push(section.id);
    } else {
      categories.set(normalizedTitle, {
        title,
        componentIds: [section.id],
      });
    }
  }

  return [...categories.entries()]
    .map(([normalizedTitle, category]) => {
      const categoryId =
        normalizedTitle === "other"
          ? normalizedTitle
          : `section:${category.title}`;
      const propertyName =
        categoryId === "other" ? categoryId : JSON.stringify(categoryId);
      return `    ${propertyName}: { title: ${JSON.stringify(category.title)}, components: ${JSON.stringify(category.componentIds)} },`;
    })
    .join("\n");
};

const buildRenderTemplateSource = (layout: Layout): string => {
  const configPath = `../library/.generated/libraryConfig-${layout.metadata.id}`;
  const mapboxImport =
    layout.metadata.pageSetType === "LOCATOR"
      ? 'import mapboxPackageJson from "mapbox-gl/package.json";'
      : "";
  const mapboxAssets =
    layout.metadata.pageSetType === "LOCATOR"
      ? `<><script id="mapbox-script" src={\`https://api.mapbox.com/mapbox-gl-js/v\${mapboxPackageJson.version}/mapbox-gl.js\`} /><link id="mapbox-stylesheet" rel="stylesheet" href={\`https://api.mapbox.com/mapbox-gl-js/v\${mapboxPackageJson.version}/mapbox-gl.css\`} /></>`
      : "";
  return sectionLibraryRenderTemplate
    .replace("/* SECTION_LIBRARY_GENERATED_FILE */", GENERATED_FILE_PREFIX)
    .replace(
      '"__SECTION_LIBRARY_LAYOUT_ID__"',
      JSON.stringify(layout.metadata.id)
    )
    .replace('"__SECTION_LIBRARY_CONFIG_PATH__"', JSON.stringify(configPath))
    .replace("/* SECTION_LIBRARY_MAPBOX_IMPORT */", mapboxImport)
    .replace("{/* SECTION_LIBRARY_MAPBOX_ASSETS */}", mapboxAssets);
};

const buildEditorTemplateSource = (
  entries: [string, Layout][],
  editorPath: string = "edit",
  editorName: string = "edit"
): string => {
  const registry = entries
    .map(([name, entry]) => {
      const configPath = `../library/.generated/libraryConfig-${entry.metadata.id}`;
      return `  ${JSON.stringify(name)}: () => import(${JSON.stringify(configPath)}).then(({ sectionLibraryConfig }) => sectionLibraryConfig),`;
    })
    .join("\n");
  return sectionLibraryEditorTemplate
    .replace("/* SECTION_LIBRARY_GENERATED_FILE */", GENERATED_FILE_PREFIX)
    .replace("/* SECTION_LIBRARY_CONFIG_IMPORTS */", "")
    .replace("/* SECTION_LIBRARY_COMPONENT_REGISTRY */", registry)
    .replace('"__SECTION_LIBRARY_EDITOR_PATH__"', JSON.stringify(editorPath))
    .replace('"__SECTION_LIBRARY_EDITOR_NAME__"', JSON.stringify(editorName));
};

const writeGeneratedFile = (filePath: string, source: string): boolean => {
  fs.ensureDirSync(path.dirname(filePath));
  if (fs.existsSync(filePath)) {
    const existingSource = fs.readFileSync(filePath, "utf8");
    if (!existingSource.startsWith(GENERATED_FILE_PREFIX)) {
      return false;
    }
    if (existingSource === source) {
      return true;
    }
  }
  fs.writeFileSync(filePath, source);
  return true;
};
