import os from "node:os";
import path from "node:path";
import fs from "fs-extra";
import { afterEach, describe, expect, it } from "vitest";
import {
  cleanupGeneratedSectionLibraryFiles,
  generateSectionLibraryFiles,
} from "./sectionLibraryGenerator.ts";

const tempRoots: string[] = [];

afterEach(() => {
  for (const rootDir of tempRoots.splice(0)) {
    fs.removeSync(rootDir);
  }
});

describe("generateSectionLibraryFiles", () => {
  it("maps all layouts to current Platform templates", () => {
    const rootDir = createLibrary();

    const result = generateSectionLibraryFiles(rootDir);

    expect(result.generatedFiles).toHaveLength(10);
    const config = fs.readFileSync(
      path.join(
        rootDir,
        "src",
        "library",
        ".generated",
        "libraryConfig-location.tsx"
      ),
      "utf8"
    );
    expect(config).toContain("label: section.config.displayName");
    expect(config).toContain("toPuckFields");
    expect(config).toContain('typeof section.component === "function"');
    expect(config).toContain(": section.component.render");
    expect(config).toContain("...section.config");
    expect(config).toContain('id: "hero"');
    expect(config).toContain("import { Hero as Section0");
    expect(config).toContain('components: ["MainContent"]');
    expect(config).not.toContain("mainConfig");
    expect(config).not.toContain("directoryConfig");
    expect(config).not.toContain("locatorConfig");
    expect(config).not.toContain("Object.groupBy");
    expect(config).not.toContain("../shared/componentRegistry");
    const directoryConfig = fs.readFileSync(
      path.join(
        rootDir,
        "src",
        "library",
        ".generated",
        "libraryConfig-directory-layout.tsx"
      ),
      "utf8"
    );
    expect(directoryConfig).toContain('id: "Directory"');
    expect(directoryConfig).toContain("sharedComponentMetadata.filter");
    expect(directoryConfig).not.toContain('id: "Locator"');
    const locatorConfig = fs.readFileSync(
      path.join(
        rootDir,
        "src",
        "library",
        ".generated",
        "libraryConfig-locator-layout.tsx"
      ),
      "utf8"
    );
    expect(locatorConfig).toContain('id: "Locator"');
    expect(locatorConfig).toContain("sharedComponentMetadata.filter");
    expect(locatorConfig).not.toContain('id: "Directory"');
    const mainTemplate = fs.readFileSync(
      path.join(rootDir, "src", "templates", "main.tsx"),
      "utf8"
    );
    expect(mainTemplate).toMatch(
      /^\/\*\* THIS FILE IS GENERATED BY THE SECTION LIBRARY PLUGIN \*\//
    );
    expect(mainTemplate).toContain('const layoutId = "location"');
    expect(
      fs.existsSync(path.join(rootDir, "src", "templates", "location.tsx"))
    ).toBe(false);
    const locationEditorTemplate = fs.readFileSync(
      path.join(rootDir, "src", "templates", "edit-location.tsx"),
      "utf8"
    );
    expect(locationEditorTemplate).toContain(
      'const editorPath = "edit/location"'
    );
    expect(locationEditorTemplate).toContain(
      '"location": () => import("../library/.generated/libraryConfig-location")'
    );
    expect(locationEditorTemplate).not.toContain("directory-layout");
    expect(locationEditorTemplate).not.toContain("locator-layout");
    const directoryEditorTemplate = fs.readFileSync(
      path.join(rootDir, "src", "templates", "edit-directory-layout.tsx"),
      "utf8"
    );
    expect(directoryEditorTemplate).toContain(
      'const editorPath = "edit/directory-layout"'
    );
    expect(directoryEditorTemplate).toContain(
      '"directory-layout": () => import("../library/.generated/libraryConfig-directory-layout")'
    );
    expect(directoryEditorTemplate).not.toContain("libraryConfig-location");
    expect(directoryEditorTemplate).not.toContain(
      "libraryConfig-locator-layout"
    );
    const locatorEditorTemplate = fs.readFileSync(
      path.join(rootDir, "src", "templates", "edit-locator-layout.tsx"),
      "utf8"
    );
    expect(locatorEditorTemplate).toContain(
      'const editorPath = "edit/locator-layout"'
    );
    expect(locatorEditorTemplate).toContain(
      '"locator-layout": () => import("../library/.generated/libraryConfig-locator-layout")'
    );
    expect(locatorEditorTemplate).not.toContain("libraryConfig-location");
    expect(locatorEditorTemplate).not.toContain(
      "libraryConfig-directory-layout"
    );
    const legacyEditorTemplate = fs.readFileSync(
      path.join(rootDir, "src", "templates", "edit.tsx"),
      "utf8"
    );
    expect(legacyEditorTemplate).toContain('const editorName = "edit"');
    expect(legacyEditorTemplate).toContain(
      '"location": () => import("../library/.generated/libraryConfig-location")'
    );
    expect(legacyEditorTemplate).toContain(
      '"directory-layout": () => import("../library/.generated/libraryConfig-directory-layout")'
    );
    expect(legacyEditorTemplate).toContain(
      '"locator-layout": () => import("../library/.generated/libraryConfig-locator-layout")'
    );
    expect(legacyEditorTemplate).not.toContain("import { sectionLibraryConfig");
    expect(
      fs.readJsonSync(path.join(rootDir, ".template-manifest.json"))
    ).toEqual({
      templates: [
        expect.objectContaining({
          name: "main",
          defaultLayoutData: expect.any(String),
        }),
        expect.objectContaining({
          name: "directory",
          defaultLayoutData: expect.any(String),
        }),
        expect.objectContaining({
          name: "locator",
          defaultLayoutData: expect.any(String),
        }),
      ],
    });
    expect(
      JSON.parse(
        fs.readJsonSync(path.join(rootDir, ".template-manifest.json"))
          .templates[0].defaultLayoutData
      )
    ).toEqual(
      expect.objectContaining({
        root: expect.objectContaining({
          props: expect.objectContaining({ version: 73 }),
        }),
      })
    );
    expect(result.manifestSource).toContain('"templateId": "main"');
    expect(result.manifestSource).toContain('"templateId": "directory"');
    expect(result.manifestSource).toContain('"templateId": "locator"');
    expect(result.manifestSource).toContain('"editorPath": "edit/location"');
    expect(result.manifestSource).toContain(
      '"editorPath": "edit/directory-layout"'
    );
    expect(result.manifestSource).toContain(
      '"editorPath": "edit/locator-layout"'
    );
    expect(result.manifestSource).toContain(
      '"vertical": [\n        "RETAIL"\n      ]'
    );
    expect(result.manifestSource).toContain(
      '"purpose": [\n        "LOCATION"\n      ]'
    );
  });

  it("replaces a compatibility manifest from an earlier library structure", () => {
    const rootDir = createLibrary();
    fs.writeJsonSync(path.join(rootDir, ".template-manifest.json"), {
      templates: [{ name: "main" }],
    });

    generateSectionLibraryFiles(rootDir);

    expect(
      fs
        .readJsonSync(path.join(rootDir, ".template-manifest.json"))
        .templates.map(({ name }: { name: string }) => name)
    ).toEqual(["main", "directory", "locator"]);
  });

  it("generates render templates that resolve URLs and require valid layout data", () => {
    const rootDir = createLibrary();

    generateSectionLibraryFiles(rootDir);

    const renderTemplate = fs.readFileSync(
      path.join(rootDir, "src", "templates", "main.tsx"),
      "utf8"
    );
    expect(renderTemplate).toContain(
      "return resolveUrlTemplate(document, relativePrefixToRoot);"
    );
    expect(renderTemplate).not.toContain("return layoutId;");
    expect(renderTemplate).toContain(
      "Section Library layout ${layoutId} is missing layout data"
    );
    expect(renderTemplate).toContain(
      "Section Library layout ${layoutId} has invalid layout data"
    );
  });

  it("does not remove a handwritten template", () => {
    const rootDir = createLibrary();
    const handwrittenMainPath = path.join(
      rootDir,
      "src",
      "templates",
      "main.tsx"
    );
    fs.ensureDirSync(path.dirname(handwrittenMainPath));
    fs.writeFileSync(handwrittenMainPath, "export default null;");

    const { generatedFiles } = generateSectionLibraryFiles(rootDir);
    cleanupGeneratedSectionLibraryFiles(generatedFiles);

    expect(fs.readFileSync(handwrittenMainPath, "utf8")).toBe(
      "export default null;"
    );
    expect(generatedFiles).toHaveLength(9);
    for (const filePath of generatedFiles) {
      expect(fs.existsSync(filePath)).toBe(false);
    }
    expect(fs.existsSync(path.join(rootDir, ".template-manifest.json"))).toBe(
      true
    );
  });

  it("replaces and removes generated templates from an earlier run", () => {
    const rootDir = createLibrary();

    generateSectionLibraryFiles(rootDir);
    const { generatedFiles } = generateSectionLibraryFiles(rootDir);
    fs.writeFileSync(
      path.join(rootDir, "src", "templates", "edit-location.client.tsx"),
      ""
    );
    cleanupGeneratedSectionLibraryFiles(generatedFiles);

    expect(
      fs.existsSync(path.join(rootDir, "src", "templates", "main.tsx"))
    ).toBe(false);
    expect(
      fs.existsSync(path.join(rootDir, "src", "templates", "main.client.tsx"))
    ).toBe(false);
    expect(
      fs.existsSync(path.join(rootDir, "src", "templates", "edit-location.tsx"))
    ).toBe(false);
    expect(
      fs.existsSync(
        path.join(rootDir, "src", "templates", "edit-location.client.tsx")
      )
    ).toBe(false);
  });

  it("does not generate files without library metadata", () => {
    const rootDir = createLibrary();
    fs.removeSync(path.join(rootDir, "src", "library", "library.json"));

    expect(generateSectionLibraryFiles(rootDir)).toEqual({
      generatedFiles: [],
      layouts: [],
    });
    expect(
      fs.existsSync(
        path.join(
          rootDir,
          "src",
          "library",
          ".generated",
          "libraryConfig-location.tsx"
        )
      )
    ).toBe(false);
    expect(
      fs.existsSync(path.join(rootDir, "src", "templates", "main.tsx"))
    ).toBe(false);
  });

  it("rejects the layout ID reserved for the editor template", () => {
    const rootDir = createLibrary();
    fs.writeJsonSync(
      path.join(
        rootDir,
        "src",
        "library",
        "layouts",
        "location",
        "metadata.json"
      ),
      {
        id: "edit",
        displayName: "Edit",
        previewImageUrl: "",
        pageSetType: "ENTITY",
      }
    );

    expect(() => generateSectionLibraryFiles(rootDir)).toThrow(
      /edit because it is reserved for a generated template/
    );
    expect(
      fs.existsSync(
        path.join(
          rootDir,
          "src",
          "library",
          ".generated",
          "libraryConfig-location.tsx"
        )
      )
    ).toBe(false);
    expect(
      fs.existsSync(path.join(rootDir, "src", "templates", "edit.tsx"))
    ).toBe(false);
  });

  it("reads JSX sections", () => {
    const rootDir = createLibrary();
    const sectionsDirectory = path.join(rootDir, "src", "library", "sections");
    fs.removeSync(path.join(sectionsDirectory, "Hero.tsx"));
    fs.writeFileSync(
      path.join(sectionsDirectory, "Hero.jsx"),
      'export const Hero = () => <section />;\nexport const config = { id: "hero", displayName: "Hero", description: "A hero.", pageSetTypes: ["ENTITY"] };'
    );

    generateSectionLibraryFiles(rootDir);

    expect(
      fs.readFileSync(
        path.join(
          rootDir,
          "src",
          "library",
          ".generated",
          "libraryConfig-location.tsx"
        ),
        "utf8"
      )
    ).toContain('from "../sections/Hero"');
  });

  it("reads indirect component and config exports", () => {
    const rootDir = createLibrary();
    fs.writeFileSync(
      path.join(rootDir, "src", "library", "sections", "Hero.tsx"),
      [
        'import type { SectionConfig } from "@yext/visual-editor";',
        "const HeroComponent = () => <section />;",
        'const heroConfig: SectionConfig = { id: "hero", displayName: "Hero", description: "A hero.", pageSetTypes: ["ENTITY"] };',
        "export { HeroComponent as Hero, heroConfig as config };",
      ].join("\n")
    );

    generateSectionLibraryFiles(rootDir);

    expect(
      fs.readFileSync(
        path.join(
          rootDir,
          "src",
          "library",
          ".generated",
          "libraryConfig-location.tsx"
        ),
        "utf8"
      )
    ).toContain("import { Hero as Section0");
  });

  it("uses the config ID after a section file is renamed", () => {
    const rootDir = createLibrary();
    const sectionsDirectory = path.join(rootDir, "src", "library", "sections");
    fs.removeSync(path.join(sectionsDirectory, "Hero.tsx"));
    fs.writeFileSync(
      path.join(sectionsDirectory, "NewHero.tsx"),
      [
        'import type { SectionConfig } from "@yext/visual-editor";',
        "export const NewHero = {};",
        'export const config: SectionConfig = { id: "hero", displayName: "Hero", description: "A hero.", pageSetTypes: ["ENTITY"] };',
      ].join("\n")
    );

    generateSectionLibraryFiles(rootDir);

    const config = fs.readFileSync(
      path.join(
        rootDir,
        "src",
        "library",
        ".generated",
        "libraryConfig-location.tsx"
      ),
      "utf8"
    );
    expect(config).toContain('from "../sections/NewHero"');
    expect(config).toContain("import { NewHero as Section0");
    expect(config).toContain('id: "hero"');
  });

  it.each([
    {
      name: "missing config",
      update: (rootDir: string): void => {
        fs.writeFileSync(
          path.join(rootDir, "src", "library", "sections", "Hero.tsx"),
          "export const Hero = {};"
        );
      },
      error: /must export 'config'/,
    },
    {
      name: "missing component export",
      update: (rootDir: string): void => {
        fs.writeFileSync(
          path.join(rootDir, "src", "library", "sections", "Hero.tsx"),
          'export const config = { displayName: "Hero", description: "Hero", pageSetTypes: ["ENTITY"] };'
        );
      },
      error: /must export 'Hero'/,
    },
    {
      name: "untyped config",
      update: (rootDir: string): void => {
        fs.writeFileSync(
          path.join(rootDir, "src", "library", "sections", "Hero.tsx"),
          'export const Hero = {};\nexport const config = { displayName: "Hero", description: "Hero", pageSetTypes: ["ENTITY"] };'
        );
      },
      error: /must use the SectionConfig type/,
    },
    {
      name: "missing section ID",
      update: (rootDir: string): void => {
        fs.writeFileSync(
          path.join(rootDir, "src", "library", "sections", "Hero.tsx"),
          [
            'import type { SectionConfig } from "@yext/visual-editor";',
            "export const Hero = {};",
            'export const config: SectionConfig = { displayName: "Hero", description: "Hero", pageSetTypes: ["ENTITY"] };',
          ].join("\n")
        );
      },
      error: /must define a valid id/,
    },
    {
      name: "empty section ID",
      update: (rootDir: string): void => {
        fs.writeFileSync(
          path.join(rootDir, "src", "library", "sections", "Hero.tsx"),
          [
            'import type { SectionConfig } from "@yext/visual-editor";',
            "export const Hero = {};",
            'export const config: SectionConfig = { id: "", displayName: "Hero", description: "Hero", pageSetTypes: ["ENTITY"] };',
          ].join("\n")
        );
      },
      error: /must define a valid id/,
    },
    {
      name: "unsafe section ID",
      update: (rootDir: string): void => {
        fs.writeFileSync(
          path.join(rootDir, "src", "library", "sections", "Hero.tsx"),
          [
            'import type { SectionConfig } from "@yext/visual-editor";',
            "export const Hero = {};",
            'export const config: SectionConfig = { id: "invalid id", displayName: "Hero", description: "Hero", pageSetTypes: ["ENTITY"] };',
          ].join("\n")
        );
      },
      error: /must define a valid id/,
    },
    {
      name: "non-string page set type",
      update: (rootDir: string): void => {
        fs.writeFileSync(
          path.join(rootDir, "src", "library", "sections", "Hero.tsx"),
          [
            'import type { SectionConfig } from "@yext/visual-editor";',
            "export const Hero = {};",
            'export const config: SectionConfig = { id: "hero", displayName: "Hero", description: "Hero", pageSetTypes: [1] };',
          ].join("\n")
        );
      },
      error: /must contain only ENTITY, DIRECTORY, or LOCATOR/,
    },
    {
      name: "unsupported page set type",
      update: (rootDir: string): void => {
        fs.writeFileSync(
          path.join(rootDir, "src", "library", "sections", "Hero.tsx"),
          [
            'import type { SectionConfig } from "@yext/visual-editor";',
            "export const Hero = {};",
            'export const config: SectionConfig = { id: "hero", displayName: "Hero", description: "Hero", pageSetTypes: ["ALL"] };',
          ].join("\n")
        );
      },
      error: /must contain only ENTITY, DIRECTORY, or LOCATOR/,
    },
    {
      name: "duplicate section ID",
      update: (rootDir: string): void => {
        fs.writeFileSync(
          path.join(rootDir, "src", "library", "sections", "SecondHero.tsx"),
          [
            'import type { SectionConfig } from "@yext/visual-editor";',
            "export const SecondHero = {};",
            'export const config: SectionConfig = { id: "hero", displayName: "Second Hero", description: "Another hero.", pageSetTypes: ["ENTITY"] };',
          ].join("\n")
        );
      },
      error: /Section ID is not unique: hero/,
    },
    {
      name: "invalid library metadata",
      update: (rootDir: string): void => {
        fs.writeJsonSync(path.join(rootDir, "src", "library", "library.json"), {
          schemaVersion: 2,
          id: "library",
          displayName: "Library",
          description: "A test library.",
        });
      },
      error: /must set schemaVersion to 1/,
    },
    {
      name: "unsupported layout vertical",
      update: (rootDir: string): void => {
        fs.writeJsonSync(
          path.join(
            rootDir,
            "src",
            "library",
            "layouts",
            "location",
            "metadata.json"
          ),
          {
            id: "location",
            displayName: "Location",
            previewImageUrl: "",
            vertical: ["UNKNOWN"],
            pageSetType: "ENTITY",
          }
        );
      },
      error: /vertical as a list of supported values/,
    },
    {
      name: "nested sections",
      update: (rootDir: string): void => {
        fs.ensureDirSync(
          path.join(rootDir, "src", "library", "sections", "nested")
        );
      },
      error: /Section directories are not supported/,
    },
    {
      name: "missing Entity layout",
      update: (rootDir: string): void => {
        fs.writeJsonSync(
          path.join(
            rootDir,
            "src",
            "library",
            "layouts",
            "location",
            "metadata.json"
          ),
          {
            id: "location",
            displayName: "Location",
            previewImageUrl: "",
            pageSetType: "DIRECTORY",
          }
        );
      },
      error: /requires one ENTITY, one DIRECTORY, and one LOCATOR layout/,
    },
    {
      name: "missing layout section",
      update: (rootDir: string): void => {
        fs.writeJsonSync(
          path.join(
            rootDir,
            "src",
            "library",
            "layouts",
            "location",
            "defaultLayout.json"
          ),
          {
            root: { props: {} },
            content: [{ type: "Missing", props: { id: "missing-default" } }],
            zones: {},
          }
        );
      },
      error: /references missing or incompatible section Missing/,
    },
    {
      name: "missing nested layout component ID",
      update: (rootDir: string): void => {
        fs.writeJsonSync(
          path.join(
            rootDir,
            "src",
            "library",
            "layouts",
            "location",
            "defaultLayout.json"
          ),
          {
            root: { props: {} },
            content: [
              {
                type: "MainContent",
                props: {
                  id: "main-content-default",
                  content: [{ type: "hero", props: {} }],
                },
              },
            ],
            zones: {},
          }
        );
      },
      error: /component hero must define an ID/,
    },
    {
      name: "duplicate layout component ID",
      update: (rootDir: string): void => {
        fs.writeJsonSync(
          path.join(
            rootDir,
            "src",
            "library",
            "layouts",
            "location",
            "defaultLayout.json"
          ),
          {
            root: { props: {} },
            content: [
              { type: "hero", props: { id: "hero-default" } },
              { type: "hero", props: { id: "hero-default" } },
            ],
            zones: {},
          }
        );
      },
      error: /component ID is not unique: hero-default/,
    },
  ])("rejects $name", ({ update, error }) => {
    const rootDir = createLibrary();
    update(rootDir);

    expect(() => generateSectionLibraryFiles(rootDir)).toThrow(error);
  });

  it("does not rewrite unchanged generated files", () => {
    const rootDir = createLibrary();
    const { generatedFiles } = generateSectionLibraryFiles(rootDir);
    const generatedPaths = [
      ...generatedFiles,
      path.join(rootDir, ".template-manifest.json"),
    ];
    const modifiedTime = new Date("2000-01-01T00:00:00.000Z");

    generatedPaths.forEach((generatedPath) => {
      fs.utimesSync(generatedPath, modifiedTime, modifiedTime);
    });
    generateSectionLibraryFiles(rootDir);

    generatedPaths.forEach((generatedPath) => {
      expect(fs.statSync(generatedPath).mtime).toEqual(modifiedTime);
    });
  });
});

const createLibrary = (): string => {
  const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), "section-library-"));
  tempRoots.push(rootDir);
  const libraryDirectory = path.join(rootDir, "src", "library");
  fs.ensureDirSync(path.join(libraryDirectory, "sections"));
  fs.ensureDirSync(path.join(libraryDirectory, "layouts", "location"));
  fs.ensureDirSync(path.join(libraryDirectory, "layouts", "directory-layout"));
  fs.ensureDirSync(path.join(libraryDirectory, "layouts", "locator-layout"));
  fs.ensureDirSync(path.join(libraryDirectory, "shared"));
  fs.writeJsonSync(path.join(libraryDirectory, "library.json"), {
    schemaVersion: 1,
    id: "library",
    displayName: "Library",
    description: "A test library.",
  });
  fs.writeFileSync(
    path.join(libraryDirectory, "sections", "Hero.tsx"),
    [
      'import type { SectionConfig } from "@yext/visual-editor";',
      "export const Hero = {};",
      'export const config: SectionConfig = { id: "hero", displayName: "Hero", description: "A hero.", pageSetTypes: ["ENTITY"], category: "Content" };',
    ].join("\n")
  );
  fs.writeFileSync(
    path.join(libraryDirectory, "sections", "Directory.tsx"),
    [
      'import type { SectionConfig } from "@yext/visual-editor";',
      "export const Directory = {};",
      'export const config: SectionConfig = { id: "Directory", displayName: "Directory", description: "A directory.", pageSetTypes: ["DIRECTORY"], category: "Directory" };',
    ].join("\n")
  );
  fs.writeFileSync(
    path.join(libraryDirectory, "sections", "Locator.tsx"),
    [
      'import type { SectionConfig } from "@yext/visual-editor";',
      "export const Locator = {};",
      'export const config: SectionConfig = { id: "Locator", displayName: "Locator", description: "A locator.", pageSetTypes: ["LOCATOR"], category: "Locator" };',
    ].join("\n")
  );
  fs.writeFileSync(
    path.join(libraryDirectory, "shared", "componentRegistry.ts"),
    [
      "export const sharedComponentMetadata = [",
      '  { id: "directory-header", pageSetTypes: ["DIRECTORY"] },',
      '  { id: "locator-helper", pageSetTypes: ["LOCATOR"] },',
      "];",
      "export const sharedComponentConfigs = {};",
      "export const sharedRootConfigs = {};",
      "export const sharedRootAllowedComponentIds = {};",
      'export const sharedRootPageSetTypes = ["DIRECTORY", "LOCATOR"] as const;',
    ].join("\n")
  );
  fs.writeJsonSync(
    path.join(libraryDirectory, "layouts", "location", "metadata.json"),
    {
      id: "location",
      displayName: "Location",
      previewImageUrl: "",
      vertical: ["RETAIL"],
      purpose: ["LOCATION"],
      pageSetType: "ENTITY",
    }
  );
  fs.writeJsonSync(
    path.join(libraryDirectory, "layouts", "location", "defaultLayout.json"),
    {
      root: { props: { version: 73 } },
      content: [{ type: "hero", props: { id: "hero-default" } }],
      zones: {},
    }
  );
  fs.writeJsonSync(
    path.join(libraryDirectory, "layouts", "directory-layout", "metadata.json"),
    {
      id: "directory-layout",
      displayName: "Directory",
      pageSetType: "DIRECTORY",
    }
  );
  fs.writeJsonSync(
    path.join(
      libraryDirectory,
      "layouts",
      "directory-layout",
      "defaultLayout.json"
    ),
    {
      root: { props: {} },
      content: [
        {
          type: "directory-header",
          props: { id: "directory-header-default" },
        },
        {
          type: "MainContent",
          props: {
            id: "main-content-directory-default",
            content: [
              { type: "Directory", props: { id: "directory-default" } },
            ],
          },
        },
      ],
      zones: {},
    }
  );
  fs.writeJsonSync(
    path.join(libraryDirectory, "layouts", "locator-layout", "metadata.json"),
    {
      id: "locator-layout",
      displayName: "Locator",
      pageSetType: "LOCATOR",
    }
  );
  fs.writeJsonSync(
    path.join(
      libraryDirectory,
      "layouts",
      "locator-layout",
      "defaultLayout.json"
    ),
    {
      root: { props: {} },
      content: [
        {
          type: "MainContent",
          props: {
            id: "main-content-locator-default",
            content: [
              { type: "Locator", props: { id: "locator-default" } },
              {
                type: "locator-helper",
                props: { id: "locator-helper-default" },
              },
            ],
          },
        },
      ],
      zones: {},
    }
  );
  return rootDir;
};
