import path from "node:path";
import fs from "fs-extra";
import ts from "typescript";

const GENERATED_FILE_PREFIX =
  "/** THIS FILE IS GENERATED BY THE SECTION LIBRARY PLUGIN */";

type LibraryMetadata = {
  schemaVersion: 1;
  id: string;
  displayName: string;
  description: string;
};

type LayoutMetadata = {
  id: string;
  displayName: string;
  previewImageUrl: string;
  vertical?: string;
  purpose?: string;
  pageSetType: "ENTITY";
};

type Section = {
  id: string;
  displayName: string;
  description: string;
  category?: string;
  sourcePath: string;
};

type Layout = {
  metadata: LayoutMetadata;
  defaultLayout: unknown;
};

type SectionLibrary = {
  metadata: LibraryMetadata;
  sections: Section[];
  layout: Layout;
};

type GeneratedSectionLibrary = {
  generatedFiles: string[];
  manifestSource?: string;
};

/**
 * Reads one Entity-only Section Library and writes the Pages source that it needs.
 *
 * 1. Validate the metadata, sections, and default layout under `src/library`.
 * 2. Generate the Puck config and render and editor templates.
 * 3. Write current Platform manifest entries and return the future artifact manifest.
 */
export const generateSectionLibraryFiles = (
  rootDir: string
): GeneratedSectionLibrary => {
  const library = readSectionLibrary(rootDir);
  if (!library) {
    cleanupStaleGeneratedFiles(rootDir, new Set());
    return { generatedFiles: [] };
  }

  const generatedDirectory = path.join(rootDir, "src", "library", ".generated");
  const configPath = path.join(generatedDirectory, "libraryConfig.tsx");
  const layoutId = library.layout.metadata.id;
  const templatePaths = [
    configPath,
    path.join(rootDir, "src", "templates", `${layoutId}.tsx`),
    path.join(rootDir, "src", "templates", "main.tsx"),
    path.join(rootDir, "src", "templates", `edit-${layoutId}.tsx`),
    path.join(rootDir, "src", "templates", "edit.tsx"),
  ];

  writeGeneratedFile(configPath, buildConfigSource(rootDir, library.sections));
  writeGeneratedFile(templatePaths[1], buildRenderTemplateSource(layoutId));
  writeGeneratedFile(templatePaths[2], buildRenderTemplateSource(layoutId));
  writeGeneratedFile(templatePaths[3], buildEditorTemplateSource(layoutId));
  writeGeneratedFile(
    templatePaths[4],
    buildEditorTemplateSource(layoutId, "edit")
  );
  writeLegacyTemplateManifest(rootDir, library.layout);
  cleanupStaleGeneratedFiles(rootDir, new Set(templatePaths));

  return {
    generatedFiles: templatePaths,
    manifestSource: `${JSON.stringify(
      {
        schemaVersion: 1,
        library: library.metadata,
        layouts: [
          {
            ...library.layout.metadata,
            templateId: layoutId,
            editorPath: `edit/${layoutId}`,
            defaultLayout: library.layout.defaultLayout,
          },
        ],
      },
      null,
      2
    )}\n`,
  };
};

/** Reads and validates the Entity-only Section Library source. */
const readSectionLibrary = (rootDir: string): SectionLibrary | undefined => {
  const libraryDirectory = path.join(rootDir, "src", "library");
  const libraryPath = path.join(libraryDirectory, "library.json");
  if (!fs.existsSync(libraryPath)) {
    return undefined;
  }

  const metadata = readLibraryMetadata(libraryPath);
  const sections = readSections(rootDir, libraryDirectory);
  const layout = readLayout(libraryDirectory);
  validateLayoutReferences(layout, sections);
  return { metadata, sections, layout };
};

export const cleanupGeneratedSectionLibraryFiles = (
  generatedFiles: string[]
): void => {
  for (const filePath of generatedFiles) {
    if (isGeneratedFile(filePath)) {
      fs.removeSync(filePath);
    }
  }
};

const readLibraryMetadata = (filePath: string): LibraryMetadata => {
  const value = readJson(filePath, "library metadata");
  if (value.schemaVersion !== 1) {
    throw new Error(`${filePath} must set schemaVersion to 1`);
  }
  return {
    schemaVersion: 1,
    id: requireString(value.id, filePath, "id"),
    displayName: requireString(value.displayName, filePath, "displayName"),
    description: requireString(value.description, filePath, "description"),
  };
};

const readSections = (rootDir: string, libraryDirectory: string): Section[] => {
  const sectionsDirectory = path.join(libraryDirectory, "sections");
  if (!fs.existsSync(sectionsDirectory)) {
    return [];
  }

  const sectionIds = new Set<string>();
  return fs
    .readdirSync(sectionsDirectory, { withFileTypes: true })
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((entry) => {
      const sourcePath = path.join(sectionsDirectory, entry.name);
      if (entry.isDirectory()) {
        throw new Error(`Section directories are not supported: ${sourcePath}`);
      }
      if (!entry.isFile() || path.extname(entry.name) !== ".tsx") {
        throw new Error(`Sections must be .tsx files: ${sourcePath}`);
      }

      const id = path.basename(entry.name, ".tsx");
      if (!isSafeId(id) || sectionIds.has(id)) {
        throw new Error(`Section ID is not unique or valid: ${id}`);
      }
      sectionIds.add(id);
      return readSection(sourcePath, path.relative(rootDir, sourcePath), id);
    });
};

const readSection = (
  sourcePath: string,
  relativePath: string,
  id: string
): Section => {
  const sourceFile = ts.createSourceFile(
    sourcePath,
    fs.readFileSync(sourcePath, "utf8"),
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TSX
  );
  const exportsComponent = sourceFile.statements.some((statement) => {
    if (!hasExportModifier(statement)) {
      return false;
    }
    if (ts.isFunctionDeclaration(statement)) {
      return statement.name?.text === id;
    }
    return (
      ts.isVariableStatement(statement) &&
      statement.declarationList.declarations.some((declaration) => {
        return (
          ts.isIdentifier(declaration.name) && declaration.name.text === id
        );
      })
    );
  });
  if (!exportsComponent) {
    throw new Error(`${sourcePath} must named-export ${id}`);
  }

  const configStatement = sourceFile.statements.find((statement) => {
    return (
      ts.isVariableStatement(statement) &&
      hasExportModifier(statement) &&
      statement.declarationList.declarations.some((declaration) => {
        return (
          ts.isIdentifier(declaration.name) &&
          declaration.name.text === "config"
        );
      })
    );
  });
  if (!configStatement || !ts.isVariableStatement(configStatement)) {
    throw new Error(`${sourcePath} must named-export config`);
  }
  const declaration = configStatement.declarationList.declarations.find(
    (item) => ts.isIdentifier(item.name) && item.name.text === "config"
  );
  if (
    !declaration?.type ||
    !ts.isTypeReferenceNode(declaration.type) ||
    !ts.isIdentifier(declaration.type.typeName) ||
    declaration.type.typeName.text !== "SectionConfig"
  ) {
    throw new Error(`${sourcePath} config must use the SectionConfig type`);
  }
  if (
    !declaration?.initializer ||
    !ts.isObjectLiteralExpression(declaration.initializer)
  ) {
    throw new Error(`${sourcePath} config must be an object literal`);
  }

  const config = declaration.initializer;
  const pageSetTypes = getProperty(config, "pageSetTypes");
  if (
    !pageSetTypes ||
    !ts.isArrayLiteralExpression(pageSetTypes) ||
    pageSetTypes.elements.length === 0 ||
    pageSetTypes.elements.some(
      (element) => !ts.isStringLiteral(element) || element.text !== "ENTITY"
    )
  ) {
    throw new Error(
      `${sourcePath} config.pageSetTypes must contain only ENTITY`
    );
  }

  return {
    id,
    displayName: getRequiredStringProperty(config, "displayName", sourcePath),
    description: getRequiredStringProperty(config, "description", sourcePath),
    ...getOptionalStringProperty(config, "category", sourcePath),
    sourcePath: relativePath,
  };
};

const readLayout = (libraryDirectory: string): Layout => {
  const layoutsDirectory = path.join(libraryDirectory, "layouts");
  if (!fs.existsSync(layoutsDirectory)) {
    throw new Error(`Missing layouts directory at ${layoutsDirectory}`);
  }
  const layouts = fs
    .readdirSync(layoutsDirectory, { withFileTypes: true })
    .filter((entry) => entry.isDirectory());
  if (layouts.length !== 1) {
    throw new Error(
      "Section Library build mode requires exactly one ENTITY layout"
    );
  }

  const layoutDirectory = path.join(layoutsDirectory, layouts[0].name);
  const metadataPath = path.join(layoutDirectory, "metadata.json");
  const metadataValue = readJson(metadataPath, "layout metadata");
  if (metadataValue.pageSetType !== "ENTITY") {
    throw new Error(`${metadataPath} must set pageSetType to ENTITY`);
  }
  const metadata: LayoutMetadata = {
    id: requireString(metadataValue.id, metadataPath, "id"),
    displayName: requireString(
      metadataValue.displayName,
      metadataPath,
      "displayName"
    ),
    previewImageUrl: requireString(
      metadataValue.previewImageUrl,
      metadataPath,
      "previewImageUrl"
    ),
    ...(metadataValue.vertical === undefined
      ? {}
      : {
          vertical: requireString(
            metadataValue.vertical,
            metadataPath,
            "vertical"
          ),
        }),
    ...(metadataValue.purpose === undefined
      ? {}
      : {
          purpose: requireString(
            metadataValue.purpose,
            metadataPath,
            "purpose"
          ),
        }),
    pageSetType: "ENTITY",
  };
  if (!isSafeId(metadata.id)) {
    throw new Error(`Layout ID is not valid: ${metadata.id}`);
  }
  return {
    metadata,
    defaultLayout: readJson(
      path.join(layoutDirectory, "defaultLayout.json"),
      `default layout for ${metadata.id}`
    ),
  };
};

const validateLayoutReferences = (
  layout: Layout,
  sections: Section[]
): void => {
  const sectionIds = new Set(sections.map((section) => section.id));
  for (const componentId of collectComponentIds(layout.defaultLayout)) {
    if (!sectionIds.has(componentId)) {
      throw new Error(
        `Layout ${layout.metadata.id} references missing section ${componentId}`
      );
    }
  }
};

const collectComponentIds = (value: unknown): string[] => {
  if (!value || typeof value !== "object") {
    return [];
  }
  const layout = value as Record<string, unknown>;
  return [
    ...collectComponentList(layout.content),
    ...Object.values(layout.zones ?? {}).flatMap(collectComponentList),
  ];
};

const collectComponentList = (value: unknown): string[] => {
  if (!Array.isArray(value)) {
    return [];
  }
  return value.flatMap((value) => {
    if (!value || typeof value !== "object") {
      return [];
    }
    const component = value as Record<string, unknown>;
    if (typeof component.type !== "string" || !component.props) {
      return [];
    }
    const props = component.props as Record<string, unknown>;
    const slots =
      props.slots && typeof props.slots === "object"
        ? Object.values(props.slots).flatMap(collectComponentList)
        : [];
    const mainContent =
      component.type === "MainContent"
        ? collectComponentList(props.content)
        : [];
    return [
      ...(component.type === "MainContent" ? [] : [component.type]),
      ...slots,
      ...mainContent,
    ];
  });
};

/**
 * Writes temporary Platform compatibility entries for main and the real layout
 * ID. Remove these entries when Platform reads section-library-manifest.json.
 */
const writeLegacyTemplateManifest = (rootDir: string, layout: Layout): void => {
  const manifestPath = path.join(rootDir, ".template-manifest.json");
  if (fs.existsSync(manifestPath)) {
    return;
  }
  const defaultLayoutData = JSON.stringify(layout.defaultLayout);
  fs.writeFileSync(
    manifestPath,
    JSON.stringify(
      {
        templates: [
          {
            name: "main",
            description:
              "Use this template to generate pages for each of your Locations.",
            exampleSiteUrl: "",
            layoutRequired: true,
            defaultLayoutData,
          },
          {
            name: layout.metadata.id,
            description: layout.metadata.displayName,
            exampleSiteUrl: "",
            layoutRequired: true,
            defaultLayoutData,
          },
        ],
      },
      null,
      2
    )
  );
};

const buildConfigSource = (rootDir: string, sections: Section[]): string => {
  const generatedPath = path.join(
    rootDir,
    "src",
    "library",
    ".generated",
    "libraryConfig.tsx"
  );
  const imports = sections.map((section, index) => {
    const importPath = path
      .relative(
        path.dirname(generatedPath),
        path.join(rootDir, section.sourcePath)
      )
      .replace(/\.tsx$/, "")
      .split(path.sep)
      .join("/");
    const specifier = importPath.startsWith(".")
      ? importPath
      : `./${importPath}`;
    return `import { ${section.id} as Section${index}, config as sectionConfig${index} } from ${JSON.stringify(specifier)};`;
  });
  const entries = sections.map((section, index) => {
    return `  { id: ${JSON.stringify(section.id)}, component: Section${index}, config: sectionConfig${index} },`;
  });
  return [
    GENERATED_FILE_PREFIX,
    'import { DropZone, type Config } from "@puckeditor/core";',
    'import { MainContent, type SectionConfig } from "@yext/visual-editor";',
    ...imports,
    "",
    'const sections: { id: string; component: Config["components"][string]; config: SectionConfig }[] = [',
    ...entries,
    "];",
    "",
    "const sectionsByCategory = sections.reduce<Record<string, typeof sections>>((categories, section) => {",
    '  const title = section.config.category ?? "Sections";',
    "  (categories[title] ??= []).push(section);",
    "  return categories;",
    "}, {});",
    "",
    "export const sectionLibraryConfig: Config = {",
    "  components: {",
    "    MainContent,",
    "    ...Object.fromEntries(sections.map((section) => [section.id, { ...section.component, label: section.config.displayName }])),",
    "  },",
    "  categories: {",
    '    structure: { title: "Structure", visible: false, components: ["MainContent"] },',
    '    other: { title: "Other", visible: false, components: [] },',
    "    ...Object.fromEntries(Object.entries(sectionsByCategory).map(([title, grouped]) => [`section:${title}`, { title, components: grouped.map((section) => section.id) }])),",
    "  },",
    "  root: {",
    '    render: () => <DropZone zone="default-zone" style={{ display: "flex", flexDirection: "column", minHeight: "100vh" }} /> ,',
    "  },",
    "};",
    "",
  ].join("\n");
};

const buildRenderTemplateSource = (layoutId: string): string => {
  return [
    GENERATED_FILE_PREFIX,
    'import "@yext/visual-editor/style.css";',
    'import "../index.css";',
    'import { Render, resolveAllData } from "@puckeditor/core";',
    'import { AnalyticsProvider, SchemaWrapper } from "@yext/pages-components";',
    'import { type GetHeadConfig, type GetPath, type HeadConfig, type TagType, type Template, type TemplateProps, type TemplateRenderProps, type TransformProps } from "@yext/pages";',
    'import { applyAnalytics, applyCertifiedFacts, applyHeaderScript, applyTheme, defaultThemeConfig, getCanonicalUrl, getPageMetadata, getSchema, GTMBody, injectTranslations, resolveUrlTemplate, VisualEditorProvider } from "@yext/visual-editor";',
    'import { sectionLibraryConfig } from "../library/.generated/libraryConfig";',
    "",
    `const layoutId = ${JSON.stringify(layoutId)};`,
    "",
    "export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = (data): HeadConfig => {",
    "  const { title, description } = getPageMetadata(data.document);",
    "  const faviconUrl = data.document?._favicon ?? data.document?._site?.favicon?.url;",
    "  return {",
    '    title: title ?? "",',
    '    charset: "UTF-8",',
    '    viewport: "width=device-width, initial-scale=1",',
    "    tags: [",
    '      ...(data.document.siteDomain ? [{ type: "link" as TagType, attributes: { rel: "canonical", href: getCanonicalUrl(data) } }] : []),',
    '      ...(description ? [{ type: "meta" as TagType, attributes: { name: "description", content: description } }] : []),',
    '      ...(faviconUrl ? [{ type: "link" as TagType, attributes: { rel: "icon", type: "image/png", href: faviconUrl } }] : []),',
    "    ],",
    '    other: [applyAnalytics(data.document), applyHeaderScript(data.document), applyTheme(data.document, data.relativePrefixToRoot, defaultThemeConfig), SchemaWrapper(getSchema(data)), applyCertifiedFacts(data.document)].join("\\n"),',
    "  };",
    "};",
    "",
    "export const getPath: GetPath<TemplateProps> = ({ document }) => {",
    '  try { return resolveUrlTemplate(document, ""); } catch { return layoutId; }',
    "};",
    "",
    "export const transformProps: TransformProps<TemplateProps> = async (props) => {",
    "  const layout = props.document.__?.layout;",
    "  if (layout) {",
    "    props.document.__.layout = JSON.stringify(await resolveAllData(JSON.parse(layout), sectionLibraryConfig, { streamDocument: props.document }));",
    "  }",
    "  return { ...props, document: props.document, translations: await injectTranslations(props.document) };",
    "};",
    "",
    "const SectionLibraryLayout: Template<TemplateRenderProps> = (props) => {",
    "  let data = {};",
    '  try { data = JSON.parse(props.document.__?.layout ?? "{}"); } catch { /* Render an empty page when Platform has no layout. */ }',
    "  return (",
    '    <AnalyticsProvider apiKey={props.document?._env?.YEXT_PUBLIC_VISUAL_EDITOR_APP_API_KEY} templateData={props} currency="USD">',
    "      <VisualEditorProvider templateProps={props}>",
    "        <GTMBody><Render config={sectionLibraryConfig} data={data} metadata={{ streamDocument: props.document }} /></GTMBody>",
    "      </VisualEditorProvider>",
    "    </AnalyticsProvider>",
    "  );",
    "};",
    "",
    "export default SectionLibraryLayout;",
    "",
  ].join("\n");
};

const buildEditorTemplateSource = (
  layoutId: string,
  templateId = `edit-${layoutId}`
): string => {
  return [
    GENERATED_FILE_PREFIX,
    'import "@yext/visual-editor/editor.css";',
    'import "../index.css";',
    'import { type GetHeadConfig, type GetPath, type HeadConfig, type TemplateConfig, type TemplateProps, type TemplateRenderProps } from "@yext/pages";',
    'import { applyTheme, defaultThemeConfig, Editor, usePlatformBridgeDocument, usePlatformBridgeEntityFields, VisualEditorProvider } from "@yext/visual-editor";',
    'import tailwindConfig from "../../tailwind.config";',
    'import { sectionLibraryConfig } from "../library/.generated/libraryConfig";',
    "",
    `const editorPath = ${JSON.stringify(templateId === "edit" ? "edit" : `edit/${layoutId}`)};`,
    `const editorName = ${JSON.stringify(templateId)};`,
    "",
    "export const getPath: GetPath<TemplateProps> = () => editorPath;",
    "export const config: TemplateConfig = { name: editorName };",
    "export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = ({ document }): HeadConfig => ({",
    "  title: editorName,",
    '  other: applyTheme(document, "./", defaultThemeConfig),',
    "});",
    "",
    "const Edit = (): JSX.Element => {",
    "  const document = usePlatformBridgeDocument();",
    "  const entityFields = usePlatformBridgeEntityFields();",
    "  return <VisualEditorProvider templateProps={{ document }} entityFields={entityFields} tailwindConfig={tailwindConfig}><Editor document={document} componentRegistry={{ main: sectionLibraryConfig }} themeConfig={defaultThemeConfig} /></VisualEditorProvider>;",
    "};",
    "",
    "export default Edit;",
    "",
  ].join("\n");
};

const cleanupStaleGeneratedFiles = (
  rootDir: string,
  activeFiles: Set<string>
): void => {
  const templatesDirectory = path.join(rootDir, "src", "templates");
  const generatedFiles = fs.existsSync(templatesDirectory)
    ? fs
        .readdirSync(templatesDirectory)
        .map((name) => path.join(templatesDirectory, name))
        .filter(isGeneratedFile)
    : [];
  for (const filePath of [
    path.join(rootDir, "src", "library", ".generated", "libraryConfig.tsx"),
    ...generatedFiles,
  ]) {
    if (!activeFiles.has(filePath) && isGeneratedFile(filePath)) {
      fs.removeSync(filePath);
    }
  }
};

const writeGeneratedFile = (filePath: string, source: string): void => {
  fs.ensureDirSync(path.dirname(filePath));
  fs.writeFileSync(filePath, source);
};

const isGeneratedFile = (filePath: string): boolean => {
  return (
    fs.existsSync(filePath) &&
    fs.readFileSync(filePath, "utf8").startsWith(GENERATED_FILE_PREFIX)
  );
};

const readJson = (
  filePath: string,
  description: string
): Record<string, unknown> => {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing ${description} at ${filePath}`);
  }
  try {
    const value: unknown = JSON.parse(fs.readFileSync(filePath, "utf8"));
    if (!value || typeof value !== "object" || Array.isArray(value)) {
      throw new Error("must be a JSON object");
    }
    return value as Record<string, unknown>;
  } catch (error) {
    throw new Error(
      `Could not parse ${description} at ${filePath}: ${error instanceof Error ? error.message : String(error)}`
    );
  }
};

const requireString = (
  value: unknown,
  filePath: string,
  field: string
): string => {
  if (typeof value !== "string") {
    throw new Error(`${filePath} must define a string ${field}`);
  }
  return value;
};

const hasExportModifier = (statement: ts.Statement): boolean => {
  if (!ts.canHaveModifiers(statement)) {
    return false;
  }
  return !!ts
    .getModifiers(statement)
    ?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword);
};

const getProperty = (
  object: ts.ObjectLiteralExpression,
  name: string
): ts.Expression | undefined => {
  const property = object.properties.find((property) => {
    return (
      ts.isPropertyAssignment(property) &&
      ts.isIdentifier(property.name) &&
      property.name.text === name
    );
  });
  return property && ts.isPropertyAssignment(property)
    ? property.initializer
    : undefined;
};

const getRequiredStringProperty = (
  object: ts.ObjectLiteralExpression,
  name: string,
  sourcePath: string
): string => {
  const value = getProperty(object, name);
  if (!value || !ts.isStringLiteral(value) || !value.text) {
    throw new Error(`${sourcePath} config must define a non-empty ${name}`);
  }
  return value.text;
};

const getOptionalStringProperty = (
  object: ts.ObjectLiteralExpression,
  name: string,
  sourcePath: string
): { category?: string } => {
  const value = getProperty(object, name);
  if (!value) {
    return {};
  }
  if (!ts.isStringLiteral(value) || !value.text) {
    throw new Error(`${sourcePath} config ${name} must be a non-empty string`);
  }
  return { category: value.text };
};

const isSafeId = (value: string): boolean => /^[A-Za-z0-9_-]+$/.test(value);
