name: Automated Linting
on:
  workflow_call:
    secrets:
      BOT_REPO_SCOPED_TOKEN:
        required: true

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.BOT_REPO_SCOPED_TOKEN }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
      - run: pnpm i --ignore-scripts

      - run: pnpm run lint
        name: Running linter
        id: eslint
        # As of this comment, there are many linting errors in pages-components.
        # This is a temporary fix to allow the workflow continue providing
        # autofixes while these errors are being addressed.
        continue-on-error: true
      - run: pnpm run prettier
        name: Running prettier

      - name: Push changes
        id: push-changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated linting/prettier update"
          add: "*"
          push: true
          pull: --rebase --autostash
          default_author: github_actions

      - name: Fail job if push changes
        if: steps.push-changes.outputs.pushed == 'true'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Linting/Prettier changes were made. A new commit with autofixes was pushed.')
      - name: Fail job on linting error
        if: steps.eslint.outcome == 'failure'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('ESLint found errors that must be manually fixed. See step: Running linter.')
