name: Autogenerate Component Docs
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  generate-docs:
    name: Generate & Commit Docs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/visual-editor

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: "Install dependencies"
        run: pnpm i --frozen-lockfile --ignore-scripts

      - name: Generate Documentation
        run: pnpm run generate-component-docs

      - name: Commit and Push Documentation Changes
        run: |
          DOCS_FILE="src/docs/components.md"

          # Check if the docs file has actually changed
          if [[ -n $(git status --porcelain $DOCS_FILE) ]]; then
            echo "✅ Documentation has changed. Committing and pushing..."
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add $DOCS_FILE
            git commit -m "docs: auto-generate component documentation"
            git push
          fi
