name: Generate Component Docs
on:
  workflow_call:
    secrets:
      BOT_REPO_SCOPED_TOKEN:
        required: true

jobs:
  generate-docs:
    name: Generate & Commit Docs
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./packages/visual-editor"

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.BOT_REPO_SCOPED_TOKEN }}

      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Install deps
        run: pnpm i --frozen-lockfile --ignore-scripts

      - name: Build
        run: pnpm run build

      - name: Generate Documentation
        run: pnpm run generate-component-docs

      - name: Running prettier
        run: pnpm run prettier

      - name: Commit Documentation Changes
        id: commit_docs
        uses: EndBug/add-and-commit@v9
        with:
          add: '["packages/visual-editor/src/docs/components.md", "packages/visual-editor/src/docs/ai/components.d.ts"]'
          message: "docs: auto-generate component documentation"
          push: true
          default_author: github_actions

      - name: Fail job if push changes
        if: steps.commit_docs.outputs.pushed == 'true'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Docs were updated automatically.')
