name: Check i18n

on:
  pull_request:
    paths:
      # Trigger on changes to locale files
      - "packages/visual-editor/locales/**"
      # Trigger on changes to source files that might introduce new i18n keys
      - "packages/visual-editor/src/**"
      # Trigger on changes to the i18n scanner configuration
      - "packages/visual-editor/i18next-scanner.config.cjs"
      # Trigger on changes to the workflow file itself
      - ".github/workflows/check-locales.yml"

jobs:
  check-locales:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/visual-editor
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
      - run: pnpm i --ignore-scripts

      - name: Run i18n scan
        run: pnpm run i18n:scan

      - name: Push changes
        id: push-changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Check i18n/i18n updates"
          add: "*"
          push: true
          pull: --rebase --autostash
          default_author: github_actions

      - name: Fail job if push changes
        if: steps.push-changes.outputs.pushed == 'true'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('i18n changes were made. A new commit with autofixes was pushed.')
