name: Publish Package

on:
  push:
    tags:
      - "*"

permissions:
  id-token: write

jobs:
  publish:
    if: github.repository == 'yext/visual-editor'
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Set node version to 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/
          always-auth: true
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --ignore-scripts --frozen-lockfile

      - name: Update npm
        run: npm install -g npm@latest

      # Debugging/logging section
      - name: Debug npm auth + registry
        run: |
          echo "== npm whoami =="
          npm whoami --registry=https://registry.npmjs.org/ || echo "❌ whoami failed"

          echo "== npm registry =="
          npm config get registry

          echo "== npm access for current user =="
          npm access ls-packages $(npm whoami) || echo "❌ access check failed"

      - name: Publish package
        run: pnpm run ci-publish ${{ github.ref_name }}
