- name: Detect deleted nested keys
  id: detect
  run: |
    BASE_SHA=$(jq -r '.pull_request.base.sha' "$GITHUB_EVENT_PATH")
    HEAD_SHA=$(jq -r '.pull_request.head.sha' "$GITHUB_EVENT_PATH")

    LOCALE_DIR="packages/visual-editor/locales"

    echo "Base SHA: $BASE_SHA"
    echo "Head SHA: $HEAD_SHA"
    echo "Locale directory: $LOCALE_DIR"

    declare -A deleted_map

    flatten_keys() {
      jq -r 'paths(scalars) | map(tostring) | join(".")' "$1" | sort
    }

    files_changed=$(git diff --name-only "$BASE_SHA" "$HEAD_SHA" -- "$LOCALE_DIR")
    echo "Changed locale files:"
    echo "$files_changed"

    for file in $files_changed; do
      [[ "$file" != *.json ]] && continue

      echo "Checking locale file: $file"
      LANG=$(basename "$(dirname "$file")")
      echo "Detected language: $LANG"

      TMP_BASE=$(mktemp)
      TMP_HEAD=$(mktemp)

      git show "${BASE_SHA}:${file}" > "$TMP_BASE" 2>/dev/null || continue
      git show "${HEAD_SHA}:${file}" > "$TMP_HEAD" 2>/dev/null || echo '{}' > "$TMP_HEAD"

      flatten_keys "$TMP_BASE" > base_keys.txt
      flatten_keys "$TMP_HEAD" > head_keys.txt

      DELETED_KEYS=$(comm -23 base_keys.txt head_keys.txt)

      if [ -n "$DELETED_KEYS" ]; then
        echo "Deleted keys found in $file:"
        echo "$DELETED_KEYS"
      fi

      while read -r key; do
        [[ -z "$key" ]] && continue
        deleted_map["$key"]+="${LANG} "
      done < <(echo "$DELETED_KEYS")
    done

    echo "Total unique deleted keys: ${#deleted_map[@]}"

    if [ ${#deleted_map[@]} -gt 0 ]; then
      OUTPUT="### 🔤 Deleted Translation Keys (consolidated)\n"

      declare -A grouped
      for key in "${!deleted_map[@]}"; do
        group="${key%%.*}"
        grouped["$group"]+="$key"$'\n'
      done

      for group in $(printf "%s\n" "${!grouped[@]}" | sort); do
        OUTPUT+="\n#### \`$group\`\n\n"
        OUTPUT+="| Key | Languages Removed |\n| --- | ----------------- |\n"

        while read -r key; do
          [[ -z "$key" ]] && continue
          langs=$(echo "${deleted_map[$key]}" | xargs -n1 | sort | uniq | paste -sd ', ' -)
          OUTPUT+="| \`$key\` | $langs |\n"
        done < <(printf "%s" "${grouped[$group]}" | sort)
      done

      echo "comment<<EOF" >> "$GITHUB_OUTPUT"
      echo -e "$OUTPUT" >> "$GITHUB_OUTPUT"
      echo "EOF" >> "$GITHUB_OUTPUT"
      echo "has_deleted=true" >> "$GITHUB_OUTPUT"
    else
      echo "No deleted keys detected."
      echo "has_deleted=false" >> "$GITHUB_OUTPUT"
    fi
